### ISSUE TITLE
Tidy up SA home view code

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1026]
https://github.com/mysociety/pombola/commit/84aa78f80d351b6b187945440ad9b156eab9f949

Ideally the `home` view function would become a CBV so that it could be subclassed in the country apps, any country specific config could be done in the country app and kept out of the core app. Once that is done the logic from the commit above can be moved into the SA application and tidied up a bit.

**Comment by paullenz** [comment]
Closing, as agreed with chrismytton as no longer significant
