### ISSUE TITLE
For speeches/sections get "edit in admin" link working

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#1048]
Eg at bottom of http://za-pombola.staging.mysociety.org/hansard/2811 or http://za-pombola.staging.mysociety.org/hansard/speech/26783

![view_section__impact_of_deterioration_of_natural_environment_on_tourism__member_s_statement_____pombola_south_africa-2](https://f.cloud.github.com/assets/187630/1614146/5333ce0c-55e6-11e3-90ab-972c30322a8a.png)

- [ ] add in name of section/speech
- [ ] make link point to item in admin

**Comment by paullenz** [comment]
No demand for this from user - suggest link is simply removed

**Comment by JenMysoc** [comment]
Link works
