### ISSUE TITLE
Zimbabwe: Slug notation error?

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1064]
From @teuben

> perhaps I have been abusing the SLUG notation for my own use and got bitten by it... I'm debating if this is a feature or a bug.
> 
> When we created slugs, I saw this long linear lists on info pages, so decided the top bar ones, the ones that really only have other slugs listed in a page, prepended them with "m" (for menubar), so i had slugs like m-democracy-resources.  On that page we have 4 links, or 4 dropdowns....
> 
> Now if you click on that top bar, ie. one is on http://www.kuvakazim.com/info/m-democracy-resources the line below the logo gives the hierarchy in the system
> 
>     Home » Information » M Democracy Resources
> 
> and it looks like django has reverse translated my slug into a Camel Code, bjut with spaces, notation.   The "M"  now looks a little awkward.
> 
> So the question is:  is that a feature or a bug of either Django or Pombola?  The code does have the title in it, so I kinda expected my title (Democracy Resources) to be used here, not the reverse engineered slug.
> 
> Second guessing, if I now remove the 'm-' from my slug names online, and edit the appropriate html files in pombola, you think this will work just fine.   My guess is yes.

**Comment by paullenz** [comment]
I would suggest that this is resolved through updating the slug as per the comment of 27/11/13 - closing the ticket for now
