### ISSUE TITLE
Issue with empty sections in Hansard parsing

### ISSUE THREAD

**Issue by osfameron** [mysociety/pombola#1072]
See for example http://za-pombola.staging.mysociety.org/hansard/2154 

Assumption is that there are several consecutive headings:

 * Announcements, Tablings And Committee Reports
 * Appropriation Bill

Perhaps Appropriation Bill should be nested underneath?  Or the two headings should be merged together.

**Comment by tmtmtmtm** [comment]
Looks like this was closed by #1512 (but not auto-closed due to formatting of PR message)
