### ISSUE TITLE
Investigate the ajax_select assets 404ing

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#1101]
On the admin pages (eg http://127.0.0.1:8000/admin/) various static assets for ajax_select` are 404ing - for the `south_africa` setup at least.

![site_administration___pombola_site_admin-2](https://f.cloud.github.com/assets/187630/1743673/89d64c90-6410-11e3-84c5-29640255d6bb.png)

These are being loaded in [pombola/admin_additions/templates/admin/base_site.html](https://github.com/mysociety/pombola/blob/master/pombola/admin_additions/templates/admin/base_site.html)

Perhaps best tackled by just removing it all - see #1102

**Comment by paullenz** [comment]
As not been flagged as an issue for two years, closing
