### ISSUE TITLE
Formatting bug on contact details tab

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1108]
On http://www.shineyoureye.org/person/mohammed-zakari/contact_details/ the label website runs over the content

**Comment by tmtmtmtm** [comment]
@paullenz — looks like this is no longer an issue:

![screen shot 2015-11-13 at 15 17 50](https://cloud.githubusercontent.com/assets/57483/11149312/c350282a-8a19-11e5-9a24-c23333709a60.png)

(Tried at various widths, font-sizes, etc)

If you can replicate, can you add a screenshot when you re-open?
