### ISSUE TITLE
try using git-annex or git-media for storing compiled assets

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1143]
@evdb makes a strong case for being able to:

1. Knowing exactly what assets were being used by a bug reporter, not dependent on versions of compass, yui-compresser, etc.
2. Being able to deploy without compiling assets on the server (and thus needing compass et al on the server) - this could speed up deployment as well.

I'd be reluctant to commit these generated files in the repository, though. However, there are tools like [git annex](http://git-annex.branchable.com/) and [git media](https://github.com/schacon/git-media) which let you precisely specify versions of binary assets and fetch them from a fileserver.  If these work as expected, it might be a nice solution to the above, although I haven't looked at either in much depth.  This ticket is to investigate whether this would be a good solution for pombola.

**Comment by tmtmtmtm** [comment]
If this investigation hasn't happened a couple of years later, I'm assuming it's not something particularly useful/important.

**Comment by mhl** [comment]
Yes, I think we're doing OK with the current system - there haven't been actual problems with this that I can remember.
