### ISSUE TITLE
Move hansard entries linked to Rachael Nduku Ndambuki to Regina Muia

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1209]
Move hansard entries under Rachael Nduku Ndambuki's profile to http://info.mzalendo.com/person/regina-nthambi-muia/. Rachael Ndambuki is not an MP and Regina's other surname is Ndambuki.

**Comment by tmtmtmtm** [comment]
This doesn't seem to be an issue any longer —  there are currently [no search results for Rachael Ndambuki](http://info.mzalendo.com/search/?q=Ndambuki&section=persons&order=relevance):

![screen shot 2015-11-24 at 12 30 53](https://cloud.githubusercontent.com/assets/57483/11366778/65df586e-92a7-11e5-8cb2-a7f128e96744.png)
