### ISSUE TITLE
ZA Pombola - NCOP should show reps groups by province

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1242]
Members of the NCOP should also be grouped by provinces and this should match what you see here  http://www.pmg.org.za/node/30337

**Comment by tmtmtmtm** [comment]
@paullenz — it's difficult to understand what this ticket refers to, as the linked page on pmg.org.za no longer exists, and http://www.pa.org.za/organisation/ncop/people/?office=1 only includes three people.

If I had to guess I'd say you're actually talking about the [full version of that page](http://www.pa.org.za/organisation/ncop/people/):

![screen shot 2015-12-19 at 12 37 21](https://cloud.githubusercontent.com/assets/57483/11912999/8a99d788-a64d-11e5-878c-36d98f17d13f.png)

but it's unclear what the suggestion is here, or whether this is something that no longer applies. 

Is this to do with being able to see all the members for Mpumalanga together?

**Comment by gailefullard** [comment]
The province from which each NCOP MP comes is now clear. The provincial legislature membership is clear. The groupings for each provinicial legislature is clear under PEOPLE. It would be a NICE TO HAVE to use the provincial dropdown menu you inserted at http://www.pa.org.za/position/member/parliament/?order=name and include it here instead [but still retain the alphabetical sort option]

**Comment by tmtmtmtm** [comment]
Thanks @gailefullard. I'll close this, and add the request for the Province filter as https://github.com/mysociety/pombola/issues/1949
