### ISSUE TITLE
Politicians' All appearances template is missing some styling

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#1261]
http://www.pa.org.za/person/cornelius-petrus-mulder/appearances/hansard

For some reason the sidebar styling is missing, and it should probably keep the tabs at top from the main profile page (http://www.pa.org.za/person/cornelius-petrus-mulder/)

**Comment by tmtmtmtm** [comment]
@wrightmartin this page currently looks like this:

![screen shot 2015-11-13 at 17 56 54](https://cloud.githubusercontent.com/assets/57483/11153312/f292dd2e-8a2f-11e5-8dce-c21d30f07883.png)

Does that mean that the issue has been resolved, or am I misunderstanding the problem?

**Comment by wrightmartin** [comment]
@tmtmtmtm the latest design update to this page has rendered it obsolete, closing :)

**Comment by tmtmtmtm** [comment]
Excellent, thanks @wrightmartin.
