### ISSUE TITLE
Pre-populate location search result with the term I just typed in

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/pombola#1264]
So on this page
http://www.pa.org.za/place/latlon/-33.925,18.424/

The search box should have 'cape town' in it. Also it probably shouldn't be in that location on the page, since it encourages me to search again, rather than view the results produced below.

**Comment by tmtmtmtm** [comment]
@zarino / @mhl is any of this addressed by the work that's currently happening on this page?

**Comment by mhl** [comment]
I didn't have it in mind, but we can certainly do that.

**Comment by tmtmtmtm** [comment]
Great. It seems like a ticket that would be good to end up closed as a natural result of the current work (even if it's by doing something different), rather than something related that still hangs around for next time…
