### ISSUE TITLE
Make a whitelabel Pombola theme

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#1278]
It would be easier to start new instances of Pombola using a whitelabel theme.

This would be an un-opinionated default theme with basic styling and layouts for all common pages and features. This is not intended to be used as a theme itself, but a decent starting point for new themes.

As we work on new instances of Pombola any customisations we make should be considered to be added to the whitelabel theme going forward.

**Comment by paullenz** [comment]
Given the low likelihood of future Pombola instances, closing this ticket
