### ISSUE TITLE
switch to MEDIA_ROOT having a country-specific suffix

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1285]
In other words, if `COUNTRY_APP` is `south_africa` the MEDIA_ROOT would be:

```
/foo/bar/media_root_south_africa
```

... instead of:

```
/foo/bar/media_root
```

This would be make the `bin/switch-country script` (and switching between countries in development more generally) much simpler. The downside would be having to be careful to move the media_root for each deployment when upgrading to a version with this change.

Dunno really.

**Comment by tmtmtmtm** [comment]
I'm guessing this has been implicitly decided against by not happening?

**Comment by mhl** [comment]
I'd still like to do it, but it's just never higher priority than the other things we have to do. I hope you don't mind if I reopen this one.

**Comment by tmtmtmtm** [comment]
No problems with re-opening, but would be good if the title/description changed to more of a "Yep, we're going to do this" than a "Hmmm, I wonder if we should do this?" :)

**Comment by mhl** [comment]
:) Done

**Comment by chrismytton** [comment]
We've removed the switch-country script and are now moving towards a one-repo-per-country model, so I'm going to close this.
