### ISSUE TITLE
ZA: reduce noise from cron jobs

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1287]
For example, there are lots of errors from antiword that are expected, since it's frequently tried on non-Word documents. Also, there's no easy way to tell if the HTTP errors from question scraping and parsing are expected or not.

**Comment by duncanparkes** [comment]
I'd really like this one bumped up the priority list - it's hard to tell at the moment whether changes to things that run as cron jobs have broken them, because they mostly look broken already!

**Comment by tmtmtmtm** [comment]
We're opening individual tickets for these as they come up — no need for a meta-ticket for it.
