### ISSUE TITLE
Add URLs for tabs on people pages

### ISSUE THREAD

**Issue by BenJam** [mysociety/pombola#1292]
it would be great to create the following three URLS on pages like:

http://www.pa.org.za/person/adrian-john-williams/

namely:

```/profile``` the default profile information
```/appearances``` appearance information
```/roi``` register of interests

this would enable me to link to/share direct links to a representatives ROI in particular.

**Comment by mhl** [comment]
Fixed by https://github.com/mysociety/pombola/pull/1820
