### ISSUE TITLE
search results for questions should link to the question/answer pair section

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1303]
The bottom result of a search for [responsible aquaculture](http://www.pa.org.za/search/?q=aquaculture+responsible) is:

> Questions  Questions asked to the President of the Republic  >  NW886E - 14 August 2009
> President of the Republic: in view of the fact that only aquaculture, responsible for a mere 0.3% of the total national 

... which links to:

* http://www.pa.org.za/question/speech/368998

This is unhelpful on a couple of scores:
* The breadcrumbs don't include the question/answer pair section, which should link to http://www.pa.org.za/question/59796 at the end
* The title is empty quotes (fixed on `feature/switch-to-sayit-master`)
* Search results with a hit in a question or an answer should probably link to the section containing both the question and the answer rather than the individual speech anyway

**Comment by paullenz** [comment]
I believe that this will be resolved by https://github.com/mysociety/pombola/issues/1797 - which only deals in question and answer pairs - closing
