### ISSUE TITLE
there should be a public guide to administrating a pombola site

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1309]
I think it's clear that there are good reasons to have a public guide to administering a Pombola-based site - I'll leave it open as to whether this should be wiki, static pages we write, etc. etc.

**Comment by tmtmtmtm** [comment]
The admin is likely to change quite significantly soon anyway, as we move some stuff out to EP, and hopefully redesign what's left. We can revisit this if it's still deemed an issue after that.
