### ISSUE TITLE
ZA: Profile pages should show all contact information

### ISSUE THREAD

**Issue by geoffkilpin** [mysociety/pombola#1316]
Only certain contact information is currently displayed on the site. E.g. for http://www.pa.org.za/person/pieter-van-dalen/ we have YouTube, LinkedIn, and Who's Who data but this does not appear.

There also seems to be a bit of uncertainty around use of the telephone contact kinds - e.g. phone, cell, and voice (this MP is one example - we have the same number listed for both phone and cell).

**Comment by tmtmtmtm** [comment]
Currently this looks like:

![screen shot 2015-12-19 at 12 11 23](https://cloud.githubusercontent.com/assets/57483/11912900/a9ef8212-a649-11e5-9036-06475f621596.png)

**Comment by duncanparkes** [comment]
I can do a bit of tidying of the data when we deploy this, stripping spaces and '@' from twitter names, for instance.
