### ISSUE TITLE
A/B test a change to the front page of Mzalendo

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1325]
One of our aims in each sprint is to A/B test a change to one of the Pombola sites - since Mzalendo has the highest traffic, so would be the best chance to get a statistically significant result. One suggestion is to try a version of the front page that has a couple of clear calls to action, but we'd need to discuss this in the context of the goals of the site and current analytics.

**Comment by paullenz** [comment]
Homepage has been updated since then
