### ISSUE TITLE
merge south_africa_set_da_office_locations into south_africa_import_constituency_offices

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1326]
The `south_africa_import_constituency_offices` command is designed to be safely runnable multiple times; everything that `south_africa_set_da_office_locations` does could easily be added into the former command, rather than being a separate step to run.

**Comment by tmtmtmtm** [comment]
@mhl will this be obsolete with the new approach in #1938?

**Comment by mhl** [comment]
I'm not sure that it's really a new approach? - it just seems to be that we get constituency office updates in a different enough format each time that it usually makes sense to write a clean new script to do the update. (There's a ticket for that underlying issue here: https://github.com/mysociety/pombola/issues/1311 but I'm not sure if there's any prospect of fixing that.) However, I do think this issue should be closed; we'll certainly want to reassess what's worth doing the next time we have to do an update rather than having this issue as something in the backlog that we might work on in isolation.
