### ISSUE TITLE
look at unmerged commits on sayit's pombola branch

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1376]
One of these is a pull request which can now be merged, the others are probably required by za-hansard, but not currently being used, so need some consideration.

**Comment by tmtmtmtm** [comment]
@mhl is this still an issue?

**Comment by mhl** [comment]
Some should still be rescued, I think. Taking them in order:

* Ignore (probably): mysociety/sayit@51f1948e2c068be45c10 A small change to the `sayit_rerun_popit_resolver` command which isn't used anywhere and I didn't realise existed. It attempts to change the people that a SayIt speaker is associated with based on `popit_name_resolver`. This command should either be removed or reimplemented completely to deal with some obvious problems with it and make it use the new `popolo_name_resolver` instead. I'm inclined to go for "remove".
* Ignore: mysociety/sayit@7c597570eae0379ae09e006 a CSS change that doesn't apply any more
* Take: mysociety/sayit@24428b51033e1b569 - still useful, and za_hansard attempts to use the option it introduces. We should turn that into a SayIt PR.
* Ignore: mysociety/sayit@5cc63c8d365e48fe7c80 - I believe this functionality is already merged in mysociety/sayit@d1b870418a8a3bc4

**Comment by mhl** [comment]
My mistake - the third one should now be in za-hansard - I've ported it to there (mysociety/za-hansard@22b0bfcf943eb495df54d4) and deployed it, so I think this issue can be closed now.
