### ISSUE TITLE
Poor formatting of questions/answers in Pombola ZA

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1380]
e.g. http://www.pa.org.za/speech/376404

**Comment by tmtmtmtm** [comment]
This is still an issue:

![screen shot 2015-11-13 at 15 26 38](https://cloud.githubusercontent.com/assets/57483/11149487/f6268c16-8a1a-11e5-9cf9-2039573946d1.png)

**Comment by paullenz** [comment]
This should be resolved as part of - https://github.com/mysociety/pombola/issues/1797 - closing for now
