### ISSUE TITLE
make "set -x" optional in run_management_command

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1382]
Some commands don't need the full `set -x` output (e.g. `feedback_report_pending`) where it's just noise.  I suggest we change `run_management_command` to take a `-v` option (i.e. check if `$1` is `-v`, and if so do `set -x` and `shift`).

**Comment by chrismytton** [comment]
The `set -x` was removed from in 241d3ff0647712c8cf87caf2694c949516399dac
