### ISSUE TITLE
add Pombola support to our generic install script

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1434]
The end result of this that we want is a Vagrant file that creates a Pombola instance with some minimal useful data in it, and where `bin/switch-country.py` gives you a working version for each of the different countries. (This would be similar to the [Alaveteli Vagrantfile](https://github.com/mysociety/alaveteli/blob/master/Vagrantfile) which just calls the generic install script.)

To avoid having to import huge database dumps or media directories, this should, for each country:
- Import person, position and organisation data from the live site's nightly export in Popolo JSON format (depends on: #1428) 
- Involve some way of importing MapIt data and the Place tables (and probably other data I've forgotten)
- Loading test fixtures to create anything else that's required for the country (e.g. Parliamentary Session dates)

**Comment by mhl** [comment]
The Vagrant file does now import data for each country (using the public database dumps instead of the Popolo JSON dump) so this can be closed.

See also #1892

**Comment by chrismytton** [comment]
We stopped using the generic install script in https://github.com/mysociety/pombola/pull/2605
