### ISSUE TITLE
Review GitHub Wiki

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/pombola#1438]
The [Pombola wiki](https://github.com/mysociety/pombola/wiki) on GitHub should either be overhauled (at least so it says "Pombola" not "Mzalendo") or ditched entirely in favour of better documentation elsewhere.

**Comment by tmtmtmtm** [comment]
Assigning @JenMysoc to clean everything out of here.

**Comment by JenMysoc** [comment]
Ok so there are two pages which would be useful to partners but should be stored somewhere like a documentation site as I doubt partners will look here. Since we don't HAVE a documentation site at the moment (see #1631) I will leave these here.
