### ISSUE TITLE
social_tools.html shouldn't assume it's being used on person URLs

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1460]
`social_tools.html` is included in pages other than person pages (e.g. place pages) but it includes this code:

    {% if settings.DISQUS_SHORTNAME %}
      <li>
        <a  href="{% url "person" slug=object.slug %}#disqus_thread"
            class="big-btn-text-green"
        >Post Comment</a>
      </li>
    {% endif %}

... which generates a person URL.

**Comment by paullenz** [comment]
Is this still an issue?

**Comment by tmtmtmtm** [comment]
Yes — if you look at http://info.mzalendo.com/place/kirinyaga-central-2013/, for example, the green comment button: 

![screen shot 2015-11-20 at 18 20 42](https://cloud.githubusercontent.com/assets/57483/11307963/6f0e8adc-8fb3-11e5-883a-7c82907385ef.png)

goes to http://info.mzalendo.com/person/kirinyaga-central-2013/#disqus_thread, which doesn't exist

**Comment by paullenz** [comment]
ahh - right - yes
