### ISSUE TITLE
Kenyan Hansard parsing issues

### ISSUE THREAD

**Issue by dracos** [mysociety/pombola#1468]
e.g. http://info.mzalendo.com/hansard/sitting/senate/2014-03-26 doesn't spot page numbers, the page disclaimer, or the Senate Majority Leader.

**Comment by tmtmtmtm** [comment]
We currently don't really have a way of assigning roles that will be held by different people over time. Hopefully this will be flow out of the work from https://github.com/mysociety/pombola/issues/1909

**Comment by dracos** [comment]
Okay, but that doesn't/wouldn't cover the fact that page has many "The electronic version of the Senate Hansard Report is for information purposes only. A certified version of this Report can be obtained from the Hansard Editor, Senate." and page numbers in it.

**Comment by tmtmtmtm** [comment]
Yep, thanks. Opened that one as https://github.com/mysociety/pombola/issues/2016
