### ISSUE TITLE
paragraph tags being rendered literally on People's Assembly

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/pombola#1477]
on
e.g. http://www.pa.org.za/hansard/2014/june/17/proceedings-at-joint-sitting-tuesday-17-june-2014/calling-of-joint-sitting-announcement

(`<p>` tags have `xmlns` attributes)

![screen-shot-2014-06-27-at-10 52 22](https://cloud.githubusercontent.com/assets/111320/3410048/2633b496-fde1-11e3-8049-166482329d6c.png)

**Comment by tmtmtmtm** [comment]
@davewhiteland do you know if this is still an issue? The linked page no longer has any content at all (which may or may not be a distinct problem in its own right):

![screen shot 2015-11-13 at 15 25 11](https://cloud.githubusercontent.com/assets/57483/11149458/c461c948-8a1a-11e5-8e85-1c6a0544d40c.png)

**Comment by tmtmtmtm** [comment]
This text appears correctly on http://www.pa.org.za/hansard/2014/june/17/proceedings-at-joint-sitting-tuesday-17-june-201-2/calling-of-joint-sitting-announcement, so I'm closing this. If the problem still exists somewhere else, we can re-open with a working (as in failing!) URL
