### ISSUE TITLE
ZA: questions page improvements

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1492]
PMG have requested several improvements to the questions page - we should break these out into new issues:

- [ ] Show a list of "most recently answered questions" at the top of `/questions`
- [ ] Pagination for ministries with many questions
- [ ] A snippet of the question text to be included on the question list pages, more like: http://myreps.sailing360.co.za/questions
- [ ] Remove the next and previous ministries links (they're a lot of noise if there are only a couple of questions.
- [ ] There are some duplicate ministries on the questions list page - they should be merged
- [ ] Perhaps make it more obvious how to get back to the index of questions (at the moment the link in the breadcrumbs isn't very obvious)

**Comment by paullenz** [comment]
closing as consolidating points in - https://github.com/mysociety/pombola/issues/1797
