### ISSUE TITLE
Adding information on Bills to the Mzalendo site

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1505]
In part replacing: https://github.com/mysociety/pombola/issues/1440

Content from prior ticket:

I have been doing a bit more digging around the area of bills for the website - in brief:

Kenya law looks like it has a good archive of who has been associated with various bills and PDFs that could be linked out to: http://kenyalaw.org/kl/index.php?id=4248

however it doesn't show people who have contributed to the bill other than the sponsor - I am struggling to find more details on this - see later also

there is a similar (but less easily parable as a PDF? - or rather multiple PDFs) - tracker on the gov site - http://www.parliament.go.ke/index.php/the-senate/house-business/bills-tracker

the actual bills themselves on the gov site are pretty poorly scanner PDFs - http://www.parliament.go.ke/plone/senate/business/bills-1/public-appointments-county-assemblies-approval-bill-2014/view

So I guess the main question is, when it comes to linking people to bills:

1) Is it okay to just have sponsors?
2) If the answer to 1) is "no" then what are your thoughts on getting hold of the additional information?

Update from Jessica on the Bill question:

Just the name of the bill and sponsors would be enough. Parliament does not have good copies of the bills. www.kenyalaw.org which is run by the Judiciary is the authoritative site for all legal info.

**Comment by davea** [comment]
I've made some progress on this, here's what it looks like right now on a profile page:

![screen shot 2015-01-20 at 14 27 56](https://cloud.githubusercontent.com/assets/4776/5818856/c5dc856e-a0b0-11e4-961a-9473c20e3ef3.png)

Each bill links directly to the PDF on kenyalaw.org. Am I on the right track?

**Comment by JessMusila** [comment]
Yes, on the right track. Where the bill has already been assented to link
to the Act.

**Comment by davea** [comment]
The profile page of a politician now shows only the 10 most recently sponsored bills:

![screen shot 2015-01-21 at 15 05 53](https://cloud.githubusercontent.com/assets/4776/5838553/2511b340-a180-11e4-9a7f-52a8850f8f30.png)

with a link to a page displayed all of their sponsored bills:

![screen shot 2015-01-21 at 15 06 57](https://cloud.githubusercontent.com/assets/4776/5838569/37e867ac-a180-11e4-91f9-7f70209992bb.png)

Those who have sponsored fewer than 10 bills and those who have never sponsored a bill aren't left out:

![screen shot 2015-01-21 at 15 05 11](https://cloud.githubusercontent.com/assets/4776/5838581/4a62e2d6-a180-11e4-8567-8873b066aee3.png)

![screen shot 2015-01-21 at 15 05 23](https://cloud.githubusercontent.com/assets/4776/5838590/5725ba16-a180-11e4-832e-11e6810fb202.png)

The details of the bills have been automatically imported from kenyalaw.org, meaning no tedious copy-pasting in the admin interface. At least not for past bills.

**Comment by JessMusila** [comment]
Looks good! If any Bill is already an Act please link to the Act. Aden
Duale is the Leader of Majority in the National Assembly so would have many
entries.

Uhuru Kenyatta (the President) and William Ruto (Deputy President) are no
longer part of Parliament so there should be no bills/motions/petitions or
statements on their profiles. They visit Parliament to give the State of
the Nation address only or on invitation by the Speakers.

**Comment by davea** [comment]
Hmm, in that case perhaps it's omitting the 'Bills Sponsored' section from the profiles of people who haven't sponsored any bills?

I will add fields so the link for an act can be added.

**Comment by davea** [comment]
This is now live on info.mzalendo.com.

I've imported all bills from 2013 & 2014, with the exception of *The Companies Bill, 2014* which doesn't seem to have a sponsor listed on [kenyalaw.org](http://kenyalaw.org/kl/index.php?id=4250).

Any bills that have been assented to and become Acts will need to be updated manually via the admin - the automatic import process didn't account for those. As soon as the act name and URL is given in the admin the site will link to the act instead of the bill PDF.

**Comment by JessMusila** [comment]
Thank you. I have sampled a few and it is looking good. 
Best,

Jessica
