### ISSUE TITLE
A - Z links on people pages

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1518]
On people pages like [People at National Council of Provinces](http://www.pa.org.za/organisation/ncop/people/) PMG have requested a clickable list of letters from A to Z across the top of the page.

The use case is if you're looking for someone and you know their surname but don't know the exact spelling you can still find them by clicking through to the correct letter then looking for them. At the moment the only solution is to click through all pages using the pagination until you find the person you're looking for.

**Comment by paullenz** [comment]
Detailed comments from PMG on this point:

It is about the new search menu for MP profiles: MP profiles
 
It is supposed to be alphabet-based so a user who wants info on an MP whose name starts with an M can access the MP quickly and not trudge through the multiple pages at the bottom.
 
The menu that has been used is a provincial dropdown menu.
 
The public does not know from which province an MP got into the National Assembly. Even the second house, the National Council of Provinces MPs are not well identified by province.
 
As the same search menu will be used for the other HOT TOPIC TABS: MP assets and MP attendance, it needs to be an alphabet menu - either drop down or a straight line of 26 letters to click on (and the pages of MPs at the bottom can be removed).

**Comment by JenMysoc** [comment]
This is the next top priority for PMG.

**Comment by tmtmtmtm** [comment]
https://github.com/mysociety/pombola/pull/1867 adds this for some of the required pages. We should check with PMG that this is suitable before adding it to the others.

**Comment by JenMysoc** [comment]
From PMG:

Very happy with this on http://www.pa.org.za/organisation/national-assembly/people/ except when you click on ALL, all 400 MPs should show. The pagination at the bottom really should be removed. [likewise for NCOP members]. However, the pagination complaint also referred to  HOT TOPICs MP Profiles page http://www.pa.org.za/position/member/parliament/?order=name should be working like this too but it can combine both NA & NCOP - the provincial legislatures are not part of HOT TOPICS

**Comment by tmtmtmtm** [comment]
@JenMysoc I think it's best if we leave this ticket as closed, and open new ones for the separate requests for things that still need to be done (i.e. one ticket for removing pagination, listing all the places where it should be removed; another ticket for the pages that also need to have the A-Z links added). I'm not sure whether the last part about the provincial legislatures not being part of HOT TOPICS is merely a passing comment/explanation, or a request that something should be fixed. If it's the latter, then that should probably be another ticket too.
