### ISSUE TITLE
ZA: SayIt thumbnail images get out of sync with Pombola images

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1543]
For example, C Mackenzie on the page here is associated with the right person (you can click through) but he has no thumbnail image on the SayIt-rendered page:

* http://www.pa.org.za/hansard/2014/july/16/proceedings-of-extended-public-committee-committ-3/hon-members-gcis#s424774

Reported by @geoffkilpin

**Comment by paullenz** [comment]
This appears to be resolved, as his image does display as a thumbnail on the sayit rendered page - closing
