### ISSUE TITLE
Link to Mathare MP's profile

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1547]
@mhl For some reason the Mathare MP's profile does not come up on the Mzalendo search http://info.mzalendo.com/position/member-national-assembly/?place_slug=mathare-2013

**Comment by tmtmtmtm** [comment]
Not sure of the history of this, but it looks like it's no longer an issue:

![mathare screen shot 2015-11-13 at 15 16 02](https://cloud.githubusercontent.com/assets/57483/11149256/7ef4b664-8a19-11e5-8c98-fff396a1b285.png)

@JessMusila feel free to re-open if I've misunderstood the issue, or if you see something like this again.
