### ISSUE TITLE
Translate for spanish is possible

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/pombola#1574]
Translate for spanish is possible?
Tnks

**Comment by johnfelipe** [comment]
Transifex for spanish?

**Comment by johnfelipe** [comment]
Hello again, transifex to spanish is possible?

**Comment by mhl** [comment]
This isn't possible at the moment, I'm afraid. I'm going to close this issue, since I think the work involved is well covered by these other issues:

* https://github.com/mysociety/pombola/labels/i18n
