### ISSUE TITLE
Add Badges to People's Shujaaz Awards Finalists

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1585]
As per email discussions add, for instance a badge and a line of text under the subtitle of the page on each of the person pages of the finalists

http://info.mzalendo.com/shujaaz#nominees

**Comment by zarino** [comment]
Is this too cartoony? /cc @wrightmartin

![peoples-shujaaz-award-badge](https://cloud.githubusercontent.com/assets/739624/5721961/9832bee8-9b2f-11e4-8a68-68b0cc15f8c8.jpg)

**Comment by paullenz** [comment]
Shall I ask Jess for her thoughts?

**Comment by zarino** [comment]
@paullenz – yes!

**Comment by zarino** [comment]
How about this @paullenz @JessMusila? The supplied badge image (with the text over the middle) was far too detailed to be reduced to a suitable size, so I've drawn a simplified version that works better at tiny sizes.

![peoples-shujaaz-award-badge](https://cloud.githubusercontent.com/assets/739624/5724034/99eb5e6e-9b40-11e4-811e-79d84ee1b047.jpg)

**Comment by JessMusila** [comment]
Perfect! @zarino @paullenz

**Comment by zarino** [comment]
@JessMusila Excellent! :tada:

**Comment by wrightmartin** [comment]
@zarino excellent work!

**Comment by paullenz** [comment]
\o/

**Comment by zarino** [comment]
@mhl @chrismytton The HTML markup and CSS for this are done, in [branch 1585-shujaaz-finalist-badges](https://github.com/mysociety/pombola/tree/1585-shujaaz-finalist-badges) – over to you to actually make it appear with the right content on the right pages.

**Comment by chrismytton** [comment]
@zarino Awesome, thanks. Am on the case now.
