### ISSUE TITLE
ZA: Updates to person profile pages (inactive people, date of death, contact details)

### ISSUE THREAD

**Issue by geoffkilpin** [mysociety/pombola#1602]
Profile pages need updating:

- [ ] For people with one or less positions (one being just a party membership), former positions should be listed on the default tab. This would avoid otherwise blank profiles like [this](http://www.pa.org.za/person/suzanne-marylan-van-aardt/) and provide information for people who are no longer MPs ([e.g.](http://www.pa.org.za/person/max-vuyisile-sisulu/)) or who have passed away ([e.g.](http://www.pa.org.za/person/mario-gaspare-oriani-ambrosini/)).

 This should possibly be limited to certain positions (legislature, executive, election lists, etc.) - as some MPs have a large number of former positions ([e.g.](http://www.pa.org.za/person/mario-gaspare-oriani-ambrosini/)). 

- [ ] If a person has passed away and their membership of their party has therefore ended, their affiliation should still be displayed in their profile in the sidebar ([e.g.](http://www.pa.org.za/person/mario-gaspare-oriani-ambrosini/)).

- [ ] Dates of death should be displayed.

- [x] Addresses (physical, postal) should be displayed on profiles if entered.

**Comment by paullenz** [comment]
breaking out Addresses as a separate ticket item - https://github.com/mysociety/pombola/issues/1604
