### ISSUE TITLE
Please collate all disqus comments on Parliamentarians profiles in one place

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1617]
@mhl @paullenz @duncanparkes Presently, there are separate disqus discussions for each of the sub-pages about a person. Please collate all disqus comments on Parliamentarians profiles in one place regardless of what they are associated with. e.g. Mike Sonko's profile has these threads going - http://info.mzalendo.com/person/gideon-mbuvi/contact_details/#comment-1847571413
and http://info.mzalendo.com/person/gideon-mbuvi/

**Comment by paullenz** [comment]
Am I right in thinking that the difficulty here is not so much in unifying comments function on a person page irrespective of tag, but merging in the existing comments to a single place?

**Comment by lizconlan** [comment]
Having read more of the Disqus documentation for #1676 there appear to be options for combining comment threads, although with heavy disclaimers that there's no way to reverse this out afterwords. Also not entirely simple instructions.

* https://help.disqus.com/customer/portal/articles/286778-migration-tools
* http://blog.disqus.com/post/870654196/migrate-your-threads-by-uploading-a-url-map
* http://stackoverflow.com/questions/15642867/merging-aggregating-disqus

**Comment by mhl** [comment]
This is fixed now - see the (duplicate) ticket: #2468
