### ISSUE TITLE
Make Zimbabwe politicians data available via API

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1622]
Regina is happy for the data they've collected to be made available for use via API on PopIt using the    CC-BY-SA 3.0 (human readable summary here: https://creativecommons.org/licenses/by-sa/3.0/ ) license. 

They are doing some data updating and this should be completed by end of April or so, so this ticket isn't urgent!

**Comment by dracos** [comment]
Is there any reason it can't be the current version (4.0)? http://creativecommons.org/version4 has the improvements, removing some doubts around database rights etc.

**Comment by JenMysoc** [comment]
Nope, they're happy to be lead by us that's just the one Mark had suggested when I asked them just after christmas.

**Comment by mhl** [comment]
Yes, the current version would be better, I don't think there was any reason for me to say 3.0 in particular.

**Comment by tmtmtmtm** [comment]
Closing in favour of https://github.com/mysociety/pombola/issues/1835
