### ISSUE TITLE
Register of interests doesn't show year

### ISSUE THREAD

**Issue by adieyal** [mysociety/pombola#1624]
e.g. http://www.pa.org.za/person/bathabile-olive-dlamini/

it is difficult to distinguish between declarations from different years

**Comment by tmtmtmtm** [comment]
Years are currently displayed:

![screen shot 2015-11-19 at 12 08 03](https://cloud.githubusercontent.com/assets/57483/11270425/d675c26a-8eb6-11e5-8742-01beac58e57e.png)

Looks like this was added in https://github.com/mysociety/pombola/commit/dfe41d5e113d918b99ca5843b6bc7d3298b7932a
