### ISSUE TITLE
Create a site for Parliaments offering similar to FixMyStreet.org or Alaveteli.org

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1631]
If we're continuing to offer Pombola as a product for people to use we should consider creating a site similar to the Alaveteli.org or FixMyStreet.org sites which could give people the basic info on the site and where to start. It would help for incoming enquiries and also to make the platform look as professional and finished as both Alaveteli and FixMyStreet.

This could be less technical than the FMS and Alaveteli pages as the platform needs a lot of customisation which I assumed we would be involved in. It would also be great if on there we could include something on using Pombola with the Poplus components.

Discuss!

**Comment by paullenz** [comment]
As we are much more likely to be looking at building off Every Politician now, I am closing this ticket

**Comment by JenMysoc** [comment]
Actually regardless of where we're building the site from I think we still need a page to tell people about this.

**Comment by JenMysoc** [comment]
Now we have our theyworkforyou site and our grand plan we should totally get on making this page!

**Comment by paullenz** [comment]
I don't think that the ticket for it should be on this repo though - it
should be (?) on the .org one

**Comment by JenMysoc** [comment]
When we create the site we should move the info from the two remaining wiki pages over there.

**Comment by chrismytton** [comment]
We're no longer actively encouraging people to reuse pombola, so I think for now https://www.mysociety.org/democracy/ and https://www.mysociety.org/democracy/pombola/ are Good Enough.
