### ISSUE TITLE
Urgent Hansard update

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1634]
Dear @paullenz and @mhl,

I noticed Mzalendo's hansard is not automatically syncing with the Parliament site. 
Do you need to update the code? During the Christmas break, the Kenyan Parliament revamped its website.

Please advise.

Regards,

Jessica

**Comment by mhl** [comment]
@JessMusila Yes, we're working on that problem this sprint - @lizconlan is going to be moving on to looking at this Hansard issue and the missing search results shortly.
