### ISSUE TITLE
searching for someone's name without its accents should still find the person

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1649]
The example that PMG pointed out is that [searching for "desiree"](http://www.pa.org.za/search/?q=desiree&section=persons&order=relevance) doesn't bring up [Ms Désirée Van Der Walt](http://www.pa.org.za/person/d-van-der-walt/) when ideally her person page should be found when searching for either "desiree" or "désirée" - only [the latter](http://www.pa.org.za/search/?q=d%C3%A9sir%C3%A9e&section=persons&order=relevance) works at the moment.

It looks as if a plausible solution is to add the [`asciifolding` analyzer](http://www.elastic.co/guide/en/elasticsearch/reference/0.90/analysis-asciifolding-tokenfilter.html) to Pombola ZA's Elasticsearch index. (Those docs are for version 0.90, which we're using - later versions [mention a `preserve_original` option](http://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html) which sounds as if it might be needed for to get searches on the accented version to still work (?))

**Comment by mhl** [comment]
@tmtmtmtm suggested an alternative approach to this - we could generate (or take from everypolitician) a mapping from common misspellings of name parts to the version of the name that will be found, seeded to start with, at least, with the unaccented version of all names that contain accents.

**Comment by tmtmtmtm** [comment]
@JenMysoc can you get or generate a list of a few other people that this needs to be solved for? Would be good to know if this potentially only for one or two people, or quite a few, and if so what sorts of characters are involved.

**Comment by dracos** [comment]
Would you have every possible combination of accent/unaccented to cover if they get only some of the accents right? :) You might know one of the ones in Máirtín Ó Muilleoir and not the others. Folding of some sort would seem sensible, we have it on TheyWorkForYou (mostly for MLAs).

**Comment by JenMysoc** [comment]
Some other examples from PMG:

Mr Manuel Simão Franca De Freitas
Mr Hendrik Christiaan Crafford Krüger
Ms Désirée Van Der Walt

**Comment by duncanparkes** [comment]
ElasticSearch is currently in a poor way on the server running the ZA staging site, so this can't yet be deployed and tested.

**Comment by duncanparkes** [comment]
Fixed in 6daf181
![2016-02-25-225127_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/13337299/7fe78dc6-dc12-11e5-8e56-3f520c6afb89.png)
