### ISSUE TITLE
Mzalendo: add all 2014/2015 CDF allocations to the MPs profiles

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1654]
PDF sent by jessica has details 

Please contact Jen or Paul for the PDF :)

**Comment by paullenz** [comment]
[Constituencies Development Fund - Constituencies Allocations Financial Year 2014_2015.pdf](https://github.com/mysociety/pombola/files/39045/Constituencies.Development.Fund.-.Constituencies.Allocations.Financial.Year.2014_2015.pdf)

**Comment by paullenz** [comment]
Note from Jessica (more generally about CDF):

Adding CDF information to Mzalendo constituency profiles is not urgent. The continued existence of CDF in Kenya as it is currently constituted is debatable. Earlier this year a court ruled it unconstitutional. A bill has recently been tabled in the National Assembly to align it with the Constitution.

**Comment by tmtmtmtm** [comment]
In that case I'm closing this. If this changes, we can re-open.
