### ISSUE TITLE
ZA: small pa changes that come out of Cape Town visit

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1655]
This is a placeholder ticket for items that come out of Paul and Dave's time in ZA

**Comment by paullenz** [comment]
Placeholder to have a couple of hours put aside for any urgent small tweaks that come from out time with PMG

**Comment by tmtmtmtm** [comment]
can I assume that anything that came out of this has been (or will be) ticketed elsewhere, and that this ticket can be closed?

**Comment by paullenz** [comment]
yup
