### ISSUE TITLE
Please merge the following profiles

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1658]
@mhl @paullenz 

1. Mohamed Maalim Mahamud 

http://info.mzalendo.com/person/mohamed-maalim-mahamud/ and http://info.mzalendo.com/person/maalim-mohamed/

2. Athanas Wafula Wamunyinyi

http://info.mzalendo.com/person/athanas-wamunyinyi/experience/ and
    http://info.mzalendo.com/person/athanas-m-wafula-wamunyinyi/

3. Joseph Kiuna Karimbeu Nganga
http://info.mzalendo.com/person/joseph-kiuna-kariambeu-nganga/
   http://info.mzalendo.com/person/joseph-kiuna/

**Comment by duncanparkes** [comment]
All merged.
