### ISSUE TITLE
reinstate social registration applications in Odekro

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1664]
I removed references to the `registration`, `registration_defaults` and `social_auth` apps when rebasing the Odekro code into the `odekro-rebased-onto-master` branch. These should be put back into `INSTALLED_APPS` in `pombola/settings/ghana_base.py`, and we should verify that social registration still works.

**Comment by duncanparkes** [comment]
I can't see what the registration is actually being used for, so I'm going to leave this for now.

**Comment by mhl** [comment]
Ian has confirmed that it's not being used for anything so he's OK with it being left out. I'll close this as a result.
