### ISSUE TITLE
add the "tag cloud" back to the rebased odekro branch

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1665]
Odekro has a "word cloud" feature, rendered with jQCloud, as seen on the front page:

![odekro-wordcloud](https://cloud.githubusercontent.com/assets/7907/8053840/15a136be-0e8c-11e5-98b4-f2b240f602e3.png)

On the live site that's getting the data from http://www.odekro.org/static/js/tagcloud.json although in the latest pushed code in the Odekro repository, it's loading from `/search/tagcloud/` as you can see here: https://github.com/Hutspace/odekro/blob/odekro/mzalendo/odekro/templates/home.html#L15

On the live site, http://www.odekro.org/search/tagcloud/ is returning an error, though, as is http://www.odekro.org/search/tagcloud/2/ so I guess that's why the front page is loading static data.

The implementation of the word cloud code can be found in:

* https://github.com/Hutspace/odekro/blob/odekro/mzalendo/search/urls.py
* https://github.com/Hutspace/odekro/blob/odekro/mzalendo/search/views.py
* https://github.com/Hutspace/odekro/blob/odekro/mzalendo/odekro/management/tagcloud.py
* https://github.com/Hutspace/odekro/blob/odekro/mzalendo/odekro/management/commands/generate_tagcloud.py

This ticket represents the work to investigate (and ideally reimplement) this functionality on the branch [odekro-rebased-onto-master](https://github.com/mysociety/pombola/commits/odekro-rebased-onto-master) cleanly, so that this functionality could optionally be used in any country supported by Pombola.

**Comment by tmtmtmtm** [comment]
Done in https://github.com/mysociety/pombola/pull/1692
