### ISSUE TITLE
Gender data extract for Mzalendo

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1668]
As per proposal from Jessica

**Comment by paullenz** [comment]
The data required is the same speaking data that is used to create the report card - i.e. number of speeches by person, for 2013, 2014 and 2015 to May, but including the gender of each person in a separate column so that it can be readily analysed

**Comment by duncanparkes** [comment]
Is this just a data gathering exercise with no actual UI?

**Comment by paullenz** [comment]
yup - we just want a CSV output for Jess

**Comment by paullenz** [comment]
Nb this is just the CSV creation - not the creation of a page

**Comment by mhl** [comment]
The kenya_hansard_speech_statistics command may be a helpful basis or starting point for this.

**Comment by duncanparkes** [comment]
I've sent some files to @paullenz, to see if they're what's wanted. I'm going to drop this into review for now - there are no code changes.
