### ISSUE TITLE
ShineYourEye - people not showing as party members

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1669]
On page e.g. http://www.shineyoureye.org/person/theodore-ahamefule-orji/experience/ even though they are listed as an ongoing party member, on the LHS is says "not a member of any party"

**Comment by dracos** [comment]
The LHS looks for orbs with kind slug "party", but the party in the main section has kind slug "political-party".

**Comment by duncanparkes** [comment]
@dracos is correct. An organisation is considered to be a party for these purposes if it has the organisation kind with slug 'party'. Changing the slug of the OrganisationKind on shineyoureye looks to me as though it would change a single URL: `/organisation/is/political-party/` would become `/organisation/is/party/`. As far as I can see there is no reference to this URL from anywhere else in the codebase except for `/parties/` which is actually expecting the slug to be `party` and so is currently broken.

Let's change the slug of the 'Political Party' OrganisationKind to 'party' to match the expectations of the code.

**Comment by mhl** [comment]
I'm happy with that so long as you add a redirect for `/organisation/is/political-party/` - you can try it out on nigeria.pombola.staging.mysociety.org
