### ISSUE TITLE
Remove comments from all bar constituency office pages on pa.org.za

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1677]
See:

Happy to remove the Discus comment page from everywhere except on constituency office pages - look into replacing with Facebook comments as per #1676

**Comment by mhl** [comment]
@paullenz I think there's something missing here after the "See:"

**Comment by mhl** [comment]
@paullenz: Could you clarify if this is still relevant?

**Comment by paullenz** [comment]
This can be closed
