### ISSUE TITLE
csv files for adwords

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/pombola#1683]
Could someone provide me with some csv files for pa.org.za Adwords set-up, please?

Here's what I'd like, ideally:

a) Names of all representatives (common names if available, as I know some can be very long), paired with the URL of that rep's page. If it's not too difficult, it'd also be handy to have their positions, parties and which parliament they are in, but that's not as important)
b) Names of provinces, paired with the province page URLs
c) Names of parties, paired with the party page URLs

And maybe, again only if it's not too tricky:
d) The names of constituency offices, but in the forms people are likely to search for them, which presumably means taking the given name like "ANC Constituency Office (927): Odendaalsrus " and changing it to something like "Odendaalsrus Constituency Office". 

(@paullenz @JenMysoc I'm thinking about the talk you gave at the meet-up and specifically the part where some users said they weren't really interested in the concept of constituency offices. Is it worth running these proposed keyword groups past PA before I go ahead and set up the ads?)

**Comment by mhl** [comment]
This could be based on:

* https://github.com/mysociety/pombola/blob/master/pombola/kenya/management/commands/kenya_adwords_csv.py

... in that a more generic basis for both country-specific commands could be in `pombola.core`. (Basically it's only the position and place names that are considered that would need to be country-specific.)

**Comment by MyfanwyNixon** [comment]
Thanks Liz, 

Deep-linked adwords for reps, constituency offices, party names and provinces are now in place (ping @JenMysoc @paullenz )
