### ISSUE TITLE
Highlight search terms in pages

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#169]
From Ory:

"In the search results if you click through to the hansard entry, it might be an idea to highlight the search item. So for example highlight 'somali pirates' in the click through"

Could apply to all pages - we could detect in the referrer if the last page was a search and then highlight.

A quick search reveals that there is pre-canned javascript out there to achieve this.

**Comment by paullenz** [comment]
No obvious user need, open for three years, closing
