### ISSUE TITLE
No search result for Sophia Abdi Noor

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1701]
Searching for "Sophia Abdi Noor" in people finds no results. I eventually found her by guessing the slug: http://info.mzalendo.com/person/sophia-noor/.

![2015-07-14-105655_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/8670721/26e5c1d2-2a17-11e5-8e0e-4b212e5b671b.png)

**Comment by mhl** [comment]
Weird, this works for me both with generic search http://info.mzalendo.com/search/?q=Sophia+Abdi+Noor&section=global&order=relevance

![global-search](https://cloud.githubusercontent.com/assets/7907/8702353/3c7dcc80-2b0f-11e5-9d72-9c9ef75e9b5f.png)

And advanced search restricted to persons: http://info.mzalendo.com/search/?q=Sophia+Abdi+Noor&section=persons&order=relevance

![person-search](https://cloud.githubusercontent.com/assets/7907/8702357/407af8e4-2b0f-11e5-9fa7-1af52f1c86ec.png)

**Comment by duncanparkes** [comment]
I see her now too, perhaps someone was rebuilding the index or something.
