### ISSUE TITLE
Duplicate Hansard entries on MP profiles

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1705]
@mhl @paullenz 

Kindly Check on Moses Kuria's profile, his Hansard  entries are repetitive. The same thing is also happening in other MPs profile for instance Ken Okoth's. Attached is Kuria's profile.

![moses](https://cloud.githubusercontent.com/assets/909927/8725752/aa02f422-2bde-11e5-8e7f-2e7e72524bee.PNG)

**Comment by tmtmtmtm** [comment]
Still an issue (at http://info.mzalendo.com/hansard/person/moses-kuria/appearances/)

**Comment by tmtmtmtm** [comment]
For Ken Okoth recent appearances are fine, but there are duplicates from 17th June (currently at  http://info.mzalendo.com/hansard/person/kenneth-odhiambo-okoth/appearances/?page=4)

**Comment by tmtmtmtm** [comment]
This is because of duplicate Hansard records — @paullenz can clean these out.

**Comment by paullenz** [comment]
Fixed - but I stupidly deleted some additional records due to date confusion - see:  https://github.com/mysociety/pombola/issues/1839
