### ISSUE TITLE
Delete the CDF allocation on Sophia Noor's profile

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1706]
@mhl @paullenz Kindly delete the CDF allocation on Sophia Noor's profile, it should only appear on the profile of the current MP for Ijara- Ibrahim Ahmed Abass.

http://info.mzalendo.com/person/sophia-noor/

**Comment by duncanparkes** [comment]
The problem here was that Sophia Noor's party membership was associated with a constituency. I've taken that off the membership, and now the CDF data doesn't appear.
