### ISSUE TITLE
possibly add tracking of youtube start / pause events to the MIT experiment page

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1708]
MIT were asking about this - at the moment from the experiment data you can't tell if someone played the video or not. We could add a new endpoint like the time-on-page one which saves this information, which we could get from https://developers.google.com/youtube/iframe_api_reference#Events

It's not clear whether they would like us to go ahead and implement this yet though.

**Comment by paullenz** [comment]
Closing as no immediate need, will re-open if a future request comes in
