### ISSUE TITLE
PU Search not returning results inline

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1714]
We've had a message from the team at SYE saying "The PU search function appears to be in place but not effective. Search is allowed, but return isn't in line"

**Comment by JenMysoc** [comment]
More details: 

PU SEARCH
1. What was entered:
PU NUMBERS from Lagos - 24-20-12-009, 24-11-03-015, 24-12-01-036, 24-03-11-019, 24-13-06-101, 24-20-04-041 and 24-08-03-021

2. Where it was entered:
The search box in the homepage’s top right corner

3. What did you expect to happen?:
A result showing -
the Federal Constituency
the Federal Representative,
the Senatorial District
the Senator and
the Governor of the voter in Lagos state

4. What actually happened?
Showed results from Kwara State – Federal Constituency and Senatorial District

**Comment by lizconlan** [comment]
So we're currently returning the Federal Constituency and the Senatorial District (although possible with unhelpful headings) so we need to also show the representatives associated with both of those and add the state Governor. (um ask me to reword that if it isn't clear)
