### ISSUE TITLE
remove misattributed committee appearances for Mr Madoda Sambatha and Ms Beryl Belinda Miller

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1718]
As requested by Zaheedah.

Previously we did this by removing the speeches with something like:

```python
  from speeches.models import Speaker, Speech
  speaker = Speaker.objects.get(person__popit_id='core_person:INSERT-ID-HERE')
  Speech.objects.filter(speaker=speaker).count()
  # Check that that's the right number...
  Speech.objects.filter(speaker=speaker).delete()
```

... and adding the PopIt ID for that person to: https://github.com/mysociety/za-hansard/blob/15bf44631e50d3c805d3342677731ff98dbbca11/za_hansard/management/commands/za_hansard_pmg_api_scraper.py#L618

**Comment by duncanparkes** [comment]
So my understanding is that it's OK to remove these speeches because committee speeches are only used for search - we don't display the whole committee proceedings anywhere ourselves, so no thread is being lost here or anything.

**Comment by duncanparkes** [comment]
Speeches now deleted:

```
from pombola.core.models import Person as CorePerson
from speeches.models import Speaker, Speech

CorePerson.objects.get(slug='beryl-belinda-miller').__dict__
bm = Speaker.objects.get(person__popit_id='core_person:3739')
Speech.objects.filter(speaker=bm).count()
Speech.objects.filter(speaker=bm)
[x.text for x in Speech.objects.filter(speaker=bm)]
Speech.objects.filter(speaker=bm).delete()
CorePerson.objects.get(slug='madoda-sambatha').__dict__
ms = Speaker.objects.get(person__popit_id='core_person:4555')
[x.text for x in Speech.objects.filter(speaker=ms)]
Speech.objects.filter(speaker=ms).delete()
```

**Comment by duncanparkes** [comment]
I've now deployed the fix to stop these speeches getting misattributed again. In the meantime, they had reappeared, so I've deleted them again. Tomorrow morning, we should have a quick look to make sure that they haven't come back.

**Comment by duncanparkes** [comment]
No speeches attached to either speaker this morning, so I'm closing this.
