### ISSUE TITLE
preliminary WriteInPublic for Pombola sites work

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1720]
> As a member of the public in Kenya
I want to be able to write to my MP
So that I can let them know what I think, ask them questions and influence them

There are a couple of possible initial approaches to this:

* Add to the nightly Pombola exports to Popolo from crontab a new export that only exports the representatives that you'd want to write to (since there's no filtering of Popolo data in WriteInPublic)
* Add an option to WriteInPublic to import CSV files from EveryPolitician

**Comment by tmtmtmtm** [comment]
The first option is probably simpler, but would largely be a waste as the second option will be needed more generally anyway.

**Comment by tmtmtmtm** [comment]
WriteInPublic [now](https://github.com/ciudadanointeligente/write-it/pull/1102) works with EveryPolitician.
