### ISSUE TITLE
Complete Facebook comments integration on pa.org.za

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1731]
Add to constituency office pages
Have archived comments visible on the same page (read only)

**Comment by lizconlan** [comment]
currently looks like this... (hard to demo publicly as the comments only get pulled in if they're from the expected domain name)

![screen shot 2015-09-02 at 11 12 47](https://cloud.githubusercontent.com/assets/27760/9628607/3977e68a-5164-11e5-981e-f4fdaadd298f.png)

**Comment by duncanparkes** [comment]
This is now merged and live. Remaining steps:

 - Close the disqus threads
 - One more fetch of the Disqus data, commit it, and deploy
 - Give the FaceBook app to PA.

**Comment by duncanparkes** [comment]
I've set all Disqus comments threads to automatically close after one day, which means all existing threads should now be closed.

**Comment by tmtmtmtm** [comment]
The primary work here is complete, and #1863 is for the final cleanup, so this can be closed.
