### ISSUE TITLE
Page for Mzalendo highlighting the value of female MPs

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1734]
Needed before September 4th.

Will contain links to Women MP profile pages as a showcase and #1733

**Comment by JenMysoc** [comment]
We're waiting for details from Jessica on the following info:

- How are you expecting the Women MPs page to look - will it be like an alternate homepage for Mzalendo?
- How are you expecting the display of the MP profiles to look - are you expecting a short summary text under a photo with a click through to a separate page with a full profile?
- Is the word cloud covering all female MPs or is it a word cloud PER female MP?
- How important is the static information? Should it take up half of the page? Or less?
- Where do you want to display the vital statistics and how - is it just numbers on the main page or did you envisage a graph or infographic?

If @Gemmamysoc could follow up first thing Tuesday morning that would be excellent!

**Comment by mhl** [comment]
I've put a line in the design backlog about getting design time for this, including the deadline - I suspect it may well need some developer support as well.

**Comment by Gemmamysoc** [comment]
Info from Jessica:

1. - How are you expecting the Women MPs page to look - will it be like an alternate homepage for Mzalendo?
The page will be an additional page on our website - Showcasing women Parliamentarians work only. We intend to run it until the 2017 elections. On the homepage, we would like a prominent link driving attention to the page. Women are marginalised in Kenyan politics and the page is Mzalendo's contribution to influence mindsets. 

2. How are you expecting the display of the MP profiles to look - are you expecting a short summary text under a photo with a click through to a separate page with a full profile? Yes. The list will have 8-10 profiles of women MPs. 8 will be selected based on clustering of counties and 2 from the nominated MPs and Senators groups.

3. Is the word cloud covering all female MPs or is it a word cloud PER female MP? The word cloud should cover all female MPs. Not for each as the highlights of their work will covered in the short summaries on the selected women MPs profiles.

4.  How important is the static information? Should it take up half of the page? Or less? We would actually like the static information to be available on each woman Parliamentarians profile. Assuming the profiles will be centred, a thin column on the right and left side of the screen would suffice. The column on the left would list their responsibilities and the right side (the 3-5 key messages from our report).

Recent surveys on civic awareness reveal that most Kenyans still don't know the actual responsibilities of MPs (Members of the National Assembly and Senators). 

5. Where do you want to display the vital statistics and how - is it just numbers on the main page or did you envisage a graph or infographic?
The vital statistics would be at the bottom of the page. They would be numbers mainly e.g 86 Women Parliamentarians - 47 Women representatives, 16 elected members, 5 nominated members & 18 nominated Senators) 1 - Deputy Speaker (National Assembly); 8 committees chairpersons and 9 committee vice chairpersons. We will also list them by party.

**Comment by zarino** [comment]
Approved mockup:

![desktop-2](https://cloud.githubusercontent.com/assets/739624/9730080/e3bdf494-560b-11e5-8c01-19e62a6ae522.png)

Jessica’s emailed me the final text.

**Comment by mhl** [comment]
This is ready to deploy, just waiting for sign-off from Mzalendo.
