### ISSUE TITLE
ZA: make a list of useful person, speech and section pages for checking redesign work

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1735]
As requested by @zarino and @wrightmartin, we should produce a useful list of persons (and also speeches and sections of speeches) that should be checked when doing redesign work because they can have such a variety of combinations of data. Here are some initial suggestions for people I've been testing against:

* /person/graham-brian-douglas-mc-intosh/ (someone with former positions)
* /person/maria-tshabalala/ (someone who has no appearances or interests register entries)
* /person/moleeane-ben-skosana/ (someone who has died)
* /person/hlakudi-frans-nkoana/ (someone with both a date of birth and a date of death)
* /person/elizabeth-thabethe/ (someone with a date of birth, also a phone and fax number, associated province and biography)
* /person/mario-gaspare-oriani-ambrosini/ (someone who has died, but make sure that their party affiliation is still shown. Also should show two positions: "Deputy Minister of Small Business development: National Executive (Executive)" and "Member: National Assembly (Parliament)")
* /person/masefako-clarah-dikgale/ (should show her position as "Delegate: National Council of Provinces (Parliament)")

This is a work in progress - some of these cover multiple cases, and there are plenty that could be added. Some of the examples in https://github.com/mysociety/pombola/issues/1602 may be worth adding too.

Those links to `localhost:8000`:

* [/person/graham-brian-douglas-mc-intosh/](http://localhost:8000/person/graham-brian-douglas-mc-intosh/)
* [/person/maria-tshabalala/](http://localhost:8000/person/maria-tshabalala/)
* [/person/moleeane-ben-skosana/](http://localhost:8000/person/moleeane-ben-skosana/)
* [/person/hlakudi-frans-nkoana/](http://localhost:8000/person/hlakudi-frans-nkoana/)
* [/person/elizabeth-thabethe/](http://localhost:8000/person/elizabeth-thabethe/)
* [/person/mario-gaspare-oriani-ambrosini/](http://localhost:8000/person/mario-gaspare-oriani-ambrosini/)
* [/person/masefako-clarah-dikgale/](http://localhost:8000/person/masefako-clarah-dikgale/)

**Comment by tmtmtmtm** [comment]
This seems like it should move to the wiki, rather than being a ticket here…

**Comment by mhl** [comment]
Good idea.

**Comment by JenMysoc** [comment]
This is done here: https://wiki.mysociety.org/wiki/People%27s_Assembly_useful_list_of_persons

**Comment by mhl** [comment]
Thanks, @JenMysoc
