### ISSUE TITLE
[ZA] Investigate why Andrew Ntwampe Morwamoche's profile is showing appearances from Mr Morwamoche of a different party from many years ago

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1740]
From PA:

Mr Andrew Ntwampe Morwamoche is a member of the PAC (candidate for the 2014 election). The appearances on his profile reflect that of a Mr Morwamoche from the ANC who seemed to have been a MP years ago. Is there a way to delete the appearances from this profile. See link below. 

http://www.pa.org.za/person/morwamoche-andrew-ntwampe/

**Comment by mhl** [comment]
This is a name resolution error; generally we delete the erroneously assigned speeches and add an exception to the code to stop them be reassigned, as in this issue:

* https://github.com/mysociety/pombola/issues/1718

In this case, Mr Andrew Ntwampe Morwamoche from PAC doesn't appear to hold a position that would allow him to speak in parliament, so the same could be done in this case by a developer.

(We're resisting getting caught up in fixing the underlying issues in the name resolution until something like https://github.com/mysociety/pombola/issues/1748 is done.)

**Comment by duncanparkes** [comment]
Misattributed speeches removed with

```
from pombola.core.models import Person as CorePerson
from speeches.models import Speaker, Speech
CorePerson.objects.get(slug='morwamoche-andrew-ntwampe').__dict__
Speaker.objects.get(person__popit_id='core_person:8277')
person = Speaker.objects.get(person__popit_id='core_person:8277')
Speech.objects.filter(speaker=person).count()
[x.text for x in Speech.objects.filter(speaker=person)]
Speech.objects.filter(speaker=person).delete()
```

in the manage.py shell.

**Comment by duncanparkes** [comment]
It looks like Morwamoche Andtrew Ntwampe is still getting things attributed to him despite us blacklisting his popit ID https://github.com/mysociety/za-hansard/commit/14c0f1345075f94c3f732b25f3029eb15ba906c4

**Comment by mhl** [comment]
The committee appearance is on date `datetime.date(1999, 9, 21)` committee ID 87 and meeting ID 3195, so we investigated this by putting in a breakpoint in the `if options['import_to_sayit']` block and single-stepping. `self.get_person` in `za_hansard/importers/import_json.py` is called with `display_name` `Morwamoche` and `party` `ANC`.  That returns a speaker with `speaker.person.popit_id` of `core_person:8277` even though that is in the `popit_id_blacklist`.

What's happening is that this the blacklist is only used to reject results from `self.resolver.get_person` - if a speaker's not found there, it still goes on to try to find a unique speaker with that name from the `Speaker` model at this line: https://github.com/mysociety/za-hansard/blob/32664ad25f6b38da7a898ce9b0bde4cd552b95af/za_hansard/importers/import_base.py#L49 - I don't see why that second attempt to find a speaker needs to be there, so it could be removed. A more conservative change which would also fix this issue would be to also check any speaker found there for `speaker.person.id` being in `popit_id_blacklist`.

**Comment by duncanparkes** [comment]
I've deployed the site with the new za-hansard, and reparsed the meeting as @mhl suggested.
