### ISSUE TITLE
update documentation to explain how to add the featured image

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1747]
We should let PMG know about how to make sure a thumbnail appears on the new front page for infographics, and also update the manual for People's Assembly admins that @paullenz wrote.

At the moment, if they do an infographic post, they'll upload the image with the File Archive app in the Django admin, and paste the URL of that image file into a Markdown image tag. Now they'll need to additionally select that file from the "featured image file" drop-down on the info page editing page in the admin interface.

n.b. this user experience is cumbersome; we should attempt to streamline it, although ultimately this may be one of the things that's best done with the "replace much of Pombola with Wagtail / Django CMS" work.

**Comment by mhl** [comment]
> Just a quick note, since I see from Twitter that you just
> published a new infographic:
> 
> There's now a couple of new exta steps you have to take when
> publishing an infographic to make sure that a thumbnail image of
> it appears on the new front page:
> 
>  At the bottom of the edit info page,
>  e.g. http://www.pa.org.za/admin/info/infopage/555/
> 
>   1. Make sure it has the 'infographic' tag
> 
>   2. Select the image file that you've just uploaded from the
>      "Featured image file" drop-down. (It's a long list, but if
>      you type the first couple of letters of the filename, it
>      should find the right one.)
> 
> I'm afraid none of this is a very good user experience for
> publishing new posts, especially since it comes on top of the
> separate upload file and copy-and-paste-its-URL steps :( Rest
> assured that we're thinking about the best way to make this
> process much simpler for you.

**Comment by paullenz** [comment]
Closing this, as PMG know how to make a change - there should perhaps be a general ticket which is - update all of the user documentation for Pombola, however as existing users seem relatively comfortable I believe this significant job is not an immediate priority

**Comment by tmtmtmtm** [comment]
https://github.com/mysociety/pombola/issues/1309 is probably the general ticket for this?

**Comment by paullenz** [comment]
ah yes - it is!
