### ISSUE TITLE
Most recent MP Corner post not appearing on ZA homepage

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1752]
The [most recent "MP Corner" blog post](http://www.pa.org.za/blog/mr-geordin-hill-lewis-da) isn't appearing on the pa.org.za homepage.

![screen shot 2015-09-01 at 15 32 41](https://cloud.githubusercontent.com/assets/22996/9607028/b41f60b2-50be-11e5-8d4a-5dc5e3ed93dd.png)

It looks to me like this is caused by [this line](https://github.com/mysociety/pombola/blob/14244e105f43ed22dedc1763b0e6bf105e7855fe/pombola/south_africa/views.py#L73), which I think should be retrieving the first element instead of the second?

```diff
-            context['mp_corner'] = articles.filter(categories=c)[1]
+            context['mp_corner'] = articles.filter(categories=c)[0]

**Comment by mhl** [comment]
It looks like that line was introduced in 993b953ec261, which changed `[:1]` to `[1]`
