### ISSUE TITLE
ZA: Missing appearances in committee scraping

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1755]
In an email from Megan from 2nd September:

> Mr Mohapi Jihad Mohapi is the Chairperson of the Select Committee on Cooperative Governance and Traditional Affairs and also a Member of the Select Committees on Security and Justice and Petitions and Executive Undertakings.
> 
> His appearances are not updating and I would appreciate if you could assist. See list of missing dates and the link of the minutes underneath: 
> 
> SELECT COMMITTEE ON COOPERATIVE GOVERNANCE AND TRADITIONAL AFFAIRS
> 28 July 2015 
> 
> https://pmg.org.za/committee-meeting/21195/ 
> 
> 9 June 2015 
> 
> https://pmg.org.za/committee-meeting/21054/ 
> 
> 13 May 2015 
> 
> https://pmg.org.za/committee-meeting/20931/ 
> 
> 12 May 2015 
> 
> https://pmg.org.za/committee-meeting/20833/ 
> 
> 17 March 2015 
> 
> https://pmg.org.za/committee-meeting/20521/ 
> 
> 11 February 2015 
> 
> https://pmg.org.za/committee-meeting/19989/ 
> 
> 11 November 2014 
> 
> https://pmg.org.za/committee-meeting/17858/ 
> 
> 15 September 2014 
> 
> https://pmg.org.za/committee-meeting/17577/ 
> 
> 15 July 2014 
> 
> https://pmg.org.za/committee-meeting/17311/ 
> 
> SELECT COMMITTEE ON SECURITY AND JUSTICE 
> 
> 27 May 2015 
> 
> https://pmg.org.za/committee-meeting/20975/ 
> 
> 20 May 2015 
> 
> https://pmg.org.za/committee-meeting/20916/ 
> 
> 13 May 2015 
> 
> https://pmg.org.za/committee-meeting/20862/ 
> 
> 18 March 2015 
> 
> https://pmg.org.za/committee-meeting/20542/ 
> 
> 18 February 2015 
> 
> https://pmg.org.za/committee-meeting/20009/ 
> 
> 5 November 2014 
> 
> https://pmg.org.za/committee-meeting/17823/ 
> 
> 17 September 2014 
> 
> https://pmg.org.za/committee-meeting/17567/ 
> 
> 23 July 2014 
> 
> https://pmg.org.za/committee-meeting/17334/ 
> 
> 15 July 2014 
> 
> https://pmg.org.za/committee-meeting/17319/ 
> 
> 9 July 2014 
> 
> https://pmg.org.za/committee-meeting/17275/ 
> 
> 25 June 2014 
> 
> https://pmg.org.za/committee-meeting/17185/ 
> 
> SELECT COMMITTEE ON PETITIONS AND EXECUTIVE UNDERTAKINGS 
> 
> 27 May 2015 
> 
> https://pmg.org.za/committee-meeting/20956/ 
> 
> 26 May 2015 
> 
> https://pmg.org.za/committee-meeting/20934/ 
> 
> 20 May 2015 
> 
> https://pmg.org.za/committee-meeting/20903/ 
> 
> 18 February 2015 
> 
> https://pmg.org.za/committee-meeting/19998/ 
> 
> 25 November 2014 
> 
> https://pmg.org.za/committee-meeting/17933/ 
> 
> 5 November 2014 
> 
> https://pmg.org.za/committee-meeting/17825/ 
> 
> PLENARY
> 
> 24 June 2014 
> 
> https://pmg.org.za/hansard/18537/ 
> 
> HANSARD 
> 
> 17 February 2015 
> 
> https://pmg.org.za/hansard/21322/ 
> 
> 1 October 2014 
> 
> https://pmg.org.za/hansard/21182/ 
> 
> 16 September 2014 
> 
> https://pmg.org.za/hansard/21181/ 
> 
> 16 July 2014 
> 
> https://pmg.org.za/hansard/18577/

**Comment by tmtmtmtm** [comment]
Closing as work being done against duplicate: https://github.com/mysociety/pombola/issues/1811
