### ISSUE TITLE
ZA: Images for Facebook ads

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/pombola#1756]
We're tentatively experimenting with some Facebook ads. I'd like to explore images that we could use to make a more appealing ad around messages such as 'Do you know what your representatives are doing in your name'; 'find contact details for your representative' and 'making Parliament easy to follow/understand". 

Guidance for these ads is here:  https://www.facebook.com/business/products/ads/how-ads-show/ and https://www.facebook.com/ads/tools/text_overlay

On discussion with @zarino, we decided that the PA team are best situated to discern what kind of imagery and messaging is best for the audience. @paullenz or @JenMysoc , would you be able to lead that discussion? I believe that the design team can give access to eg a stock photography library from which suitable images could be identified.

**Comment by MyfanwyNixon** [comment]
Temporarily on hold - we've met targets and frozen the Facebook ads.

**Comment by davewhiteland** [comment]
PA team have emailed images to use :dancer:

**Comment by JenMysoc** [comment]
So is this going ahead still?

**Comment by paullenz** [comment]
Not a current requirement - and have been mailed as per the above comment
