### ISSUE TITLE
Replace "Goodluck Jonathan" as suggested search term

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1757]
The search box suggests I search for Goodluck Jonathan. Doing so returns zero results. Searching solely for Jonathan gives me several results (though none of them him), but then tells me that it found nothing:

![screen shot 2015-09-03 at 16 01 32](https://cloud.githubusercontent.com/assets/57483/9662010/5ca54854-5255-11e5-9e6b-ecb271b05a72.png)

**Comment by mhl** [comment]
The "Results 0-0" bit is covered by #1651, so I'm dropping the difficulty of this (just changing the placeholder text) to 1.

**Comment by JenMysoc** [comment]
Fixed in pull request #1925

**Comment by mhl** [comment]
:+1: Thanks, Jen - I've deployed that now
