### ISSUE TITLE
Merge Shakila Abdalla's profiles

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1768]
@paullenz @mhl @JenMysoc 

Shakila Abdalla has two profiles -please merge them.
1. http://info.mzalendo.com/person/shakila-abdalla/appearances/
2. http://info.mzalendo.com/person/shakila-abdalla-mohamed/

She's one of the Women Parliamentarians so it is likely be highly scrutinised later this week.

Regards,

Jessica

**Comment by duncanparkes** [comment]
Do this before putting #1734 live.

**Comment by mhl** [comment]
@JessMusila Just to double-check, those two profiles have different active party memberships at the moment - one is "Orange Democratic Movement Party Of Kenya" and the other is "Wiper democratic Movement Kenya". Perhaps one of those memberships should have an end date set?

**Comment by JessMusila** [comment]
@mhl She is currently a member of the Wiper Democratic Party. I have set an end date for her Orange Democratic Movement Party of Kenya membership.

**Comment by mhl** [comment]
@JessMusila Thanks - I've merged them now, it'd be great if you could check that http://info.mzalendo.com/admin/core/person/380/ doesn't have duplicate information now.
