### ISSUE TITLE
Mzalendo: improve performance of the homepage twitter timeline

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#1770]

**Comment by wrightmartin** [comment]
There is an option in the timeline creation wizard to prevent images from auto-expanding. I assume this means the browser only loads them on demand? 

![screen shot 2015-09-21 at 12 15 19](https://cloud.githubusercontent.com/assets/2292925/9990590/7454bdfa-605a-11e5-9ab9-71911820ba85.png)

I'm trying to work out what it changes in the embed code

**Comment by wrightmartin** [comment]
> 12:31 markl:	"Your widget has been saved, it may take a few minutes for your changes to appear."

Config change made by @mhl

**Comment by zarino** [comment]
@wrightmartin – ShineYourEye has an identical widget on its homepage – I wonder whether @mhl owns that too?

**Comment by mhl** [comment]
@zarino - Yeah, good call; I've updated ShineYourEye and Kuvakazim's Twitter widgets too

Obviously these shouldn't be owned by me personally, so I've created: https://github.com/mysociety/pombola/issues/1772
