### ISSUE TITLE
[NG] PU Search Results not accurate

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1780]
the SYE team have sent us an email about the PU search results:

For the number @lizconlan entered into the PU search to test it the team have said:

"The PU Number belongs to a registered voter in Plateau State, rather then Cross River State,

The fields in the results are alright

However, the results themselves aren't accurate."

And they've sent us an excel spreadsheet (please ask @jenmysoc) with the data and said the following:

Kindly find attached the structure for determining:

1. State --- Executive Governor

2. Federal Constituency --- Federal Representative

3. Senatorial Distict --- Senator

in respect to PU Numbers

Reminder:
PU SEARCH:

 This is a sample PU number -  18-13-05-002

The 1st part represents the state
    2nd = the local government
    3rd = the ward
    4th = the polling unit

 Each registered voter belongs to a polling unit
 Each polling unit is in a ward
 Each ward is in a local government area
 Each local government area is in a state constituency (In some cases, however, depending on the size, a local government area has been split to create 2 or 3 federal constituencies)
 Each local government area is in a federal constituency (In some cases, however, depending on the size, a local government area has been split to create 2 federal constituencies)
 Each local government area is in a senatorial district

**Comment by mhl** [comment]
One obvious issue is that the state number -> state mappings we have don't correspond to those we've most recently been sent by EIE: they sent us:

https://drive.google.com/open?id=0B1rfXEWouvZNSEh0UEFycG80WHlNNFRWdGRZQk5EQXMtdldr

... whereas the code currently uses:

https://github.com/mysociety/pombola/blob/b103d9344912e41bbbc04fa4319097e49d845179/pombola/nigeria/views.py#L34-L72

**Comment by mhl** [comment]
@JenMysoc @lizconlan could you possibly find from your email what the PU number was that's referred to here:

> For the number @lizconlan entered [...]

**Comment by mhl** [comment]
Here's the best example for testing we've got:

> PU SEARCH
> 1. What was entered:
> PU NUMBERS from Lagos - 24-20-12-009, 24-11-03-015, 24-12-01-036, 24-03-11-019, 24-13-06-101, 24-20-04-041 and 24-08-03-021
> 
> 2. Where it was entered:
> The search box in the homepage’s top right corner
> 
> 3. What did you expect to happen?:
> A result showing -
> the Federal Constituency
> the Federal Representative,
> the Senatorial District
> the Senator and
> the Governor of the voter in Lagos state
> 
> 4. What actually happened?
> Showed results from Kwara State – Federal Constituency and Senatorial District

**Comment by JenMysoc** [comment]
The PU number Liz used was 09/07/02/007

**Comment by mhl** [comment]
The LGA names in the spreadsheet we were sent by EiE didn't easily match the names in MapIt already (which came from the original import of Nigerian administrative boundaries from [GADM](http://gadm.org). I've manually matched all but two of these, though in this Google spreadsheet (mySociety only permissions):

https://docs.google.com/spreadsheets/d/1qj_qnppEXlO3Y_acoeXn3mpKtrSZVaJUwLteIFedII4/edit#gid=0
