### ISSUE TITLE
Use SVGs for graphics on Pombola sites

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#1782]
- Create SVGs from source graphics. 
- Optimise them using a tool eg http://petercollingridge.appspot.com/svg_optimiser
- Add a check for svg support, either through modernizr, or this snippet
```
<script>
  (function flagSVG() {
    var ns = {'svg': 'http://www.w3.org/2000/svg'};
    if(document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure", "1.1")) {
      document.getElementsByTagName('html')[0].className += ' svg';
    }
  })();
</script>
```
- Use a fallback technique eg

**HTML**
```
<svg> ... </svg>
<div class="fallback"></div>
```

**CSS**
```
.fallback { 
  display: none;
  /* Make sure it's the same size as the SVG takes up */
}
.no-svg .fallback { 
  background-image: url(logo.png); 
}
```

**Browser support for SVGs** http://caniuse.com/#search=svg

- [x] SA https://github.com/mysociety/pombola/pull/1784
- [x] Kenya #1788 
- [ ] Nigeria
- [ ] Ghana
- [ ] Libya
- [ ] Zimbabwe

**Comment by tmtmtmtm** [comment]
We don't control the Ghana site enough to do this, and the others either don't exist, or are being moved to Pombola-simple, so closing this.
