### ISSUE TITLE
[NG] Indexing the blog page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1786]
SYE would like to have a blog post index on the side of the blog page. A menu that organises post by month, to aid access to posts.

**Comment by tmtmtmtm** [comment]
@chrismytton you should be aware of this in terms of the migration (feel free to move the ticket to the new SYE repo…)

**Comment by chrismytton** [comment]
Moved to https://github.com/theyworkforyou/shineyoureye/issues/17
