### ISSUE TITLE
ZA: Navigation drop-downs fall behind MP photo

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#1800]
Possibly post-[jqueryUI](https://github.com/mysociety/pombola/issues/1745)?

![screen shot 2015-10-07 at 14 45 26](https://cloud.githubusercontent.com/assets/2292925/10339221/2ccbcd20-6d02-11e5-8eb2-df60730ba31a.png)

**Comment by gailefullard** [comment]
appears to be fixed

**Comment by tmtmtmtm** [comment]
http://www.pa.org.za/person/patricia-emily-adams/ works as expected for me on Chrome, Firefox, and Safari:
 
![screen shot 2016-01-17 at 16 18 44](https://cloud.githubusercontent.com/assets/57483/12378461/3a4117a6-bd36-11e5-8d1a-24396a860333.png)

@wrightmartin Can you still replicate the original problem, or can this be closed now?

**Comment by gailefullard** [comment]
Can be closed - also works on Internet Explorer
