### ISSUE TITLE
ZA: PMG's requested changes to the person page on PA

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1807]
After our call with PA last week we figured out some changes that would improve the person pages on People's Assembly; this ticket is for the work to implement these changes (largely design time).

@zarino's notes from the call are here: https://docs.google.com/document/d/14fSsB_ZpyXurzK72XdV2MqORylT7p6mahOjgYtlWLas/edit (only shared mySociety internal)

And a mockup from @wrightmartin of what they might look like: ![mockup of new people pages](http://i.imgur.com/9Lc9Cvl.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/pull/1808
