### ISSUE TITLE
Merge Yusuf Haji's profiles

### ISSUE THREAD

**Issue by JessMusila** [mysociety/pombola#1813]
Hi Mark @mhl 

I trust you are well. Please merge Senator Yusuf Haji's profiles. The links follow below:

1. http://info.mzalendo.com/person/mohamed-yusuf-haji/
2. http://info.mzalendo.com/person/yusuf-haji/

Regards,

Jessica

**Comment by mhl** [comment]
Hi @JessMusila - I've done this merge; if you could check the results here for any duplicate information that would be great: http://info.mzalendo.com/admin/core/person/26/ that would be great.
