### ISSUE TITLE
Blog post about the performance sprint

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#1814]
In #1764 we did a load of work towards making the Pombola sites speedier for people on slow connections.

We should write a blog post about the changes we made, and how (if at all) they affected whatever success metrics we collect for these sites (eg: user engagement, time on site, page depth?)

**Comment by tmtmtmtm** [comment]
@zarino is this something that's still likely to happen? Or does it fall under the "It would have been nice to, but it's quite unlikely now" category?

**Comment by zarino** [comment]
I think the momentum has probably passed. In fact, I was almost convinced we'd already written at least an internal blog post about it, but I can't find it. So maybe I'm just thinking of the measurements in the discussion thread on https://github.com/mysociety/pombola/issues/1764.

**Comment by tmtmtmtm** [comment]
Yeah — that's what I suggested. I'll close this then.
