### ISSUE TITLE
[ZA] Wrong Mr Mohapi updated on committee appearances

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1816]
Megan has pointed out that the wrong Mohapi has been updated:

It needs to move here: http://www.pa.org.za/person/mohapi-jihad-mohapi  Mohapi Jihad Mohapi (ANC)

It should NOT be here: http://www.pa.org.za/person/mojaki-victor-mohapi  Mojaki Victor Mohapi (APC) - he has not said anything in the committees yet.

**Comment by duncanparkes** [comment]
This is really explanation of what's going on in #1811.
