### ISSUE TITLE
consider adding an attendance data app as well

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1818]
@idesouza told me about the work they'd been doing on attendance data for MPs in Ghana - there's a blog post here:

http://blog.odekro.org/2015/09/16/what-has-your-mp-done-for-you-analysing-mps-effectiveness-between-january-2013-july-2014/

We've also been working on [adding attendance data to People's Assembly](https://github.com/mysociety/pombola/pull/1810) (using the Code4SA API and caching the results, rather than storing it in the database).

It would probably be worth adding an application and models for attendance data (analagous to the `bills` application), and make sure that it is at least generic enough to support the attendance data from Ghana and South Africa, since it's not as straightforward as one might think (e.g. Ghana has "present", "absent", "absent with permissions"; while the South Africa data records some other information about attendance.)

Once the attendance data is available via Django models it'd be easy to make it available via an API as well (see #1817)

**Comment by mhl** [comment]
Examples of the richer attendance data in People's Assembly, from https://github.com/mysociety/pombola/commit/7fc1ce2f8d174ddc3bf1d66aa4464baf92e12324#diff-25f9879f2d898727d97553e2d169f1ffR622

```
    #  A:   Absent
    #  AP:  Absent with Apologies
    #  DE:  Departed Early
    #  L:   Arrived Late
    #  LDE: Arrived Late and Departed Early
    #  P:   Present
```

**Comment by chrismytton** [comment]
Ghana app has now been removed from Pombola.
