### ISSUE TITLE
write a script to find if there are other erroneously associated CDF budget allocations

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1822]
This issue https://github.com/mysociety/pombola/issues/1706 arose because any political Position associated with a consitituency (i.e. that has its `place` member set to that constituency) causes the CDF budget to be associated with the person in that membership - it's not limited to MPs.

To investigate the scale of this problem, we decided in sprint retrospective to write a short script to find any other non-current MPs who have CDF budget information displayed for them.

**Comment by duncanparkes** [comment]
Running the following in `python manage.py shell` produces a list of people who aren't members of the National Assembly, but who still have CDF data displayed on their pages.

```
from pombola.core.models import Person
with_constituency_filtered = [
    x for x in Person.objects.all()
    if x.constituencies().filter(
        budget_entries__organisation='Constituencies Development Fund').exists()
    ]
not_members = [
    x for x in with_constituency_filtered
    if not x.position_set.filter(title__name='Member of the National Assembly')
    ]
[x.slug for x in not_members]
```

Currently there are 20 such people

```
'samuel-kambi'
'emilio-kathuri'
'linah-kilimo'
'geoffrey-kingangi'
'anthony-lofficer-leaduma'
'partamei-lepariyo'
'lucas-maitha'
'omari-nyanje-mbuli'
'john-mututho'
'anania-mwaboza'
'barnabas-mwangi'
'janet-midecha-mwenesi'
'andrew-njoroge'
'jack-ojiambo'
'kennedy-odoyo-okoth'
'judah-ole-metito'
'wilfred-ombui'
'phillip-rutino'
'hussein-sasura'
'mohamed-sirat'
```

**Comment by tmtmtmtm** [comment]
Thanks @duncanparkes. This seems like a problem that's likely to re-appear even if we clean up that data. I suspect we want to change the CDF allocation to only appear in the case of a current legislative membership for the constituency. 

#1831 looks like it might also be vaguely connected — the Area being set on a party membership there seems to also trigger confusion in the "Constituency" box.

**Comment by duncanparkes** [comment]
When we sort this out, we should probably revert the change I made to Sophia Noor to stop the CDF data being displayed in #1706.

**Comment by tmtmtmtm** [comment]
@paullenz is going to remove the wrong memberships on these ones for now. It would be good to find a better long term solution, but we may as well fix the immediate issue quicker.

**Comment by duncanparkes** [comment]
No need to remove the memberships themselves, just remove the association
with the constituency from them.

Duncan

**Comment by tmtmtmtm** [comment]
Yeah — that's what I meant, I was just imprecise. :)

**Comment by paullenz** [comment]
I think I have done these.  In a couple of cases there was a different problem - the aspirant MP role did not have an end-date set
