### ISSUE TITLE
Erroneous appearances for Morwamoche Andrew Ntwampe (PAC)

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1824]
The appearances in the House need to be removed for Morwamoche Andrew Ntwampe (PAC). He is not the ‘Mr Morwamoche (ANC)’ that comes up.

**Comment by paullenz** [comment]
The reason that this has happened is because there have been a couple of instances where the same Hansard record has been imported twice - I will go through the few instances where this has occurred and delete duplicate via the admin interface

**Comment by duncanparkes** [comment]
This is #1740 again - reopening the original issue.
