### ISSUE TITLE
ZA: small fixes for attendance data display on PA

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1825]
These arise from feedback from PMG about the version that has gone live:

> Thank you for the excellent work on the MP attendance. The layout is simple, easy to digest and exactly what we envisaged. We are excited about this initiative and hope it will generate some interest.
> 
> We would like to suggest the following:
> 
 - [x]     It should clearly state that this is attendance records for committee meetings and not plenary sittings.
 - [x]      The 2014 records should indicate: “From the start of the Fifth Parliament”
 - [x]     There needs to be a disclaimer. The suggested wording is as follows:
> 
> DISCLAIMER: This is not the official attendance record of Parliament and this information has been obtained via the Parliamentary Monitoring Group.  PMG makes every effort to compile reliable and comprehensive information, but does not claim that the data is 100% accurate and complete. This information is updated regularly…. [not sure if there is a better or more appropriate word to use. We populate attendance information on a daily/regular basis from our side and hope it is reflected soon thereafter on the PA website]

**Comment by duncanparkes** [comment]
I've added these three small changes in 414886fef8685e1fb5e55d38661d14aa1c4cdbc2.

**Comment by duncanparkes** [comment]
Before these changes

![attendance_before](https://cloud.githubusercontent.com/assets/56265/11397324/83538810-9370-11e5-8005-69539b659064.png)

and after

![attendance_after](https://cloud.githubusercontent.com/assets/56265/11397329/8852bb88-9370-11e5-9f42-9714d3ed4d39.png)

I haven't styled the new paragraphs, I'll leave choice of grey to @zarino!
