### ISSUE TITLE
ZA: Belinda Bozzoli confusing entries

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1828]
Belinda Bozzoli appears on the [Democratic Alliance (DA) members of the National Assembly — current members](http://www.pa.org.za/organisation/national-assembly/party/da/) page, but confusingly listed as "Member-elect" rather than "Member":

![screen shot 2015-11-14 at 09 46 05](https://cloud.githubusercontent.com/assets/57483/11162981/dbfcb050-8ab4-11e5-85c6-45422b95cc65.png)

Her own page has a confusing membership of "None":

![screen shot 2015-11-14 at 09 47 02](https://cloud.githubusercontent.com/assets/57483/11162983/e45e85a2-8ab4-11e5-9607-d0a56c35807c.png)

**Comment by paullenz** [comment]
This was caused by there not being an end date in the Member-elect role and no new member role following on from this - I have correct for her and another candidate who still had an open member-elect role by using the admin interface
