### ISSUE TITLE
MPs seeming to have multiple consituencies

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1831]
Some MPs are listed as being members for multiple constituencies.

Gideon Maitha, for example, is listed for both Kilifi North and Malindi: 

![screen shot 2015-11-19 at 09 20 14](https://cloud.githubusercontent.com/assets/57483/11266773/fb62bafa-8e9e-11e5-930a-f5214f8c9c57.png)

(note that the order also varies between page reloads):

![screen shot 2015-11-19 at 09 20 34](https://cloud.githubusercontent.com/assets/57483/11266778/ffebc56c-8e9e-11e5-8072-79daa8aa2a61.png)

This confuses my scraper greatly.

My assumption is that this is because of the two different memberships:
* Member of the National Assembly for Kilifi North
* Member of Orange Democratic Movement for Malindi

If the "Constituency" box is meant to list all Constituencies that anyone has ever been connected with in any capacity, it would be useful if they could at least be ordered or distinguished in some way. Or if it's only meant to be (for example) the current constituency of a sitting MP, then it should be restricted to that.

**Comment by paullenz** [comment]
The constituency box should only be showing the constituency that they represent in parliament

**Comment by paullenz** [comment]
Resolved as per #1822

**Comment by tmtmtmtm** [comment]
Thanks @paullenz — I've also added #1838 for making the constituency box only show the correct information, even if incorrect data is added again later.
