### ISSUE TITLE
Mzalendo / pa.org.za - add "update results" button to search

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1834]
Currently the advanced search results (see #1833) offers users the ability to filter the results based upon radio button selection or date range.  To at least this user it feels unintuitive that do to this you have to click on "Search" again and suggest that an "Update results" button is added to the advanced search function - it would have the same action as clicking search again, just be more intuitive for the user

![screen shot 2015-11-26 at 16 50 42](https://cloud.githubusercontent.com/assets/739624/11427805/dc30f402-945d-11e5-89dc-47abaa9d7e7e.png)

**Comment by duncanparkes** [comment]
@paullenz I wonder if it would be OK here just to change the 'Search' button into an 'Update Results' button under certain circumstances. Perhaps it should be 'Update Results' if there is a current search, for instance?

**Comment by paullenz** [comment]
If that is materially easier, yes (but I did like the idea of there being a
button in the box along with the filter items - felt a bit more logical to
be there

**Comment by duncanparkes** [comment]
I'll put my version on staging and you can see what you think.

**Comment by duncanparkes** [comment]
@zarino suggests a nicer plan:

'Add a second submit button, at the end of the form, that's very pale and greyed out UNTIL you make a change to the advanced settings, at which point the button activates into a red state, and reads "Update results"'

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/issues/1845

![screen shot 2015-11-26 at 16 48 23](https://cloud.githubusercontent.com/assets/739624/11427789/cb41ad4e-945d-11e5-8269-2d33df32b1e9.png)
