### ISSUE TITLE
Merging two profiles: Gasebonwe-Tongwane & Tongwane

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1836]
She was first called Tshoganetso Mpho Adolphina Gasebonwe 2009 - 2014.
She now calls herself Tshoganetso Mpho Adolphina Tongwane.

In the rush of all the new MPs in May 2014:
Someone at PMG must have tacked on her married name to the original PA
profile: http://www.pa.org.za/person/tshoganetso-mpho-adolphina-gasebonwe-tongwane/

Someone else at PMG must have created a new profile:

http://www.pa.org.za/person/tshoganetso-mpho-adolphina-tongwane/

There are 2009 - Mar 2014 Committee Appearances + Constituency Office
info in:      http://www.pa.org.za/person/tshoganetso-mpho-adolphina-gasebonwe-tongwane/

There are July 2014 - 2015 Committee Appearances in:

http://www.pa.org.za/person/tshoganetso-mpho-adolphina-tongwane/

Her attendance is not visible in either profile.

**Comment by duncanparkes** [comment]
Since 6b03c21f527eda595734f23e22840f81d93eb0d2, this can now be fixed with the following commands:

In `python manage.py shell`

```
>>> from pombola.core.models import Person
>>> Person.objects.filter(gender='Female').update(gender='female')
16
>>> Person.objects.filter(gender='Male').update(gender='male')
43
>>> Person.objects.filter(gender=' male').update(gender='male')
1
>>> 
>>> new_person = Person.objects.get(slug='tshoganetso-mpho-adolphina-tongwane')
>>> old_person = Person.objects.get(slug='tshoganetso-mpho-adolphina-gasebonwe-tongwane')
>>> new_person.title = old_person.title
>>> new_person.summary = old_person.summary
>>> new_person.save()
```
And then 

```
python manage.py core_merge_people --keep-person tshoganetso-mpho-adolphina-tongwane --delete-person tshoganetso-mpho-adolphina-gasebonwe-tongwane
```

**Comment by duncanparkes** [comment]
Removed a few duplicate memberships and a duplicate photo in the admin, and this is now done.
