### ISSUE TITLE
Add search box to the pa.org.za Hansard page

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1846]
On this page - http://www.pa.org.za/hansard/

There is the standard nav bar search box which searches everything - we would like a hansard-specific search box to be added to the page

**Comment by tmtmtmtm** [comment]
Currently the advanced search has an option to let you restrict your search to Hansard:

![screen shot 2016-01-15 at 16 14 38](https://cloud.githubusercontent.com/assets/57483/12358026/29f102ce-bba3-11e5-9958-79a2fb4008a3.png)

This triggers searches like: http://www.pa.org.za/search/?q=horse&section=hansard

I'm presuming this request is simply to add a search box that automatically adds that restriction.

**Comment by tmtmtmtm** [comment]
@paullenz this has now been added: http://www.pa.org.za/hansard/
