### ISSUE TITLE
Move social media icons to the top of the homepage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1849]
From PMG: "We also wanted the Facebook and Twitter icons moved to the top so that its immediately visible on the home page"

This is their second highest priority action.

**Comment by tmtmtmtm** [comment]
@JenMysoc does this apply to every page (i.e. moving these from the footer to the header?) — or only the home page?

**Comment by tmtmtmtm** [comment]
Current position: 
![screen shot 2015-12-14 at 22 21 13](https://cloud.githubusercontent.com/assets/57483/11795871/080b0aac-a2b1-11e5-935f-f548102b9699.png)
