### ISSUE TITLE
[ZA] Get rid of Newsletter and Survey Archive from Extras Tab 

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1850]
PMG have asked us to get rid of these two menu links from the Extras tab on the main menu bar

**Comment by tmtmtmtm** [comment]
![screen shot 2015-12-14 at 22 22 03](https://cloud.githubusercontent.com/assets/57483/11795908/37a13840-a2b1-11e5-89fb-4402e3ecdba0.png)
