### ISSUE TITLE
[ZA] Move "links" and "Get Data" from Extras menu link to the bottom of the page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1851]
Take these two items - links and Get data - off the Extras drop down menu and put them in the footer of the page

**Comment by tmtmtmtm** [comment]
![screen shot 2015-12-14 at 22 22 03](https://cloud.githubusercontent.com/assets/57483/11795913/45fd2d86-a2b1-11e5-86a5-dd17334e9abe.png)

**Comment by duncanparkes** [comment]
Fixed in  7f59264070815a638d855f55f4e3797ee31debe5
