### ISSUE TITLE
[ZA] Get rid of "extras" from the menu bar on PA.org.za

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1852]
linked to #1850 and #1851 and #1854 

PMG want the Extras item removed from the main menu bar along with all the items on the drop down menu.

**Comment by tmtmtmtm** [comment]
![screen shot 2015-12-14 at 22 22 03](https://cloud.githubusercontent.com/assets/57483/11795899/29ce33d0-a2b1-11e5-94de-ad32cb99c49f.png)

**Comment by duncanparkes** [comment]
Fixed in084698ea31fa0aac5eabf34f0e5466a6298d39c2
