### ISSUE TITLE
[ZA] Move 2014 election data from Extras item to Public Participation tab

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1854]
From PMG: “2014 Election data” should be moved and featured as a side menu to ‘Elections’ under the “Public Participation” tab.

**Comment by tmtmtmtm** [comment]
![screen shot 2015-12-14 at 22 22 03](https://cloud.githubusercontent.com/assets/57483/11795929/6570289e-a2b1-11e5-8f79-94369dfb7d1f.png)

![screen shot 2015-12-14 at 22 24 19](https://cloud.githubusercontent.com/assets/57483/11795943/76dd1272-a2b1-11e5-85ca-0d9862952fa0.png)
