### ISSUE TITLE
[ZA] Ability to reflect if an MP is a "former MP"

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1856]
From PMG: "We would like it to reflect on the MP profile if an MP is an “Former MP” - this is not happening: http://www.pa.org.za/person/graham-peter-dalziel-mac-kenzie/"

**Comment by tmtmtmtm** [comment]
MacKenzie:

![screen shot 2015-12-14 at 22 35 31](https://cloud.githubusercontent.com/assets/57483/11796243/3453ee9c-a2b3-11e5-889e-a73f41787675.png)

I'm presuming this should be a modified version of the "National Assembly" text below an existing MP's name?:

![screen shot 2015-12-14 at 22 28 24](https://cloud.githubusercontent.com/assets/57483/11796052/1706174e-a2b2-11e5-87fd-1a729d185e0c.png)
