### ISSUE TITLE
[ZA] Allow for label of MLP under person name on person page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1857]
From PMG: "We decided that Member at “National Assembly”, “National Council of Provinces” or “Western Cape Provincial Legislature” should be captured underneath MP’s name. Thanks for doing that, but we noticed that it has not been done for Members of Provincial Legislatures (MPLs)"

We need to add this option in the same way we added the other options

**Comment by tmtmtmtm** [comment]
For National Assembly members this currently looks like ([Adams](http://www.pa.org.za/person/patricia-emily-adams/))
![screen shot 2015-12-14 at 22 28 24](https://cloud.githubusercontent.com/assets/57483/11796052/1706174e-a2b2-11e5-87fd-1a729d185e0c.png)

For National Council of Provinces: ([von Brandis](http://www.pa.org.za/person/eugene-von-brandis/))

![screen shot 2015-12-14 at 22 29 19](https://cloud.githubusercontent.com/assets/57483/11796065/2bf88a38-a2b2-11e5-8404-d47f07520fe9.png)

This still needs to be done for all the Provincial Legislatures: ([Botha](http://www.pa.org.za/person/lorraine-juliette-botha/))

![screen shot 2015-12-14 at 22 32 34](https://cloud.githubusercontent.com/assets/57483/11796152/ae3282ba-a2b2-11e5-979a-93b01dcbc56b.png)
