### ISSUE TITLE
[KE] Run the MP performance stats for Mzalendo as per the approach taken in prior years

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#1873]

**Comment by JenMysoc** [comment]
Jess asked the following: Beyond the count of the actual number of times an MP has spoken, how granular can you really get in your analysis? Is it possible to generate a word cloud of what each MP has been speaking about? Would we have to give you the phrases we would be looking out for?

**Comment by JenMysoc** [comment]
The ticket from last year: https://github.com/mysociety/pombola/issues/1160

**Comment by mhl** [comment]
I've sent an initial version of this data to Jess, but there are a couple of things to consider:
* People missing a position in `all-speakers.csv` spreadsheet
* That, as @duncanparkes pointed out, there are some duplicate sittings in the database, so speeches will be overcounted

**Comment by mhl** [comment]
Other issues highlighted by Jessica:

> Below are anomalies we have come across in the speech counts: Names of current MPs are in bold ink.
> 
> 1. Josephat Nanok the governor of Turkana County still appears on the list. 
> He shares a surname with the current MP of Turkana West, Daniel Epuyo Nanok- May be this is where the problem could be.
> 
> 2. Judah Katoo Metito is the MP of Kajiado East. It seems the system didn't capture this.
> 
> 3. Maalim Mohamed Abdisalan is not a member of Parliament but he has speech counts. Maalim vied for an MCA in the last election, I still cannot figure out how he got speech counts. His counts should be posted under Eng. Maalim Mohamud Mohamed, the MP for Mandera West
> 
> 4. Christopher Omulele is the MP of Luanda Constituency in Vihiga County. The system didn't capture this. 
> 
> 5. John Zebedeo opore is the MP of Bonchari in Kisii County. The system didn't capture this.
> 
> 6. Kipkorir Marisin Sang is the MP of Bureti in Kericho County. This wasn't captured by the system.
> 
> 7. Margaret Nabwala Toili isn't a Member of Parliament but she appears on the list. She vied for Kabuchai costituency Member of Parliament in the last election. We cant figure out why she appears on the list.

**Comment by mhl** [comment]
Another thing mentioned by Jen is that the spreadsheet only lists people with *some* speeches - it would be helpful to list those with 0 speeches as well, so they can be manually checked.

**Comment by tmtmtmtm** [comment]
I'm marking this ticket as Done — we can open new tickets if there's any further feedback
