### ISSUE TITLE
Positions Held tab should display for people with no historic positions

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1877]
Why is there no positions held tab being displayed here despite membership of NCOP?

http://www.pa.org.za/person/landulile-cathrine-dlamini/

![2015-12-17-112223_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11868662/64b671fe-a4b1-11e5-973c-5104aa925c87.png)

**Comment by duncanparkes** [comment]
See also: http://www.pa.org.za/person/eddie-makue/

**Comment by tmtmtmtm** [comment]
@paullenz @JenMysoc is there an underlying problem in the data for these people that could be fixed (whether by us or by asking PMG to do it)? Or is the data all OK, and this is purely a code-level problem?

**Comment by duncanparkes** [comment]
It looks to me as though the 'Positions Held' tab is only being show for people who have some inactive positions - which is odd, because it contains details of the active ones as well.

https://github.com/mysociety/pombola/blob/25b76f2/pombola/south_africa/templates/core/person_detail.html#L65

**Comment by mhl** [comment]
Fixed with a9dfa3de5930b098323861826b241dad575c602f and e1f200d3cd520e3bd235b6e143cf5724caff4f55.
