### ISSUE TITLE
Dedupe organisations displayed under a person's name

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1878]
Note that National Council of Provinces appears twice here!

http://www.pa.org.za/person/dr-mateme-hunadi-euphemia/

![2015-12-17-113552_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11868801/6fd3d60c-a4b2-11e5-8ed0-0a2f6a4c853b.png)

**Comment by gailefullard** [comment]
this looks good now (including the use of Formerly:)

**Comment by tmtmtmtm** [comment]
Done.
