### ISSUE TITLE
Who should be displayed Office Bearers page?

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1879]
http://www.pa.org.za/organisation/national-assembly/people/?page=1&office=1

Following the 'Office Bearers' link from the National Assembly page gets a slightly odd list of people.

![2015-12-17-115204_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11869094/9f174e88-a4b4-11e5-9db9-548dd834f29c.png)

I'm not convinced 'Member-elect' is the kind of office we want here:

![2015-12-17-114931_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11869060/56780ab4-a4b4-11e5-933a-2dae6f9bf404.png)

And what about the two people whose office is displayed as 'None'?

![2015-12-17-114949_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/11869063/5adf3e92-a4b4-11e5-9dbc-2f689048e677.png)

**Comment by tmtmtmtm** [comment]
@JenMysoc / @paullenz — do you know what this page _should_ be doing?

**Comment by JenMysoc** [comment]
PMG need to discuss this page internally and will provide us feedback soon, therefore this is not a high priority ticket at the moment.

**Comment by JenMysoc** [comment]
PMG are happy for pages of this type to be killed so please go ahead and remove the "Office Bearers" pages

**Comment by duncanparkes** [comment]
![2016-02-04-090602_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/12810566/e6bece60-cb1e-11e5-903f-2eb06f9e8edb.png)
![2016-02-04-090617_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/12810571/edf93b0c-cb1e-11e5-90f8-6c5fcb651b0e.png)
