### ISSUE TITLE
[ZA] Handle local government on the Rep Locator for PA.org.za

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1883]
From PMG:

We are only 45 municipalities short of having all the ward councillors' personal mobile numbers (and email addresses if they have). Our team will be working on the missing 45 when we come back in January. We gave Greg another 66 municipalities which he loaded onto http://www.pa.org.za/ward-councillor-lookup/ last week. This is in addition to the 82 we gave him earlier. SA has 278 municipalities (but 85 of these are district municipalities which do not have wards). As it is local elections around May 2016 - it is pertinent.

PMG would therefore like the Rep Locator to also handle the ward level for the ward councillors.

**Comment by tmtmtmtm** [comment]
@JenMysoc is there a more detailed spec for this somewhere? It may be that it's obvious to @duncanparkes or @mhl exactly what is needed here, but it would be good to avoid any guesses or misinterpretation when implementing this.

AIUI, the Rep Locator is currently linked from the footer, and goes to http://www.pa.org.za/search/location/

A search returns a (to me slightly confusing) page that shows, by default "Constituency Offices", ordered by distance, and zero or more people connected with those:
![screen shot 2015-12-18 at 10 55 19](https://cloud.githubusercontent.com/assets/57483/11895352/f317f0f2-a575-11e5-9ec0-5dbd65e46890.png)

but with links (that seem like they should really look like tabs) to let you toggle between that and National Representatives (a plain list of people):

![screen shot 2015-12-18 at 10 55 34](https://cloud.githubusercontent.com/assets/57483/11895366/07a45bc8-a576-11e5-92c1-1595b0aa77a5.png)

Is the idea here that this would be a third page that could be selected from either of those? Will there be other ways you can get to these pages? What should the results look like?

**Comment by gailefullard** [comment]
mySociety needs to advise us on how best this could work in a 3-tier government system

**Comment by tmtmtmtm** [comment]
superseded by #1895
