### ISSUE TITLE
Create promotion guide for partners

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/pombola#1884]
Similar to https://github.com/mysociety/alaveteli/issues/2966 and https://github.com/mysociety/fixmystreet-international/issues/28, Pombola should have a guide to make promotion easier for partners.

**Comment by mhl** [comment]
Probably this is something that @JenMysoc / @davewhiteland should look into?

**Comment by JenMysoc** [comment]
This is something we need to do with @MyfanwyNixon in the future.

**Comment by MyfanwyNixon** [comment]
Closed as no longer relevant.
