### ISSUE TITLE
ZA: NCOP members wrongly grouped as 'Other' on Place pages

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1886]
http://www.pa.org.za/organisation/ncop/people/ shows all the National Council of Provinces members:

![screen shot 2015-12-19 at 12 37 21](https://cloud.githubusercontent.com/assets/57483/11913008/f6f99f62-a64d-11e5-9c07-fc16199e98f3.png)

However, when you click on one of those province names to go to the Area page (e.g. http://www.pa.org.za/place/mpumalanga/), this lists 0 members of the NCOP:

![screen shot 2015-12-19 at 12 44 12](https://cloud.githubusercontent.com/assets/57483/11913015/4582be66-a64e-11e5-92bb-2b4decc2fb66.png)

with the actual members being grouped under 'Other' instead:

![screen shot 2015-12-19 at 12 45 00](https://cloud.githubusercontent.com/assets/57483/11913019/5cfa2cdc-a64e-11e5-9143-052681294974.png)

**Comment by duncanparkes** [comment]
The problem is here

https://github.com/mysociety/pombola/blob/54911ea/pombola/south_africa/views.py#L255

The only positions which are considered are those with the title_slug of 'member'. NCOP positions have title_slug 'delegate'.

**Comment by tmtmtmtm** [comment]
@duncanparkes is that what's causing things like https://github.com/mysociety/pombola/issues/1877 as well? 

Is there something about NCOP positions that mean that these _should_ be different (and we need to change various things to cope with that), or can these all be harmonised?

**Comment by duncanparkes** [comment]
I think #1877 is something different - I'll comment over there.

In general I think we have a big problem with slugs of things like membership titles/organisations/organisation kinds finding there way into the code. All this is data which can be changed from the Django admin, and when it is changed, things will break.

**Comment by duncanparkes** [comment]
I'm inclined to think we should just make this little bit of code accept 'delegate' for the NCOP positions for now. There are already a lot of places where it allows 'member' and 'delegate'.
