### ISSUE TITLE
update to django 1.8

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1893]
We were originally intending to do #1594 before this, but that kind of "stop-the-world" refactoring no longer seems like such a good idea (particularly given the experience of migrating YNR to django-popolo, which is an easier job) and it certainly shouldn't block us getting onto the most recent version of Django, since Pombola is now using a version of Django that won't be getting security updates.

(This will mean updating SayIt and its dependent version of django-popolo too.)

**Comment by mhl** [comment]
The most difficult part of this upgrade by a long way is the upgrade of SayIt since that involves a migration of SayIt underlying representation of people, switching from popit-django to django-popolo. That also affects popit-resolver and za-hansard. So I think this makes most sense to do in three steps:

- [ ] Update SayIt to the latest version while remaining on Django 1.6.5 - there's now a [pull request for this (which links to related dependent pull requests)](https://github.com/mysociety/pombola/pull/1951)
- [ ] Update Django to 1.7
- [ ] Update Django to 1.8

The second two steps should be relatively easy once the first one is done, but we want to make sure that's working first.

**Comment by mhl** [comment]
Done now :fireworks:

**Comment by tmtmtmtm** [comment]
woooohooooo!
