### ISSUE TITLE
migrate to using mysociety-django-images

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1898]
We extracted pombola's `images` app into https://github.com/mysociety/django-images (mysociety-django-images on pypi) for YNR, however we didn't switch Pombola to use that at the same time. We should do that - it should be a quick thing to do since nothing's changed in the models.

**Comment by duncanparkes** [comment]
Fixed in 8739e4f2ea9a0aebe5ece7ddb052ab2abbe27827.
