### ISSUE TITLE
remove old kuvakazim vhosts

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1902]
If the "pombola light" static Kuvakazim site is working out well, we should remove the old Pombola-based Kuvakazim vhosts - hopefully @tmtmtmtm or @chrismytton can say when they're happy for that to happen.

**Comment by tmtmtmtm** [comment]
I suspect we're OK to go ahead with this now? @chrismytton ?

**Comment by chrismytton** [comment]
Yep, fine by me. I believe I've copied all the relevant files over to the [`media_root` directory in KuvakaZim](https://github.com/mysociety/kuvakazim/tree/master/media_root), let me know if I've missed anything!

**Comment by chrismytton** [comment]
Done. Vhost files and database dumps are in my home directory on firefly.
