### ISSUE TITLE
[ZA] Move "MP Corner" "Advocacy Campaign" and "Members' Interests" to sit under Hot Topics on the Menu Bar

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1918]
PMG would like to reshuffle the items on the drop downs from the menu bar if possible. These changes are as follows:

Move "MP Corner" and "Advocacy Campaigns" from the Blog section to the Hot Topics section.

![screen shot 2016-01-21 at 15 06 51](https://cloud.githubusercontent.com/assets/4170351/12484162/eb012686-c050-11e5-99c5-a8869f74c9c9.png)

Move "Members' Interests" from Democracy Resources to the Hot Topics section

![screen shot 2016-01-21 at 15 09 21](https://cloud.githubusercontent.com/assets/4170351/12484216/25f34ef4-c051-11e5-8793-79e17cf3e263.png)

**Comment by gailefullard** [comment]
plus rename Members' Interests = MP Assets

**Comment by JenMysoc** [comment]
@gailefullard When you say MP Comments do you mean MP Profile? We've put MP Profile in the list where you've put MP Comments because there's not a specific comments section for MPs at the moment on the site :) and you mentioned you wanted MP Profiles on this list.

**Comment by gailefullard** [comment]
Yes, apologies, I mean MP profile

**Comment by tmtmtmtm** [comment]
Although these have been correctly moved in the header bar itself, the page that you get to from clicking the primary link in the header is still out of date.

i.e. The 'Democracy Resources' page needs to link to the Bill Tracker and Committees pages:

![screen shot 2016-02-12 at 09 32 01](https://cloud.githubusercontent.com/assets/57483/13003152/c0d09a3c-d16b-11e5-82e8-85e18ed022e2.png)
![screen shot 2016-02-12 at 09 32 29](https://cloud.githubusercontent.com/assets/57483/13003155/c723b022-d16b-11e5-89eb-3fc650358589.png)

and similar for the 'Hot Topics' page:

![screen shot 2016-02-12 at 09 32 13](https://cloud.githubusercontent.com/assets/57483/13003165/d0631ede-d16b-11e5-8661-701b5d7b84fc.png)
![screen shot 2016-02-12 at 09 32 21](https://cloud.githubusercontent.com/assets/57483/13003167/d1f2e838-d16b-11e5-8283-3f4c17e17f0f.png)

**Comment by JenMysoc** [comment]
This is now done in the admin and the pages are displaying correctly

**Comment by tmtmtmtm** [comment]
Yay!
