### ISSUE TITLE
[KE] Josephat Nanok appears on the speech count list for Turkana when he shouldn't

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#1921]
On Jessica's MP Speeches, Josephat Nanok should no longer appear - He is a Governor of Turkana. The current MP of  Turkana West is Daniel Epuyo Nanok who should appear instead.

**Comment by duncanparkes** [comment]
Since 3c7d3098d59f10a15226e427feb9969ac3bf7608, Governors no longer appear in the stats.
