### ISSUE TITLE
Import constituency office data and photos

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/pombola#1938]
PMG have been undertaking an exercise to collect accurate locations and photos of all the party constituency offices.

We need:

  - [x] A new script to import their data and update our database with the correct locations
  - [x] The script to also store copies of the photos
  - [x] To display the photos on each constituency office page [do #1948 at same time]

**Comment by duncanparkes** [comment]
This possibly relates to #1311

**Comment by duncanparkes** [comment]
d6bf2d6b4d53bf65b347c0c0b772271ccce75f0a Does the office name matching and location update parts of this.

**Comment by zarino** [comment]
Regarding the display of the photos: Given there will be more offices *without* a photo than *with*, putting it somewhere structurally insignificant would be best (so there isn't an obvious gap when no photo is available). I'm thinking below the map in the sidebar:

![screen shot 2016-02-15 at 17 17 25](https://cloud.githubusercontent.com/assets/739624/13055580/07f31766-d408-11e5-9627-e3cf29a1ce8c.png)

The downside of this is that it pushes the address and phone details further down. Do you think that will be an issue @JenMysoc @mhl?

Do we know anything about the aspect ratio of the images? (ie: Are they all landscape?)

**Comment by tmtmtmtm** [comment]
I'd lean towards even putting it _after_ the address — as I'm assuming the primary use case here is so that you can recognise it if you go visit, which would request getting the address first… (I may be completely misunderstanding what this is for, though)

**Comment by zarino** [comment]
Something like this? @tmtmtmtm @JenMysoc 

![screen shot 2016-02-16 at 16 09 37](https://cloud.githubusercontent.com/assets/739624/13082225/ba421da8-d4c7-11e5-86ca-f31677a8ac24.png)

**Comment by JenMysoc** [comment]
:+1: Looks awesome to me

**Comment by zarino** [comment]
Here's roughly how it'll look on a mobile – with the photo about halfway down the page, after the map and contact details:

![screen shot 2016-02-16 at 16 11 00](https://cloud.githubusercontent.com/assets/739624/13082286/fac2ea6a-d4c7-11e5-89ff-36da9a6be12f.png)

**Comment by zarino** [comment]
I've pushed this little bit of styling to the `1938-import-new-constituency-office-data` branch.

Now it needs a developer (@duncanparkes @mhl?) to replace the hard-coded example image with the actual image for the constituency office.
