### ISSUE TITLE
KE: /organisation/ford-kenya/ and /organisation/ford-k/ are the same party

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1940]
We currently have two separate entries for "Forum for the Restoration of Democracy–Kenya (FORD-Kenya)" — http://info.mzalendo.com/organisation/ford-kenya/ (which has all the information about the party, but only a handful of members), and http://info.mzalendo.com/organisation/ford-k/ (which has no blurb, but most of the members). 

(NB: There are also two spin-off parties: http://info.mzalendo.com/organisation/nfk/ and http://info.mzalendo.com/organisation/ford-p/, which are correctly distinct)

**Comment by tmtmtmtm** [comment]
@JenMysoc should check with Jessica if this is definitely so. If so we need to find a way to merge them. There's no admin command to merge orgs (only people), but we should probably make one.

**Comment by JenMysoc** [comment]
@JessMusila Do you know whether the FORD-Kenya and FORD-K are the same parties on Mzalendo? If so we'll merge in the information so that one is complete. If we do that which name should we use; FORD-Kenya or FORD-K?

**Comment by JessMusila** [comment]
@tmtmtmtm @JenMysoc Ford-Kenya or Ford-K is the same party. The preferred name to use is Ford-Kenya.

**Comment by chrismytton** [comment]
Needed to update the `started` field on Ford-Kenya:

```python
from pombola.core.models import Organisation
fk = Organisation.objects.get(pk=1175)
fk.started = '1990-00-00'
fk.save()
```

**Comment by chrismytton** [comment]
To merge the orgs we need to run the following command:

```
python manage.py core_merge_organisations --keep-object=1175 --delete-object=23
```

**Comment by chrismytton** [comment]
Done on staging and live sites.
