### ISSUE TITLE
ZA: "More…" link on NCOP page 404s

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1950]
From http://www.pa.org.za/organisation/ncop/, the "More…" link goes to http://www.pa.org.za/organisation/ncop/info/national-council-provinces, which 404s:

![screen shot 2016-02-12 at 09 52 02](https://cloud.githubusercontent.com/assets/57483/13003596/7791476a-d16e-11e5-9aa0-114d28818dc4.png)

**Comment by tmtmtmtm** [comment]
Looks like this is because the link is relative:

```
<p><a href="info/national-council-provinces" title="NCOP">More...</a></p>
```

but should be to `/info/national-council-provinces`

**Comment by tmtmtmtm** [comment]
This looks like it's something that's set on the Organisation (i.e. should be fixed in the admin interface), rather than a code-level problem.

**Comment by mhl** [comment]
Indeed, in the admin there's a "Summary" field which is markdown - it literally includes that "More" link with the wrong path.

**Comment by JenMysoc** [comment]
I can't find the cut off bit on the page in the admin. The summary area just has this as a continuous bit of text.
![screen shot 2016-02-17 at 16 48 17](https://cloud.githubusercontent.com/assets/4170351/13117109/7d987350-d596-11e5-9cc6-b691f3583991.png)

Here you can see the bit on the page where it is cutting off the text, but there's nothing there nor any links that I can easily see in the text there.

**Comment by mhl** [comment]
@JenMysoc That looks like the admin page that lets you edit the info page about the National Council of Provinces. That's what the "More" text should link to, so you actually want to be editing the "Summary" text of the "National Council of Provinces" Organisation in the admin to fix the link - the URL for that is: http://www.pa.org.za/admin/core/organisation/71/

**Comment by JenMysoc** [comment]
Fixed!
