### ISSUE TITLE
Remove MPLs from /position/member/parliament

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1958]
http://www.pa.org.za/position/member/parliament/?order=name should not include members of the provincial legislatures - only the national level ones.

**Comment by mhl** [comment]
This view should only be showing people related to positions such that:

* The PositionTitle has slug 'member'
* The OrganisationKind is 'parliament'

The only organisations of that OrganisationKind are: "National Assembly" and "National Assembly".

The provincial legislatures have OrganisationKind "Provincial-Legislature", on the other hand.

Do you have an example of an MPL who appears in this list so I could investigate further?

**Comment by tmtmtmtm** [comment]
This was split out from the original ticket https://github.com/mysociety/pombola/issues/1908, which didn't really give much more information.

From scanning email, however, it seems that this came from the "roundup of work done and work to be done" email of Jan 12th, which said "the pagination complaint also referred to  HOT TOPICs MP Profiles page http://www.pa.org.za/position/member/parliament/?order=name should be working like this too but it can combine both NA & NCOP - the provincial legislatures are not part of HOT TOPICS"

It's unclear whether that's saying "this page currently includes MPLs and shouldn't", or is just letting us know that it correctly doesn't include them, but as the code seems to be doing the right thing, I think we can assume the latter, and close this.
