### ISSUE TITLE
update the install script to restore the public database dump for each country

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1959]
Now we have a public database dump available for each country, we should be able to update `bin/install-as-user` to import that data after creating the database.

(There may be some issues there where the migrations say that particular tables are created, but they're not in the dump because we excluded any with anything like personal information in them.)

This would make the Vagrantfile for Pombola development much more useful.

This is a precursor to https://github.com/mysociety/pombola/issues/1892

**Comment by chrismytton** [comment]
This is now done as part of vagrant provisioning.
