### ISSUE TITLE
KE: Constituency mismatches with Official site

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1961]
This afternoon I scraped the official Kenyan Parliament website. When matching the data there to Mzalendo I discovered a bunch of people whose Constituency information differs across the two sites:

* Aden Bare Duale ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/215-duale-aden-bare): Tavedujis / [Mzalendo](http://info.mzalendo.com/person/aden-duale/): Garissa Township)
* Bernard Munywoki Kitungi ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/289-kitungi-bernard-munywoki): Mwingi North / [Mzalendo](http://info.mzalendo.com/person/bernard-munywoki-kitungi/): Mwingi West)
* Edwin Kipruto Barchilei ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/183-barchilei-edwin-kipruto): Eldoret East / [Mzalendo](http://info.mzalendo.com/person/edwin-kipruto-barchilei/): Soy)
* Elijah Lagat ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/299-lagat-elijah-kiptarbei): Tinderet / [Mzalendo](http://info.mzalendo.com/person/elijah-lagat/): Chesumei)
* Elisha Kipkorir Busienei ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/196-busienei-elisha-kipkorir): Eldoret East / [Mzalendo](http://info.mzalendo.com/person/elisha-kipkorir-busienei/): Turbo)
* James Kimaru Bett ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/187-bett-james-kimaru): Eldoret East / [Mzalendo](http://info.mzalendo.com/person/james-kimaru-bett/): Kesses)
* James Mwangi Gakuya ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/227-gakuya-james-mwangi): Westlands / [Mzalendo](http://info.mzalendo.com/person/james-mwangi-gakuya/): Embakasi North)
* Jimmy Angwenyi ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/174-angwenyi-jimmy-nuru-ondieki): Bonchari / [Mzalendo](http://info.mzalendo.com/person/jimmy-angwenyi/): Kitutu Chache North)
* John Ndirangu Kariuki ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/262-kariuki-john-ndirangu): Westlands / [Mzalendo](http://info.mzalendo.com/person/john-ndirangu-kariuki/): Embakasi Central)
* Joseph Kirui Limo ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/309-limo-kirui-joseph): Ainamoi / [Mzalendo](http://info.mzalendo.com/person/joseph-kirui-limo/): Kipkelion East)
* Justice Kipsang Kemei ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/269-kemei-justice-kipsang): Ainamoi / [Mzalendo](http://info.mzalendo.com/person/justice-kipsang-kemei/): Sigowet/Soin)
* Kabando wa Kabando ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/250-kabando-kabando-wa): Tetu / [Mzalendo](http://info.mzalendo.com/person/kabando-kabando/): Mukurweini)
* Korei Ole Lemein ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/303-lemein-korei-ole): Kilgoris / [Mzalendo](http://info.mzalendo.com/person/korei-ole-lemein/): Narok South)
* Lemanken Aramat ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/179-aramat-lemanken): Kilgoris / [Mzalendo](http://info.mzalendo.com/person/lemanken-aramat/): Narok East)
* Mohamed Adan Huka ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/241-huka-mohamed-adan): Mandera West / [Mzalendo](http://info.mzalendo.com/person/mohamed-adan-huka/): Mandera South)
* Samuel Kiprono Chepkonga ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/206-chepkonga-samuel-kiprono): Eldoret East / [Mzalendo](http://info.mzalendo.com/person/samuel-kiprono-chepkonga/): Ainabkoi)
* Samuel Moroto ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/211-chumel-samuel-moroto): Kapenguri / [Mzalendo](http://info.mzalendo.com/person/samuel-moroto/): Kapenguria)
* Wesley Kipchumba Korir ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/295-korir-wesley-kipchumba): Cherenganyi / [Mzalendo](http://info.mzalendo.com/person/wesley-kipchumba-korir/): Cherangany)

A couple of those look like simple typos (though worth checking whether that's on the official site or Mzalendo), but most of them look more significant.

There were also some who have no constituency on Mzalendo (only a County), but do on the Official site:

* Aisha Jumwa Katana ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/265-katana-aisha-jumwa): Kilifi North / [Mzalendo](http://info.mzalendo.com/person/aisha-jumwa-katana/): [none])
* Alice Nyanchoka Chae ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/197-chae-alice-nyanchoka): Kitutu Masaba / [Mzalendo](http://info.mzalendo.com/person/alice-nyanchoka-chae/): [none])
* Annah Nyokabi Gathecha ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/229-gathecha-annah-nyokabi): Gatundu South / [Mzalendo](http://info.mzalendo.com/person/annah-nyokabi-gathecha/): [none])
* Dennitah Ghati ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/233-ghati-dennitah): Rongo / [Mzalendo](http://info.mzalendo.com/person/dennitah-ghati/): [none])
* Fatuma Ibrahim Ali ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/167-ali-fatuma-ibrahim): Wajir North / [Mzalendo](http://info.mzalendo.com/person/fatuma-ibrahim-ali/): [none])
* Florence Kajuju ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/252-kajuju-florence): Igembe South / [Mzalendo](http://info.mzalendo.com/person/florence-kajuju/): [none])
* Halima Ware Duri ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/218-duri-halima-ware): Garsen / [Mzalendo](http://info.mzalendo.com/person/halima-ware-duri/): [none])
* Hellen Chelangat Chepkwony ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/207-chepkwony-hellen-chelangat): Ainamoi / [Mzalendo](http://info.mzalendo.com/person/hellen-chelangat-chepkwony/): [none])
* Jane Agnes Wanjira Machira ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/317-machira-jane-agnes-wanjira): Laikipia East / [Mzalendo](http://info.mzalendo.com/person/jane-agnes-wanjira-machira/): [none])
* Joyce Akai Emanikor ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/221-emanikor-joyce-akai): Turkana North / [Mzalendo](http://info.mzalendo.com/person/joyce-akai-emanikor/): [none])
* Joyce Wanjalah Lay ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/301-lay-joyce-wanjalah): Taveta / [Mzalendo](http://info.mzalendo.com/person/joyce-wanjalah-lay/): [none])
* Mahbub Fathia ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/223-fathia-mahbub): Mandera West / [Mzalendo](http://info.mzalendo.com/person/mahbub-fathia/): [none])
* Maison Leshoomo ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/306-leshoomo-maison): Samburu West / [Mzalendo](http://info.mzalendo.com/person/maison-leshoomo/): [none])
* Mary Sally Keraa ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/271-keraa-mary-sally): Bonchari / [Mzalendo](http://info.mzalendo.com/person/mary-sally-keraa/): [none])
* Mishi Juma Khamisi ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/274-khamisi-mishi-juma): Changamwe / [Mzalendo](http://info.mzalendo.com/person/mishi-juma-khamisi/): [none])
* Nasra Ibrahim Ibren ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/242-ibren-nasra-ibrahim): Moyale / [Mzalendo](http://info.mzalendo.com/person/nasra-ibrahim-ibren/): [none])
* Priscilla Nyokabi Kanyua ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/259-kanyua-priscilla-nyokabi): Tetu / [Mzalendo](http://info.mzalendo.com/person/priscilla-nyokabi-kanyua/): [none])
* Rachel Ameso Amolo ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/170-amolo-rachel-ameso): Lugari / [Mzalendo](http://info.mzalendo.com/person/rachel-ameso-amolo/): [none])
* Regina Nyeris Changorok ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/198-changorok--regina-nyeris): Kapenguri / [Mzalendo](http://info.mzalendo.com/person/regina-nyeris-changorok/): [none])
* Sabina Wanjiru Chege ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/203-chege-sabina-wanjiru): Kangema / [Mzalendo](http://info.mzalendo.com/person/sabina-wanjiru-chege/): [none])
* Shukran Hussein Gure ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/240-gure-shukra-hussein): Tavedujis / [Mzalendo](http://info.mzalendo.com/person/shukran-hussein-gure/): [none])
* Susan Kipketer Chebet ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/201-chebet-susan-kipketer): Marakwet East / [Mzalendo](http://info.mzalendo.com/person/susan-kipketer-chebet/): [none])
* Tiyah Galgalo Ali ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/166-ali-tiyah-galgalo): Isiolo North / [Mzalendo](http://info.mzalendo.com/person/tiyah-galgalo-ali/): [none])
* Zainab Kalekye Chidzuga ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/210-chidzuga-zainab-kalekye): Msambweni / [Mzalendo](http://info.mzalendo.com/person/zainab-kalekye-chidzuga/): [none])
* Zipporah Jesang Kurgat Kering ([Official](http://www.parliament.go.ke/the-national-assembly/members/item/272-kering-zipporah-jesang-kurgat): Tinderet / [Mzalendo](http://info.mzalendo.com/person/zipporah-jesang-kurgat-kering/): [none])

**Comment by JenMysoc** [comment]
I think @JessMusila would be best placed to suggest where the data is wrong and on which site :)

**Comment by JessMusila** [comment]
@tmtmtmtm @JenMysoc 

Constituency boundaries changed before the 2013 general elections. The correct constituency names have the tag (Constituency 2013 -) against them. The constituency names on Mzalendo are correct as they were issued by the IEBC and gazetted before the election.

For the list you generated the correct MP and Constituency match follows:

- Aden Bare Duale - Garissa Township
- Bernard Munywoki Kitungi - Mzalendo: Mwingi West
- Edwin Kipruto Barchilei - Soy
- Elijah Lagat - Chesumei
- Elisha Kipkorir Busienei - Turbo
- James Kimaru Bett - Kesses
- James Mwangi Gakuya - Embakasi North
- Jimmy Angwenyi - Kitutu Chache North
- John Ndirangu Kariuki - Embakasi Central
- Joseph Kirui Limo - Kipkelion East
- Justice Kipsang Kemei - Sigowet/Soin
- Kabando wa Kabando - Mukurweini
- Korei Ole Lemein - Narok South
- Lemanken Aramat - Narok East
- Mohamed Adan Huka - Mandera South
- Samuel Kiprono Chepkonga - Ainabkoi
- Samuel Moroto - Kapenguria
- Wesley Kipchumba Korir - Cherangany

In the March 2013 election, 47 women parliamentarians (County Members of the National Assembly or women representatives) were elected under affirmative action. They don't have constituency names against their profiles as that is not their official jurisdiction. 

We have linked each woman MP with her correct title and the county she represents.

1. Aisha Jumwa Katana - County/Women Rep - Kilifi County
2. Alice Nyanchoka Chae - County/Women Rep - Nyamira County
3. Annah Nyokabi Gathecha - County/Women Rep - Kiambu County
4. Dennitah Ghati - County/Women Rep - Migori County
5. Fatuma Ibrahim Ali - County/Women Rep - Wajir County
6. Florence Kajuju - County/Women Rep - Meru County
7. Halima Ware Duri - County/Women Rep - Tana River County
8. Hellen Chelangat Chepkwony - County/Women Rep - Kericho County
9. Jane Agnes Wanjira Machira - County/Women Rep - Laikipia County
10. Joyce Akai Emanikor - County/Women Rep- Turkana County
11. Joyce Wanjalah Lay - County/Women Rep - Taita Taveta County
12. Mahbub Fathia - County/Women Rep - Mandera County
13. Maison Leshoomo - County/Women Rep - Samburu County
14. Mary Sally Keraa - County/Women Rep. - Kisii County
15. Mishi Juma Khamisi - County/Women Rep. - Mombasa County
16. Nasra Ibrahim Ibren - County/Women Rep - Marsabit County
17. Priscilla Nyokabi Kanyua - County/Women Rep - Nyeri County
18. Rachel Ameso Amolo - County/Women Rep - Kakamega County
19. Regina Nyeris Changorok - County/Women Rep - West Pokot County
20. Sabina Wanjiru Chege - County/Women Rep - Murang'a County
21. Shukran Hussein Gure - County/Women Rep - Garissa County
22. Susan Kipketer Chebet  - County/Women Rep - Elgeyo Marakwet county
23. Tiyah Galgalo Ali - County/Women Rep - Isiolo County
24. Zainab Kalekye Chidzuga - County/Women Rep - Kwale County
25. Zipporah Jesang Kurgat Kering  - County/Women Rep - Nandi County

We also got 16 women senators and some nominated women MPs representing special interests and party proportions.

**Comment by tmtmtmtm** [comment]
Thanks @JessMusila. It's quite astonishing that the official site can be so bad. I can only even find half the MPs listed on it. Do you know if the others are hiding somewhere different, or whether they're simply just missing?

**Comment by JessMusila** [comment]
@tmtmtmtm The gaps in www.parliament.go.ke validate Mzalendo's very existence. Their website is incomplete. We had also noted that majority of the MPs names are missing.
