### ISSUE TITLE
KE: data report — missing start date

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1968]
The following people have legislative memberships with no start date:

```
 id  |     legal_name     | start_date |  end_date  | subtitle |   organisation    |         role         | area  |  area_kind   
-----+--------------------+------------+------------+----------+-------------------+----------------------+-------+--------------
 360 | Adelina Ndeto Mwau |            | 2013-03-04 |          | REPUBLIC OF KENYA | Member of Parliament | Kaiti | Constituency
(1 row)
```

----
via 
```sql
SELECT mp.id, mp.legal_name, p.start_date, p.end_date, p.subtitle, o.name AS organisation, t.name AS role, a.name AS area, pk.name AS area_kind
  FROM core_person mp
  LEFT JOIN core_position p ON mp.id = p.person_id
  LEFT JOIN core_positiontitle t ON p.title_id = t.id
  LEFT JOIN core_place a ON a.id = p.place_id
  LEFT JOIN core_placekind pk ON a.kind_id = pk.id
  LEFT JOIN core_organisation o ON p.organisation_id = o.id
 WHERE t.id IN (1, 851, 849) 
   AND p.start_date = ''
 ORDER BY t.name, p.subtitle, p.start_date, mp.legal_name;
```

**Comment by tmtmtmtm** [comment]
@JessMusila Adelina Ndeto Mwau (http://info.mzalendo.com/person/adelina-mwau/experience/) is currently listed as having been the MP for Kaiti from an unknown date until 2013-03-04. This is the only Parliamentary membership on the site that doesn't have a start date.

But from what I can tell, Gideon Ndambuki was actually the MP for Kaiti at that time. Do you know what this should be set to?

In trying to find out what the start date should be set to, I'

**Comment by JessMusila** [comment]
@tmtmtmtm We have deleted the entry. She was a nominated Member of Parliament and never an elected one. She hails from Kaiti constituency though.

**Comment by tmtmtmtm** [comment]
Thanks, @JessMusila.
