### ISSUE TITLE
NG: Senators with wrong Area type

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1979]
The following Senators have legislative memberships with an Area that isn't a Senatorial District:

```
 id  |     legal_name      |   organisation    |  role   |     area     |      area_kind       | start_date |  end_date  
-----+---------------------+-------------------+---------+--------------+----------------------+------------+------------
 199 | GUMBA ADAMU IBRAHIM | National Assembly | Senator | Abuja        | Other                |            | 2010-00-00
 201 | GWARZO BELLO HAYATU | National Assembly | Senator | Abuja        | Other                | 1999-00-00 | 2007-00-00
 233 | NINGI AHMED ABDUL   | National Assembly | Senator | Abuja        | Other                | 1999-00-00 | 2011-00-00
 147 | DAHIRU UMARU        | National Assembly | Senator | Abuja        | Other                | 2003-00-00 | 2007-00-00
 273 | EKWEREMADU IKE      | National Assembly | Senator | Abuja        | Other                | 2003-00-00 | 2011-00-00
  88 | ANYANWU CHRIS N. D  | National Assembly | Senator | Abuja        | Other                | 2007-00-00 | 2011-00-00
  85 | SANI AHMAD RUFAI    | National Assembly | Senator | Abuja        | Other                | 2007-00-00 | 2011-00-00
 441 | USMAN NENADI ESTHER | Senate            | Senator | Kaduna South | Federal Constituency | 2011-05-29 | 2015-05-29
 289 | MAKARFI AHMED M     | Senate            | Senator | Kaduna North | Federal Constituency | 2012-01-31 | 2015-05-29
(9 rows)
```

via:
```sql
SELECT mp.id, mp.legal_name, o.name AS organisation, t.name AS role, a.name AS area, pk.name AS area_kind, p.start_date, p.end_date
  FROM core_person mp
  LEFT JOIN core_position p ON mp.id = p.person_id
  LEFT JOIN core_positiontitle t ON p.title_id = t.id
  LEFT JOIN core_place a ON a.id = p.place_id
  LEFT JOIN core_placekind pk ON a.kind_id = pk.id
  LEFT JOIN core_organisation o ON p.organisation_id = o.id
 WHERE t.name = 'Senator' 
   AND pk.name != 'Senatorial District'
 ORDER BY t.name, p.subtitle, p.start_date, mp.legal_name;
```

**Comment by mhl** [comment]
We thought these are probably best fixed in the admin interface rather than programmatically, although we can use the query as an automatic check for regressions.

**Comment by tmtmtmtm** [comment]
All three of these (Abuja, Kaduna South, and Kaduna North) are both Senatorial Districts _and_ Federal Constituencies. 

@mhl: Is the correct approach here to have separate Areas — i.e. Kaduna South (Senatorial District) and Kaduna South (Federal Constituency) — or do we have a way of saying that an area can be both?

**Comment by mhl** [comment]
We have to have separate areas, i.e. Kaduna South (Senatorial District) and Kaduna South (Federal Constituency) or lots of things could go wrong. Each place that represents a boundary should have a foreign key to the MapIt area, and these have different MapIt areas (and different boundaries):

* http://www.shineyoureye.org/mapit/area/439.html
* http://www.shineyoureye.org/mapit/area/863.html

**Comment by JenMysoc** [comment]
Done

**Comment by tmtmtmtm** [comment]
Thanks @JenMysoc. Some of these have now moved to being of the same problem as in https://github.com/mysociety/pombola/issues/2036, as the Area is for the wrong _date_, but that's still an improvement on it being the wrong type of area entirely!
