### ISSUE TITLE
ZA: update / remove old South Africa data import docs

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#1980]
@chrismytton pointed out that this is now out-of-date:

https://github.com/mysociety/pombola/blob/sayit-upgrade-part-1/docs/south_africa.md#reparsing-hansard

The initial data import steps are no longer relevant, so we should remove them, and the scraping and parsing steps should be update.

**Comment by duncanparkes** [comment]
It looks to me as though what's needed in this section is just to remove the popit_resolver_init, but I'm not certain, so I'd rather leave this to @mhl

**Comment by mhl** [comment]
Fixed in 2217565e2386f and 1f74166e8b3f1
