### ISSUE TITLE
Split out ShineYourEye mapit to separate subdomain

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#1982]
Move the [ShineYourEye Mapit](http://www.shineyoureye.org/mapit/) onto its own subdomain, probably mapit.shineyoureye.org, and run it as a standalone vhost.

**Comment by chrismytton** [comment]
This will need to be done before fully switching over to the new Pombola Simple version (https://github.com/mysociety/pombola/issues/1914).

**Comment by mhl** [comment]
It's perhaps worth noting there that there are some bits of Pombola that use the MapIt models directly in a way that doesn't have a correspondence in the HTTP-based API, e.g. finding the area of overlap of intersecting areas:

https://github.com/mysociety/pombola/blob/master/pombola/core/models.py#L835-L916

I don't think this will affect the functionality you want to keep for ShineYourEye-in-Pombola-Simple, though.

**Comment by chrismytton** [comment]
@mhl Would it be possible to just switch to using global mapit rather than install the SYE mapit separately? Or is there stuff in SYE mapit that isn't in global mapit?

**Comment by davewhiteland** [comment]
For clarification and removal of doubt in the discussion that might follow: global mapit != international mapit. Global MapIt is useful if the boundaries you're using are in OpenStreetMap; International Mapit is the one the International Team used for custom geometries on a per-project basis (e.g., OSM didn't have the boundaries needed for Trinidad & Tobago, so we drew our own, and added them to International MapIt.

**Comment by mhl** [comment]
@chrismytton The SYE MapIt uses boundaries from http://gadm.org, which seem to be complete - that's not the case with the OSM boundary data for Nigeria, so it's best to stick with the GADM data in the ShineYourEye MapIt. It's also had lots of additional names added to the areas to help identify them - lots of them have wide variations in orthography in practice.

international.mapit, which @davewhiteland mentioned, would be a good place to import the data to, but it's fine to create a new MapIt instance (nigeria.mapit.mysociety.org) too.

**Comment by chrismytton** [comment]
Done as a separate vhost for now - http://nigeria.mapit.mysociety.org/area/66

It can potentially be added to international mapit at some point in the future.
