### ISSUE TITLE
KE: Misleading "No experience" claim

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1983]
On, for example http://info.mzalendo.com/person/adelina-mwau/, we say under Experience "No records found.":

![screen shot 2016-02-23 at 13 47 26](https://cloud.githubusercontent.com/assets/57483/13253546/8167d51e-da34-11e5-9219-1e800a151021.png)

This is quite odd, as we do actually know quite a lot about their Experience:

![screen shot 2016-02-23 at 13 48 06](https://cloud.githubusercontent.com/assets/57483/13253556/8b436cd8-da34-11e5-84e6-e2a87e03eaf5.png)
 

If the issue is that this section is only for *current* information, then we should say so explicitly (e.g. "No current positions known"), though it would be even better if we could include the most important historic position(s) here.

**Comment by mhl** [comment]
At estimation we suggested half a day, timeboxed, to work on making this less confusing.

**Comment by tmtmtmtm** [comment]
We made the simple fix to this in #2057 — working out what we should say instead when there are no current memberships (we should probably still highlight something here) can be done as part of to #2019
