### ISSUE TITLE
In /admin/core/person/ Positions should be grouped and ordered

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#1990]
When a Person has a lot of Positions it's quite hard to scan through them all:

![screen shot 2016-02-23 at 15 46 01](https://cloud.githubusercontent.com/assets/57483/13256999/ee04bd6c-da44-11e5-9c68-861d738e58bc.png)

I would suggest grouping them by category (political, educational, etc), and then sorting within those by most recent start date.

**Comment by mhl** [comment]
It would be nice to also highlight legislative positions.

**Comment by mhl** [comment]
We suggested at estimation time that this be timeboxed to a day - just see how much could be improved in that time.

**Comment by duncanparkes** [comment]
Closing in favour of #2116.
