### ISSUE TITLE
Mzalendo - Infographics, can they be shown on the infographics page?

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#2006]
Currently it is just a list of links

![screenshot 2016-02-24 10 51 33](https://cloud.githubusercontent.com/assets/909811/13283207/974a073e-dae4-11e5-8869-6c34442f3d34.png)

**Comment by tmtmtmtm** [comment]
Does this require any new functionality, or is it just a matter of someone embedding images into the text?

**Comment by mhl** [comment]
This is a manually edited info page at the moment, so someone could convert the PDFs to a bitmap, upload that image, and include each on this page.

Alternatively, we could turn this into a dynamic page, using the "feature image" of an info page for each infographic, as we do to extract the infographics for the front page of PA.

(The difficulty estimate on this ticket is if we do the latter approach.)

**Comment by tmtmtmtm** [comment]
@paullenz I don't believe it's worth adding any new functionality here. I'd suggest someone just manually add images to the page.
