### ISSUE TITLE
"current_user_id: 0" leaking out

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#2015]
At the bottom of pages like http://za-pombola.staging.mysociety.org/hansard/2012/february/28/proceedings-of-the-national-assembly-tuesday-28-fe/impact-of-deterioration-of-natural-environment-on there's text shows `current_user_id`. I'm assuming this is debugging text that leaked out?

![screen shot 2016-02-24 at 14 56 33](https://cloud.githubusercontent.com/assets/57483/13289199/116ea840-db07-11e5-91f0-8406fe1c5ff5.png)

**Comment by dracos** [comment]
It only displays on a staging site.

**Comment by tmtmtmtm** [comment]
Ah, yes. I just followed the link from another ticket, and hadn't even noticed it was to staging…
