### ISSUE TITLE
document (and figure out) how best to use the public database dumps

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2029]
The rough procedure for using, say, the South Africa database dump would be:

```
wget 'http://www.pa.org.za/media_root/dumps/pg-dump.sql.gz'
```

Create a new database:

```
createdb za-pombola
echo 'CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology' | psql za-pombola
zcat pg-dump.sql.gz | psql za-pombola
```

This database's django_migrations table will be populated, but not all the tables will exist, because we've dropped those that contain personal data. If you remove all the migrations, and run migrate with --fake-initial (on Django 1.8 or just migrate on Django 1.7) then only the first migration for each app will be successfully faked.

Perhaps one way around this is to do the following steps:

* Make sure that if we don't include a table, we don't include any tables from its app (that'd mean missing out on some data, e.g. experiments_experiment, everything in votematch except votematch_submissions, etc.)
* Manually remove from the django_migrations table those migrations referencing those apps (e.g. easy_thumbnails, auth, experiments
* Run `./manage.py migrate`

This seems to work, but doesn't seem like an ideal solution. In absence of a better suggestion we should document this in place of the very out-of-date information in `docs/south_africa.md`.

**Comment by mhl** [comment]
Rather than removing entries from the `django_migrations` table, another option might be to have a settings module that sets the `MIGRATION_MODULES` dictionary to specify `None` for the apps that need to be recreated, see: https://docs.djangoproject.com/en/1.9/ref/settings/#migration-modules - so the old syncdb behaviour will run.

That's Django 1.9 only, but there' s a suggestion in this question that just using a non-existent module does the same? http://stackoverflow.com/questions/31831001/make-migration-conditional-in-django

**Comment by mhl** [comment]
@jennyd suggested a much better way of doing this: we could do two database dumps, the first with the `--schema-only` option and not restricting tables; the second with `--data-only` and only including the safe tables.

**Comment by mhl** [comment]
This seems to work well when I tried it manually just now - to dump the schema, the script should do something like:

```
pg_dump --schema-only --no-owner --no-acl -h dassie.ukcod.org.uk -U mzalendo-za-production mzalendo-za-production > just-schema.sql
```

(although that should also have included `-T layer -T topology` to exclude the PostGIS tables that should already have been created...)

Then dump the data with something like:

```
pg_dump --data-only --no-owner --no-acl -t budgets_budget -t budgets_budgetsession -t core_alternativepersonname -t core_contact -t core_contactkind -t core_identifier -t core_informationsource -t core_organisation -t core_organisationkind -t core_organisationrelationship -t core_organisationrelationshipkind -t core_parliamentarysession -t core_person -t core_place -t core_placekind -t core_position -t core_positiontitle -t core_slugredirect -t django_content_type -t django_migrations -t django_site -t easy_thumbnails_source -t easy_thumbnails_thumbnail -t easy_thumbnails_thumbnaildimensions -t experiments_experiment -t file_archive_file -t images_image -t info_category -t info_infopage -t info_infopage_categories -t info_infopage_tags -t info_tag -t info_viewcount -t instances_instance -t instances_instance_users -t interests_register_category -t interests_register_entry -t interests_register_entrylineitem -t interests_register_release -t mapit_area -t mapit_code -t mapit_codetype -t mapit_country -t mapit_generation -t mapit_geometry -t mapit_name -t mapit_nametype -t mapit_postcode -t mapit_postcode_areas -t mapit_type -t pombola_sayit_pombolasayitjoin -t popit_apiinstance -t popit_person -t popolo_contactdetail -t popolo_identifier -t popolo_link -t popolo_membership -t popolo_organization -t popolo_othername -t popolo_person -t popolo_post -t popolo_source -t scorecards_category -t scorecards_entry -t slug_helpers_slugredirect -t south_migrationhistory -t speeches_recording -t speeches_recordingtimestamp -t speeches_section -t speeches_slug -t speeches_speaker -t speeches_speech -t speeches_speech_tags -t speeches_tag -t spinner_imagecontent -t spinner_quotecontent -t spinner_slide -t tasks_task -t tasks_taskcategory -t za_hansard_answer -t za_hansard_pmgcommitteeappearance -t za_hansard_pmgcommitteereport -t za_hansard_question -t za_hansard_questionpaper -t za_hansard_source -h dassie.ukcod.org.uk -U mzalendo-za-production mzalendo-za-production > just-data.sql
```

That outputs some warnings about tables with circular references, e.g.:

```
pg_dump: NOTICE: there are circular foreign-key constraints among these table(s):
pg_dump:   core_place
pg_dump: You may not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
```

In practice, I could restore this dump without errors despite the circular foreign-key restraints (e.g. the parent relationship on core_place) - the order of data in these tables just happens to be in the right order such that there are no such errors. (It would be good to avoid having to use the `--disable-triggers` option, since then the restore of that data will have to be done by a PostgreSQL superuser.)

Anyway, this seems like the best approach so far - we should update the `core_database_dump` script and cron job to generate both of these database dumps and then update `bin/install-as-user` to use them.

**Comment by tmtmtmtm** [comment]
NB: 'gunzip -c' will be more portable than 'zcat' here

(See, for example, discussion at https://github.com/dalibo/pgbadger/issues/70)

**Comment by mhl** [comment]
There's a PR that deals with this here: https://github.com/mysociety/pombola/pull/2119
