### ISSUE TITLE
[ZA] Separate out MPs and MPLs for the new Ward Rep Locator page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2107]
We need to separate out the MPs from the MPLs (eg: MPs in the left column, MPLs in the right column) and include the paragraph of text we discussed at the beginning, explaining what each type of person is for and when you should contact them.

Currently it looks like this:
![screen shot 2016-03-10 at 09 54 43](https://cloud.githubusercontent.com/assets/4170351/13665842/3c123076-e6a6-11e5-9b72-a5c2289ee14e.png)

But I think they would prefer to revert to the first design Zarino did which looks more like this:

![screen shot 2016-03-10 at 09 55 54](https://cloud.githubusercontent.com/assets/4170351/13665891/8c598782-e6a6-11e5-9954-03171e7e299e.png)

**Comment by duncanparkes** [comment]
Fixed in c3a53d8
