### ISSUE TITLE
[ZA] Change the way information is displayed in the Ward Rep Locator results page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2114]
The information shown on the ward rep locator results page should look like this:

> Juliana Danielle Killian (ANC) 
> Member at National Assembly
> ANC Constituency Office (621): Salt River Regional Office
> 358 Victoria Road, Salt River, 7925, South Africa (1.7 km away)

The name of the rep should be in a slightly smaller font than the rest of the information and should link to the person page for that person.
The name of the constituency office and area should link to the details for that office.

**Comment by zarino** [comment]
Done in https://github.com/mysociety/pombola/commit/c45de0155ad123bf7b80c78237c70f61b82d7275
