### ISSUE TITLE
KE: investigate why John Bomet Serut's party appears wrong in EveryPolitician

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2133]
The scraper is inferring that he's of party "Independent Aspirant", which is clearly
wrong.

**Comment by tmtmtmtm** [comment]
![screen shot 2016-04-14 at 07 49 32](https://cloud.githubusercontent.com/assets/57483/14519243/80ebd1fe-0215-11e6-80f4-6515b2ee7d4a.png)

**Comment by tmtmtmtm** [comment]
@mhl did you ever investigate this? It would be nice to get this fixed up in EP

**Comment by mhl** [comment]
I've fixed it in Mzalendo now - he does seem to have been Independent since 2013 according to https://en.wikipedia.org/wiki/Mt._Elgon_Constituency so I think this must have been someone accidentally selecting "Independent Aspirant" instead of "Independent" from the drop-down.

**Comment by tmtmtmtm** [comment]
Excellent. Thanks @mhl

**Comment by tmtmtmtm** [comment]
That has flowed through to EP now: https://github.com/everypolitician/everypolitician-data/pull/15602/files
