### ISSUE TITLE
[KE] Changing the information displayed on Party Pages

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2145]
When speaking to Jessica, we found out that Parties in Kenya tend to be short lived and very changable. To get the most use out of the party pages on Mzalendo Jess has suggested showing the following information on the page:

a) the day they were formed
b) the date they ceased to exist. 
c) If they were established following a merger between several parties & the date that happened; 
d)If they emerged as a splinter from another party. If so which one and the date. 

Party pages should also show: details of the founder, party leaders, members and coalitions they are part of.

**Comment by tmtmtmtm** [comment]
Is this expected to be structured data in some way? Or is this just a text box that she can fill in herself?

**Comment by JenMysoc** [comment]
This is just text, not anything structured

**Comment by mhl** [comment]
@JenMysoc That's already possible, by editing the "summary" field for the Organisation in the admin interface. For example, someone's done this for Ford Kenya, and it's displayed when you go to the party page:

http://info.mzalendo.com/organisation/ford-kenya/

Is there something else we should be doing for this issue?

**Comment by JenMysoc** [comment]
Nope nothing else :) Jessica has said she can edit the party pages!
