### ISSUE TITLE
[KE] Homepage redesign for the elections in 2017

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2146]
Quick notes:

* Mzalendo is going to be a thought-leader around the 2017 elections, providing facts, voting advice, and opinion pieces.
* The homepage needs to give visitors a key overview of Mzalendo’s election coverage.
   * Not sure what content Jessica wants on the homepage – @zarino to discuss with Jessica.
* Mzalendo has a reputation for the strong research it does – eg the People’s Shujaaz and Women Reps features – so these need to remain prominent. Elections could be treated as just another feature (albeit a *current*, unfolding one).
* There will also be a new Election section for the site, so a link to that will need to be added to the nav bar, and the Senators/NA Members links can be combined into one, to make space.

Background info: https://wiki.mysociety.org/wiki/Mzalendo#April_2016

**Comment by zarino** [comment]
It sounds like the requirements for the homepage are that there should be a section dedicated to the election coverage, containing the 2 or 3 most recent blog posts about the election, plus a space to push key voter actions like "Did you know you can still register to vote?" or, I expect eventually, "Where can I vote?"

Visually, I think it comes down to how big a deal @JessMusila wants to make about Mzalendo’s elections coverage.

If we're worried about taking up too much space, or we don't want to distract too much from the rest of the content on the homepage, then a simple approach like this might be best:

![option 1](https://cloud.githubusercontent.com/assets/739624/15012614/0989798a-11f2-11e6-9185-737291ad0641.png)

Here, election coverage is handled just like the other "Special features" – which means the picture of parliament and the rest of the sidebar is kept relatively high on the page. People will have to scroll down a bit further to get to the blog posts and twitter feed, but I think that's unavoidable if we're going to add anything substantial to the homepage.

To me, personally, however, it feels like a lost opportunity to do something really BIG on the homepage. This is a year when Mzalendo could really shine, and position itself as *the* place for Kenyan election coverage. With that in mind, you could split the election coverage out into its own section, right at the top of the homepage:

![option 2](https://cloud.githubusercontent.com/assets/739624/15012670/8d2d2b7e-11f2-11e6-982e-d3e041a14f6f.png)

Now that we have more room, the blog posts can be treated just like the standard blog, with nice big titles and text previews. And there's space on the left—in that top-left sweet spot that *everybody looks at* when they land on the homepage—for a big message like "Have you registered to vote?" etc.

The down-side is that all the normal homepage content gets pushed down. Although it doesn't make a *huge* difference on desktop screens, visitors on mobiles will probably have to scroll at least one whole screen down, to get to the normal homepage content outside of the yellow Elections banner.

Would love to hear your thoughts, @JessMusila @JenMysoc.

**Comment by JessMusila** [comment]
@JenMysoc @zarino 
Thanks for these mock-ups. We prefer the second option with some edits. Mzalendo has emerged as thought leader in the Kenyan political space. As a result we want to make changes to the home page. 

Our comments follow each with an explanation of what informs the change proposed:
i)We would like to change the tabs on the menu bar.  Combine NA members and Senators into one drop menu called 'MPs'. 

ii) For now create a tab called 'Research'. Drop the 'Women MPs survey' and 'People Shujaaz' to the 'Research' tab. They don't need to be displayed on the homepage anymore. Move 'People's Shujaaz' from public participation tab.

iii)We do not want to have a dedicated tab to the elections yet. That will come at a later date. For now let the 'Elections 2017' will be nestled under 'Research' tab too.

iv) Now to the design. We prefer the second option. How about you inter-change the layout order? Have the normal content section above the election content with clear differentiation. 

Alternatively, is the space that had the 'special features' before is large enough to hold the elections info and keep the rest of the content as it is?

We remain open to any suggestions you may make.

Regards,

**Comment by JenMysoc** [comment]
Thanks @JessMusila 

Those edits to the menu bar sound simple to do and we can do that no matter which design you decide on. 

From point iv on the second design it sounds like you want the elections in focus section to be at the bottom of the page just before the footer? My concern with this is it will fall "below the fold" meaning that people won't immediately see it as they would need to scroll through the whole home page. 

This
> Alternatively, is the space that had the 'special features' before is large enough to hold the elections info and keep the rest of the content as it is?

Sounds like the first design option might actually work better for you if we remove the Women MPs Survey and People's Shujazz off the front page? That way the special features section can just be able the elections?

I do personally really like the second design - it's really eye catching and would encourage me to think more about what was going on in the Kenyan elections. Are you thinking it's too early for that much elections exposure?

**Comment by JessMusila** [comment]
Hey Zarino,

Apologies for the delayed response, I have been swamped with work. Go ahead
and fit the first design option in the Special features section. Then share
the mock up with us so we can get our trustees opinion.

Kindly edit the sentence above the Register to Vote button to read: "You
can *still* register to vote at your local IEBC office until February
2017." The word - still - is in bold for emphasis, people think the voter
registration exercise is over.

Regards.

Jessica

*Jessica *
*Musila, Executive Director, Mzalendo Trust, P. O. Box 21765 00505 Ngong
Road, Nairobi, Tel. 0726464063Email: jessica@mzalendo.com
<jessica@mzalendo.com>, Skype: Jessica.Musila, Twitter: Africanvigil,
www.mzalendo.com <http://www.mzalendo.com>*
