### ISSUE TITLE
Get TLS certificates for Mzalendo and People's Assembly

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2165]
Nowadays you get a small boost in pagerank for serving sites over HTTPS by default, and it's good practice in any case. We should get certificates for Mzalendo and People's Assembly using letsencrypt, since it's easy and free.

**Comment by chrismytton** [comment]
People's Assembly has been served over HTTPS since June 2017: https://www.pa.org.za/

**Comment by sagepe** [comment]
Mzalendo now uses HTTPS. There are a handful of mixed content warnings and HTTP links left to fix, but I think this ticket is done.
