### ISSUE TITLE
update the People's Assembly homepage

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2170]
As background, PMG got some advice from a social media/digital marketing company that said that:

> the mandate of the PA website should be
> clearer and more prominent on the homepage. The green band should be solely
> about connecting with your rep and that is why the message should be
> centered and the levels of representation should be included (See attached).

A summary of the changes they've asked for is:

> 1) Center the Rep Locator text on the green band and insert 'At local,
> provincial and national level' underneath 'Contact your representative'. The
> copy can be bigger across the green band.
> 2) The email sign-up should be an icon next to the Facebook icon at the top
> of the page (see rough idea on the attached screenshot). It should be
> similar in size and colour of the Facebook and twitter icons.
> 3) Remove the 'Subscribe' link at the top of the page (circled in red),
> because it links to an outdated sign-up page for the PMG newsletter.

The mock-up they sent us was:

![homepage](https://cloud.githubusercontent.com/assets/7907/15832205/070f9eb4-2c19-11e6-8ce6-60695a9f3778.jpg)

(I think I misunderstood this request initially; in an earlier email it sounded as if there were two main calls-to-action: enter your address to find your representative, and "subscribe" to their Facebook feed, but I realise they meant the "subscribe" link should still refer to the email sign-up, and there's one main call-to-action: enter you address to find your representative.)

If there's more than one idea from the design team about how to implement this, I think this would be a great case for A/B testing, since there's a clear and easily measurable outcome we're looking for.

**Comment by JenMysoc** [comment]
PMG would like not to have A/B testing on this change this time so if we can just make the changes and save A/B testing for another time that would be great.

**Comment by mhl** [comment]
I've dealt with the requests in points 1 and 3. I haven't added an icon (or alternative representation) of email sign-up; that'll be something that @wrightmartin or @zarino can look at in this sprint.

As before, the design is different depending on the height of the user's window so that some of the infographics are always visible, so here are the full, medium and small height window variants:

### Full

![full](https://cloud.githubusercontent.com/assets/7907/15897974/6204c1b6-2d8e-11e6-95b4-792fdbbe8775.png)

### Medium

![mid](https://cloud.githubusercontent.com/assets/7907/15897978/65f4e0f8-2d8e-11e6-9321-3d7db4c9d192.png)

### Small

![small](https://cloud.githubusercontent.com/assets/7907/15897986/6ce4c4b4-2d8e-11e6-8510-89bed443705f.png)

I'm also confused by the mailing list request. What is the mailing list sign-up that the new "subscribe" icon should link to?

Currently, the Subscribe link goes to http://www.pa.org.za/info/newsletter - the sign-up on that page is to http://www.graphicmail.co.za/ which is the same sign-up as in the footer. Is that the PMG MONITOR email, which they seem to be deprecating, or it the live mailing list?

**Comment by JenMysoc** [comment]
Thank you for doing this Mark! Is this change live so I can point them to it?

I will double check on the mailing list - I was unaware they had two - and let you know!

**Comment by mhl** [comment]
@JenMysoc They might be the same! I wasn't involved in the setup of that at all.

The changes I mentioned / screenshotted are live, yes.

**Comment by zarino** [comment]
@JenMysoc – did you get an answer on which URL the email newsletter icon should link to?

**Comment by zarino** [comment]
PS. Here's a branch with the new icon, and a tidied up central section for the homepage:

https://github.com/mysociety/pombola/compare/2170-za-homepage-tweaks

**Comment by JenMysoc** [comment]
@zarino Thanks! It should point to the People's Assembly newsletter sign up which is http://www.pa.org.za/info/newsletter :)

**Comment by zarino** [comment]
@markl @JenMysoc – Pull request here: https://github.com/mysociety/pombola/pull/2173
