### ISSUE TITLE
[KE] Menu items not collapsing on blog pages

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2200]
![screen shot 2016-09-30 at 10 15 15](https://cloud.githubusercontent.com/assets/4170351/18987029/9520d61c-86f7-11e6-9953-5c2b84d653fd.png)

This is only happening on the blog page on Mzalendo - I've checked the other pages and they are all displaying fine! Not sure what could be causing this but if it could be fixed as a matter of urgency that would be excellent!

**Comment by zarino** [comment]
The HTML of the menu on `http://info.mzalendo.com` (left) is completely different to the HTML of the menu on  `http://www.mzalendo.com/blog` (right).

![screen shot 2016-09-30 at 12 33 05](https://cloud.githubusercontent.com/assets/739624/18990485/13400736-870a-11e6-855d-3807457011bb.png)

But the CSS styles are the same. Therefore, the CSS isn't applying properly to the `/blog` markup, causing everything to look broken.

I'm assuming the markup for both sites should be in sync. Sounds like something for @mhl to look into.

**Comment by mhl** [comment]
It's confusing, but the blog is actually a Wordpress install that we host, and the theme for it is in the orgsites repository:

* https://github.com/mysociety/orgsites/blob/master/blogs/themes/mzalendo/header.php
* https://github.com/mysociety/orgsites/blob/master/blogs/themes/mzalendo/footer.php

Sorry, I should have remembered this when reviewing your menu changes...

**Comment by zarino** [comment]
@mhl – I wonder whether we could automate this somehow, so that deploying the orgsites project scrapes the menu off the live mzalendo site, and dumps it into a `.php` file for the theme to import? It seems ridiculous for us to maintain the menu structure in two separate repos.
