### ISSUE TITLE
Vagrantfile: tests don't run out of the box

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2202]
@jacksonj04 pointed out that the tests don't run out-of-the-box because the test database has to be created with the PostGIS extension and by default you need to be a superuser to do that: https://gist.github.com/jacksonj04/0bc566748ef2a1d9a3e4bc5b7095c1be

**Comment by mhl** [comment]
@jacksonj04 What was the distribution of the base box you were using?

The PostgreSQL user should be created as a superuser on trusty:

https://github.com/mysociety/pombola/blob/master/bin/site-specific-install.sh#L47-L55
https://github.com/mysociety/commonlib/blob/master/bin/install-site.sh#L236-L239

... which the Vagrantfile [uses by default](https://github.com/mysociety/pombola/blob/master/conf/Vagrantfile.example#L4).

**Comment by chrismytton** [comment]
This no longer seems to be an issue.
