### ISSUE TITLE
[ZA] Add Ministers filter to MP attendance page

### ISSUE THREAD

**Issue by xybrnet** [mysociety/pombola#2239]
An additional dropdown is required on http://www.pa.org.za/mp-attendance/ so that the list of member's attendance can be filtered to only show Ministers.

**Comment by mhl** [comment]
Is it OK to close this now, @xybrnet?

**Comment by xybrnet** [comment]
@mhl - Yes, it is. I was not sure what the process is. For the future, should I close the issues I create?

**Comment by mhl** [comment]
It's fine either way, I was just double-checking :)
