### ISSUE TITLE
[ZA] A/B test moving the MP profiles button to the top of the page on mobile

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2250]
PMG have asked us to make the links to the MP profiles page from the homepage, which are currently on the red buttons (shown here on the full sized website), more prominent when you visit the site on mobile.

![screen shot 2017-02-28 at 12 04 24](https://cloud.githubusercontent.com/assets/4170351/23404776/a9c3addc-fdae-11e6-94bd-c9b3e5263a6b.png)

On a mobile view you need to scroll very far down the homepage to see the buttons and the links are otherwise not obvious.

We have suggested A/B testing moving these buttons to the top of the site on mobile - which PMG are supportive of. 

We need to:

- Find a way to move the Homepage red buttons only on mobile (or mobile width browsers - whatever is simplest?)
- Show this change to only 50% of users using mobile
- Track the mobile users on analytics and see whether the change has resulted in more users clicking on the MP Profiles page: currently only 2.08% of mobile users from ZA find their way to the MP profiles page at http://www.pa.org.za/position/member/parliament/?order=name&a=1

**Comment by zarino** [comment]
Seems simplest to use Google Analytics Experiments for this: https://developers.google.com/analytics/solutions/experiments-feature-reference

Background tasks we’ll need to do:

- [ ] Google Analytics event tracking for clicks on the MP Profiles button
- [ ] Set up an experiment with two variations in Google Analytics

On page load we’ll want to:

- [ ] Load the [Content Experiments API](https://developers.google.com/analytics/devguides/collection/analyticsjs/experiments) on pa.org.za
- [ ] If the screen is small (maybe look for presence of mobile nav UI as a signal for this?) choose a variation with `cxApi.chooseVariation()`.
- [ ] If user is assigned the variant, move the buttons to the top of the page with `$('.home__topics').insertBefore('.home__news')`
- [ ] Profit.

**Comment by zarino** [comment]
Started in branch [2250-za-homepage-button-experiment](https://github.com/mysociety/pombola/compare/master...2250-za-homepage-button-experiment)

**Comment by zarino** [comment]
We completed the test! 

Moving the buttons up increased visits to "MP Profiles" page. But we should _now_ test whether having all 5 buttons at the top of the page has any negative impact on overall homepage engagement.

![screen shot 2017-05-18 at 09 36 25](https://cloud.githubusercontent.com/assets/739624/26241576/0eb5c5ce-3c7d-11e7-8b87-6ca7a92ee4be.png)

Plain English summary: Of mobile visitors shown the "hot topics" buttons at the bottom of the homepage, only 10% clicked on the "MP Profiles" button (2 out of 19 visitors); Of mobile visitors shown the "hot topics" buttons at the _top_ of the homepage, 35% clicked on the "MP Profiles" button (16 out of 46 visitors)

**Comment by JenMysoc** [comment]
this has been done!
