### ISSUE TITLE
Vagrant issues

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2261]
Running Vagrant 1.8.6 on Mac OS 10.10.4 I had some issues getting the vagrant vm running.

The provisioning scripts were failing because DNS wasn't working inside the box, resulting in lots of errors like:

```
==> default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'
```

I fixed this by changing this line of the Vagrantfile…

```ruby
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
```

To this…

```ruby
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
```

I had another issue where the `git submodule --quiet update --recursive` in `install-site.sh` was failing:

```
==> default: Submodule 'commonlib' (git://git.mysociety.org/commonlib) registered for path 'commonlib'
==> default: Cloning into 'commonlib'...
==> default: fatal: read error: Connection reset by peer
==> default: fatal: early EOF
==> default: fatal: index-pack failed
==> default: Clone of 'git://git.mysociety.org/commonlib' into submodule path 'commonlib' failed
```

I couldn't work out why – but when I `vagrant ssh`-ed in, and ran the install script manually, it worked…

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo xargs -0 ./install-site.sh < install-arguments
```

I also noticed that the "helpful" instructions printed at the end of provisioning don't actually work – they're missing the `. ../pombola-virtualenv/bin activate` step.

**Comment by zarino** [comment]
@dracos notes that he had to perform a similar DNS fix in mapit recently: https://github.com/mysociety/mapit.mysociety.org/commit/78dd3981c3134f7952f9460c8dbbdd16ea9428da

**Comment by zarino** [comment]
I’ve done a bit more investigation into this, and there are two settings that will "enable" DNS inside VMs on my Mac:

```
vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
```

```
vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
```

The presence of _either_ of these will prevent the DNS issues I was having before. And on/off combinations of the two will work as long as _either_ `natdnshostresolver1` is `on`, or `natdnsproxy1` is `off`.

I'm not sure *why* this has only now become an issue. And I'm not sure whether it’s only _me_ that’s affected. But for now, I’ve just created a default `Vagrantfile` at `~/.vagrant.d/Vagrantfile` on my Mac, which contains the fix:

```
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end
end
```

The settings in `~/.vagrant.d/Vagrantfile` get applied _before_ settings from the project-specific `Vagrantfile` – so my fix will work as long as projects don’t actively set `natdnsproxy1` to `on` in their own `Vagrantfile`.

**Comment by chrismytton** [comment]
The vagrant bits were completely rewritten as part of https://github.com/mysociety/pombola/pull/2605. Please open a new issue if you're still seeing problems.
