### ISSUE TITLE
[ZA] Replace Democracy Resources with MP profiles on Menu bar

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2267]
![screen shot 2016-08-02 at 15 20 37](https://cloud.githubusercontent.com/assets/4170351/24950160/fb498138-1f67-11e7-99fc-1b1b015c9c61.png)

PMG would like to replace Democracy Resources on the Menu bar with the link to MP Profiles from the Hot Topics section.

Democracy resources and all the pages contained under that dropdown should be moved to the Hot Topics section of the menu bar. 

If possible PMG would like Democracy Resources to be the main link on the Hot Topics section and all the links underneath to be submenus

The linked pages under democracy resources are: 
http://www.pa.org.za/info/democracy-resources
http://www.pa.org.za/question/
https://pmg.org.za/bills/
https://pmg.org.za/committees/
http://www.pa.org.za/hansard <- remove this from list

http://www.pa.org.za/blog/category/advocacy-campaigns <- add this to list!

PMG would like to remove the hansard link completely and adding Campaigns from further down the Hot Topics menu into the submenu under the "democracy resources" heading

**Comment by jacksonj04** [comment]
* [ ] Democracy resources and all the pages contained under that dropdown should be moved to the Hot Topics section of the menu bar.
* [ ] Democracy Resources should be the main link on the Hot Topics section and all the links underneath to be submenus:
  The linked pages under democracy resources are:
  http://www.pa.org.za/info/democracy-resources
  http://www.pa.org.za/question/
  https://pmg.org.za/bills/
  https://pmg.org.za/committees/
* [ ] Remove http://www.pa.org.za/hansard from list
* [ ] Add http://www.pa.org.za/blog/category/advocacy-campaigns to list
* [ ] Remove the hansard link completely
* [ ] Add Campaigns from further down the Hot Topics menu into the submenu under the "democracy resources" heading
