### ISSUE TITLE
[ZA] Make text more prominent on "Make Yourself Heard" page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2268]
PMG would like to make the call to action on the Make Yourself Heard page more prominent.

![screen shot 2017-04-12 at 10 41 21](https://cloud.githubusercontent.com/assets/4170351/24951646/0806fae0-1f6d-11e7-95e7-05f730603981.png)

The call to action is the text:"  Current Calls for Comment - where you can have you say: click here "

This could be simply by increasing the size of the text but we're also open to other ideas!

**Comment by zarino** [comment]
We could pull it out in a little box, like we do with the other "interactive" bits of the site such as the search filters:

![screen shot 2017-08-16 at 10 03 45](https://user-images.githubusercontent.com/739624/29355790-46d2caf0-826a-11e7-939b-e7d18706452a.png)

Perhaps PMG could come up with some better wording if we go in this direction? Whatever we put in here should probably hint at what a "call for comment" actually is – which isn't really explained anywhere on the page right now.

Feels natural to also follow up with a repeated link after the guidelines, to give people a clear next action after reading the background info:

![screen shot 2017-08-16 at 10 08 05](https://user-images.githubusercontent.com/739624/29356060-eb058dec-826a-11e7-9d74-1396da8e8803.png)

**Comment by zarino** [comment]
Assuming PMG are happy with the design, here’s a pull request that adds the styling to the core stylesheets, and gives an example of the markup you’ll want to add to the Make Yourself Heard page: https://github.com/mysociety/pombola/pull/2299

**Comment by jacksonj04** [comment]
Things to do:

[ ] Merge #2299 
[ ] Get better wording from PMG?
[ ] Update the page!

**Comment by JenMysoc** [comment]
I need to add some things from their feedback to the ticket so don't do this yet!

**Comment by JenMysoc** [comment]
OK comments from PMG:

- [ ] Change ‘Make Yourself Heard’ to 'Have Your Say’ as the title
- [ ] Remove ‘Have your say’ in the shaded box
On this image: https://user-images.githubusercontent.com/739624/29355790-46d2caf0-826a-11e7-939b-e7d18706452a.png

- [ ] Change wording for the whole page to match the below:

> 1.1 Submissions

> It is important for citizens to make themselves heard on matters affecting them, by making submissions to Parliament. The Constitution allows the public to participate in government's decisions in terms of law making, oversight and parliamentary processes.

> When Parliament processes legislation, they will invite the public to comment, which allows citizens to present their views, grievances and suggestions to the relevant parliamentary committee. The submissions are considered by Members of Parliament and the submitter may be called upon to make an oral submission to the Committee during a public hearing.

> Here is a guideline for writing a submission:

> 1. If you're making a submission on behalf of a company or organisation, use a letterhead. If you do not have a letterhead or you are an individual, state clearly at the top (preferably in the right hand corner) who you are and include your address and contact details.
> 2. Head the submission with the name of the committee it is addressed to, what the submission seeks to address – the subject line (this must be very clear), and include the date the submission is being made.
> 3. Give details about your organisation or yourself, stating why the bill is important to you, and how it will affect you or the public.
> 4. This should be followed by a paragraph underlining the problems you have with the bill and your proposed solutions or recommendations. Remember to be constructive in your criticism of the bill.
> 5. Indicate whether you would like the opportunity to make an oral presentation to the committee regarding your submission.

> See this example of a submission from [Healthy Living alliance on the on Health Promotion Levy on Sugar Beverages](https://www.pmg.org.za/files/HEALA.docx)

> 1.2 Visiting Parliament

> The Constitution allows for citizens to attend parliamentary committee meetings and sittings of the National Assembly and National Council of Provinces as long as you have an ID. The public is also allowed to contact Members of Parliament (the elected representatives of the people) to express their views on pertinent matters. Members of Parliament are accountable to you because you voted for them.

> You can find the daily schedule of Committee meetings [here](https://www.pmg.org.za/schedule)

> If you would like to arrange a parliamentary tour, please contact the Tours Administrator on 021 403 2266 or tours@parliament.gov.za

> If you would like to observe a debate in the main chambers, please contact Parliament’s Public Relations Office on 021 403 2197/8 or mtsheole@parliament.gov.za

> 1.3 Taking Parliament to the People

> Taking Parliament to the People is a flagship programme of the NCOP which brings together all three levels of government in one place to meet face to face with locals to identify challenges and find solutions. For two full week every year Members of the NCOP, in partnership with provincial legislatures, invites members of the public to hold public hearings where they can air their grievances around service delivery. The aim is to discuss relevant, pressing issues and to form a plan of action where the problems are addressed. The types of issues that are discussed include matters of housing shortages, water shortages, education, health and social assistance (amongst others).

> NCOP representatives are engaging with the public and listening to what they have to say. The programme is usually held in deep rural areas where service delivery issues are most rife, and where people lack the resources to access Parliament.

_1.4 Sectoral Parliaments

Sectoral Parliaments are special dedicated parliaments for groups that are generally marginalised. Examples of sectoral parliaments include women’s parliament, youth Parliament, worker’s parliament and children’s parliament. The sittings are hosted annually for each parliament, during which Members of Parliament engage with these marginalised groups on matters affecting them.

The overall aim is to encourage public participation by providing the public with the opportunity for them to voice their concerns and grievances._ <-- delete this section in italics

**Comment by zarino** [comment]
The CSS styles for this have been merged into `master`, but this hasn't been deployed yet and the custom html content hasn't been added to the page yet. So I'm going to reopen this ticket.

**Comment by JenMysoc** [comment]
done!
