### ISSUE TITLE
[ZA] Second A/B test on "MP Profiles" homepage hot topic button placement

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2274]
We’re going to assume that moving the "Hot Topics" buttons to the top of the homepage is the new normal, because #2250 showed fairly clearly that it improves clicks on the "MP Profiles" hot topic button.

We now want to check that the new normal (all 5 buttons at the top) doesn’t _adversely_ affect engagement with all the other homepage content. (We’re a bit worried people will land on the homepage, see just a screen full of red buttons, and if they’re not interested in MP Profiles, just leave).

So, set up a new 3-way A/B/C test.

A test has been successful when a user clicks anything matching `$("#page a[href]:not(.home__topics a), #page input, #page button")`.

| Test | Behaviour |
| :---: | --- |
| A | All 5 Hot Topics buttons at the top of homepage |
| B | MP Profiles button at the top, other 4 Hot Topics at the bottom |
| C | All 5 Hot Topics buttons at the bottom |

We don’t really want to _go_ with Option C (it would mean ignoring the benefit shown by #2250) but we’re including it in the test because it will give us a baseline against which to compare Options A and B.

**Comment by wrightmartin** [comment]
#2275 PR!

**Comment by jacksonj04** [comment]
<img width="887" alt="screen shot 2017-08-10 at 09 46 32" src="https://user-images.githubusercontent.com/619082/29162271-d2880b1e-7db0-11e7-8594-31c79302d7ba.png">

Winner is Option B, #2293 is ticket to implement.
