### ISSUE TITLE
[ZA] Page to view all member attendance records

### ISSUE THREAD

**Issue by xybrnet** [mysociety/pombola#2276]
Create a page to list all member attendance records, and add a link to view it below the most recent attendance records on the MP profile pages.

(Similar to the page showing all appearances)

**Comment by JenMysoc** [comment]
Hey @xybrnet as Gaile has requested us to do a redirect can I assume this work is complete?

**Comment by xybrnet** [comment]
Hi @JenMysoc. This as complete, yes. Excuse me for not marking it so.
