### ISSUE TITLE
[KE] Allow featured person space to show a features blog instead

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2278]
Jessica is working with the South African group Livity on a project called Project Democracy which is based on a South African initiative they are trying to replicate in Kenya. Mzalendo have been chosen as the platform on which to share the updates and news from this project. These will consist of blogs, youtube videos, twitter updates and facebook updates as well as potentially instagram updates. 
 
One of the elections changes Jessica wants therefore is for the top three blogs (which Jessica will pick - likely to the most recent in the Project Democracy category) to be represented with a picture in the place where the Featured Person element currently sits.

Once the election is over Jessica would like this element to go back to showing a featured person.

![screen shot 2017-06-13 at 09 56 33](https://user-images.githubusercontent.com/4170351/27230411-05281ed6-52a7-11e7-9e0c-b22c4bb7f3be.png)

**Comment by wrightmartin** [comment]
Something like this?

![mzalendo](https://user-images.githubusercontent.com/2292925/27540599-a0c268be-5a78-11e7-8c3a-81efb203b311.png)

**Comment by JenMysoc** [comment]
Yes but it will also need to be able to include pictures :)

The title of the blog should be Project Mchujo :)

**Comment by wrightmartin** [comment]
Just to clarify: is the image coming from the blog post itself, or is it more like a general image for Project Mchujo?

![mzalendo](https://user-images.githubusercontent.com/2292925/27577706-96a4eb12-5b19-11e7-9a50-35b955a128a8.png)

**Comment by JenMysoc** [comment]
Image will be from blog post itself :)

**Comment by JenMysoc** [comment]
@JessMusila what do you think of the above?

**Comment by JenMysoc** [comment]
@mhl Jessica is going to use the same blog as for the elections and tag posts appropriately

**Comment by JenMysoc** [comment]
Elections are over now so this is obsolete
