### ISSUE TITLE
[KE] Set up YNR for Kenya

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2280]
Set up an instance of YNR and import the details of candidates from the IEBC into the platform.

We need to find out from jessica:

- [ ] what format the candidate data will be in

- [x] how she wants to include the election data in Mzalendo (or if YNR will be separate)

From our call notes:

"Another thing Jessica would like to include for the elections is a YourNextRep instance to gather more data about the candidates standing for election at all levels of the government. She has a 3rd year university student who will be helping her with this (Robin, who has previously contacted mySoc about setting up YNR in Kenya and is now working with Mzalendo). 
 
Currently we don’t know if the IEBC will be releasing the data via API as they did last time - Jessica is going to an election meeting over the next two days which will hopefully tell us that information. The IEBC have committed to make a gazetted version of the candidate data available by 2017-06-24 and Robin may be able to OCR this if they don’t release an API version. 
 
With the candidates they would like to group them by age group and by gender so that people can see at a glance how many younger candidates are running and how many female candidates are running. If possible, Jessica thought it would be good to show who had already been in parliament and link out to the Mzalendo page for that person so people could gather more information. 
 
They would also like to display manifestos for people who are running, so that the youth voters (whom they are trying to attract) can make good decisions. Jessica asked if the candidates who were running again could have their profiles pre-populated from Mzalendo data. 
 
They’d like to use the data from YNR to populate Mzalendo post election with the candidates that have won. If possible."

**Comment by JenMysoc** [comment]
Jessica would like the candidate data to be, or look like it is, a part of Mzalendo and be reflected on the homepage. 

Jessica has asked if previous and incumbent MPs that are candidates can have their records be accessible to the public. EG all the info that's already on Mzalendo about the current MPs should also be reflected somehow on the candidate platform.

Jessica also wants users to be able to search through the aspirants database: according to gender, age, county and the 6 elective positions in this election.

We are waiting to find out about the format of the data, we also need to know:

- [ ] How the aspirant data is going to be reflected on the homepage
- [ ] How we will display or link the current data for the MPs in position to the positions as candidates for election in August

**Comment by mhl** [comment]
I created a ticket for the initial work on the YNR site here: https://github.com/mysociety/yournextrepresentative/issues/985

**Comment by JenMysoc** [comment]
We also need some design love to make the site look like Mzalendo

**Comment by zarino** [comment]
Pull request for the Mzalendo-themed styling here: https://github.com/mysociety/yournextrepresentative/pull/986

**Comment by chrismytton** [comment]
This is now live at http://kenya.ynr.mysociety.org/, yay! 🏆
