### ISSUE TITLE
[KE] Provide 2017 speech counts to Jessica

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2282]
Jessica would like the "up to now" 2017 speech counts for the MPs currently in position. 

Date range: 01/02/2017 to 20/06/2017 (Checking this is the correct end date)

**Comment by mhl** [comment]
We usually do this with a command like the following:

    ./manage.py kenya_hansard_speech_statistics --date-from=2016-01-01 --date-to=2017-01-18

... and apply caveats that you can find in the previous email where we sent such statistics over.

**Comment by JenMysoc** [comment]
This has been done
