### ISSUE TITLE
ZA: redirect http -> https for PA if PMG are happy with that

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2288]
We've already added a Let's Encrypt certificated for https://www.pa.org.za but it's still http by default. If PMG are happy with this (and I can't see why not - it should be all up-side) we can redirect any http request to https by changing.

This *might* affect someone in situations like:
* someone who's programmatically downloading the database dumps or JSON export with a client that doesn't handle redirects.
* scrapers that don't handle redirects - this might possibly be the case for the EP scrapers but it'd be very easy to fix if so.

I don't think we should worry about those - it should be quite clear what the failure is, and this is definitely a positive change for the site.

I think all that's needed it to turn on `https_only` in the vhost's JSON.

**Comment by JenMysoc** [comment]
This has been completed
