### ISSUE TITLE
[KE] RSS feed proxy on homepage is broken

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2292]
The Mzalendo homepage uses the Google Feed API to load an RSS feed from `{{ settings.BLOG_RSS_FEED }}` and display it in `#home-news-list`.

Except the Google Feed API was deprecated at the end of last year, and we need to use something else.

ISTR last time we looked at this, we couldn’t just ajax in the RSS feed because of cross-domain limitations. If that’s still the case, maybe we should switch to another server-side proxying service, like https://rss2json.com?

**Comment by zarino** [comment]
Another way to fix this would be to get `www.mzalendo.com` to include a HTTP response header like:

    Access-Control-Allow-Origin: http://info.mzalendo.com

Allowing ajax requests from `info.mzalendo.com` to request data from `www.mzalendo.com`.

**Comment by jacksonj04** [comment]
`www.mzalendo.com` is apparently handled via blogs.

**Comment by jacksonj04** [comment]
So, I think we need to add a couple of lines to the blogs `httpd.conf`:

    SetEnvIf Referer "^http://www.mzalendo.com/" is_mzalendo_www
    Header add Access-Control-Allow-Origin http://info.mzalendo.com env=is_mzalendo_www

and then modify `feeds.js` to not use the Google Feeds API

**Comment by dracos** [comment]
"Referer" isn't always set, and can be spoofed. Why not use `SetEnvIf Host` as I suggested in Slack? (You probably want `SetEnvIfNoCase` actually.)
I would also recommend `set` rather than `add` in general.

**Comment by jacksonj04** [comment]
So:

    SetEnvIfNoCase Host "^www\.mzalendo\.com" is_mzalendo_www
    Header set Access-Control-Allow-Origin http://info.mzalendo.com env=is_mzalendo_www

?

**Comment by dracos** [comment]
Looks okay, though of course I would test it first (Zarino's https://github.com/zarino/micropache might come in helpful there if you don't have Apache set up? Both these commands work in .htaccess files so should be straightforward to test.)
