### ISSUE TITLE
[KE] import elected representatives from the 2017 elections from YNR

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2300]
There are links to the spreadsheets of the elected members of the National Assembly, the special Women Representatives and Senators on this page: http://kenya.ynr.mysociety.org/help/results

The links to the CSV files are:

* http://kenya.ynr.mysociety.org/media/candidates-elected-na-2017.csv
* http://kenya.ynr.mysociety.org/media/candidates-elected-wo-2017.csv
* http://kenya.ynr.mysociety.org/media/candidates-elected-se-2017.csv

The problem with importing these into Mzalendo is that some of them may already existed in the Mzalendo database because they had been elected politicians in the past, but there is no shared ID.

The first thing perhaps to do is to get a sense of how many of these cases there are (perhaps from asking Jessica). If there aren't many, then we could add all of these people as if they were new, and then use [`core_merge_people`](https://github.com/mysociety/pombola/blob/master/pombola/core/management/commands/core_merge_people.py) to merge any that are actually duplicates with their existing record.

Alternatively, if there are lots of incumbents who have been reelected, I would do the following (which, n.b. depends on a tool which doesn't exist yet, but hopefully will in some form by the start of the next sprint):
* Create a CSV file of people currently in the Mzalendo database
* Use the [new standalone reconciler tool that we're planning](https://github.com/everypolitician/everypolitician/issues/575) on that CSV file and each of the elected people CSV files to produce a mapping between person IDs when they're the same person. This should be nice, because i'll show photos from both sources if they exist.

Either way, a new import script will been needed to create / update the people in Mzalendo.

The positions are modelled as follows - (I think this is right, but please double-check! I'm writing this ticket in something of a rush):
* Members of the National assembly have a position with:
** PositionTitle: Member of the National Assembly
** Organisation: Parliament
** Place: a place with PlaceType "Constituency 2013-"
* Women Representatives are the same, *except*:
** Their Position has a Subtitle of "Women's representative"
** Their Position's Place has a PlaceType "County 2013-"
* Senators have a position:
** PositionTitle: Senator
** Organisation: Senate
** Place: a place with PlaceType "County 2013-"

The nominated members of the National Assembly and the Senate (whom we don't have data about yet, I think) are similarly modelled, except for having a subtitle "Nominated"

**Comment by mhl** [comment]
Abiud has sent us a list of members of the national assembly who have been re-elected - without Mzalendo IDs / slugs, unfortunately, but this is a help nonetheless.

**Comment by JenMysoc** [comment]
done!

**Comment by chrismytton** [comment]
Done in https://github.com/mysociety/pombola/pull/2310
