### ISSUE TITLE
[KE] Changes to main Mzalendo nav menu

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2302]
From earlier call with Jessica:

> We propose the "MPs" dropdown menu should have four links: MNAs, Senators, Women and Youthful MPs (under 35s). 
> 
> For the last two categories: there is no need to distinguish between Senators and MNAs as they are special caucuses. We will reach out to the two groups for the list of names.

> The "News" dropdown menu should have only two categories:
> i) Press - Merge info under Press releases and Newsletters 
> ii) Infographics - Merge Information captured as data and infographics 

> "Research" tab to replace "Public Participation"
> We will archive all Mzalendo related projects under this in order of priority:
> a) Election 2017 milestones
> b) Debunking Myths on Women MPs (Drop the duplicate page called women MPs)
> c) People's Shujaaz Awards (Please drop the duplicate page titled 'Peoples Shujaaz Finalists) 
> d) Kindly rename the 'Proposed Bills; under public participation 'National Youth Employment Authority' bill
>
> We would also like to have the opportunity to add other research outputs done in conjuction with mySociety like the recent MAVC UCL research and the research comparing SA/Kenya/UK & US civic sites. 
> 
> Do not carry over the polls and forum from the public participation tab. Also the rights and responsibilities list is duplicated from the democracy resources section.

**Comment by zarino** [comment]
Just discussed this with @jacksonj04. As far as we can tell, the menu structure will look something like this (with changes in **bold**):

* Home
* Democracy Resources
   * Citizens Rights & Responsibilities
   * How Our Democracy Works
   * Democracy FAQs
   * Ministry Overview
   * Constitution 2010
   * Election Legislation
   * Democracy Documents
* MPs
   * NA Members
   * Senators
   * **Women** – new page, listing Women MNAs and Senators
   * **Youthful MPs** – new page, listing under-35 MNAs and Senators
* Parliament
   * Parliament Overview
   * Committee Overview
   * Bills Overview
   * Bills List
   * Hansard
   * Political Parties
* **Research**
   * **Election 2017 milestones** – not sure what page this is??
   * **Debunking Myths on Women MPs** – the existing `/women` page
   * **People's Shujaaz Awards** – the existing `/shujaaz/2015` page
   * **National Youth Employment Authority** – the existing `/info/proposed-bills` page
* News
   * **Press** – new page that combines current `/info/press` and `/info/newsletter`
   * **Infographics** – new page that combines current `/info/infographics` and `/info/data`
* About
   * Mzalendo Overview
   * Site FAQs
   * Policies
   * Founders
   * Management
   * Partners
   * Scorecard FAQs
   * Contact
   * Get the data

There will be some pages that are no longer linked to from the nav:

* `/info/forum`
* `/info/polls`
* `/blog`

I can understand the first two maybe disappearing, but I have a feeling `/blog` should still be linked to from somewhere! Maybe in the "News" menu? Or we could make it an actual top-level menu item. We’re removing the "Public Participation" link, so there’ll be lots of room at that top level.

**Comment by jacksonj04** [comment]
In the interests of shipping something sooner and tackling the complex bit later, I'm slicing this into two issues. #2314 now covers the new Women and Youthful MP pages, this ticket specifically deals with the purely navigational changes:

* Remove 'Public Participation'
* Shuffle around 'Research' to match new order
* Remove items from 'News' (but temporarily retain 'Blog' until we figure out where it should go, because otherwise it orphans all the content)
* Add redirects to handle the newly merged pages in the News menu

To do:

* [ ] Manually merge the page content via admin for the merged pages.

**Comment by chrismytton** [comment]
This was mostly done in https://github.com/mysociety/pombola/pull/2315 and there have been other changes to the menu in the meantime so I'm going to close this issue. Any further menu changes should be documented in a new issue.
