### ISSUE TITLE
[KE] Show "Responsibilities" for a representative, near their contact details on their profile page

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2304]
It is a waste of everybody’s time for Mzalendo visitors to contact representatives about issues the representative has no influence over.

Different types of representatives have different responsibilities. From Jessica:
* Members of the National Assembly (MNAs): Representation, Oversight, Legislation and CDF Management
* All other types of MNAs (nominated & women reps): Representation, Oversight and Legislation only
* Senators: Representation, Oversight and Legislation with county interests in mind.

Make these responsibilities clear on the person page, near the contact details.

**Comment by JenMysoc** [comment]
1. Responsibilities of the President
Constitution of Kenya Article 131, 132, 133 and 134 (Abridged) 
 Head of State and Government, Commander-in-Chief of the Kenya Defence Forces and Chairperson National Security Council. 
Declares a state of emergency and war with the approval of Parliament.
Addresses each newly elected Parliament 
Gives a State of the Nation address to Parliament each year
Nominates and appoints the Cabinet Secretaries, Attorney-General, Secretary to the Cabinet, Principal Secretaries, high commissioners, ambassadors and diplomatic and consular representatives and other state officers.
Chairs Cabinet meetings, directs and co-ordinates the functions of ministries and government departments. 
 Assigns responsibility for implementation of any Act of Parliament to a Cabinet Secretary.
Receives foreign diplomatic and consular representatives.
Confers honour in the name of the people and the Republic. 
Ensures that the international obligations of the Republic are fulfilled through the actions of the relevant Cabinet Secretaries.
 Exercises the power of mercy. 
 
2. Responsibilities of a Cabinet Secretary 
Runs departments and agencies under their dockets in accordance with the constitution.
Accountable to the President in exercise of their powers 
Attend to Parliament, if need be, to answer questions concerning their ministries and 
Provides full and regular reports concerning matters under their control.

**Comment by zarino** [comment]
> The box on the Elected (Constituency) Members of the National Assembly (MNAs) profiles will have the following list: Representation, Oversight, Legislation and NG-Constituency Development Fund (NG- CDF) Management 
>
> Nominated MNAs box will list: Representation, Oversight and Legislation only.
>
> Women Representatives box will list: Representation, Oversight, Legislation & NG-Affirmative Action Social Development Fund (NG-AASDF)
>
> Senators responsibilities will be: Representation, Oversight and Legislation with county interests in mind.

**Comment by zarino** [comment]
After some discussion with @JenMysoc and @JessMusila, here’s where I think we’re heading with this:

![screen shot 2017-10-23 at 15 48 37](https://user-images.githubusercontent.com/739624/31896481-ccb1d90a-b80b-11e7-87de-f3f87003ebce.png)

I originally thought maybe it could fit into the sidebar, nearer the contact details, but there’s just too much text, and a sidebar position probably isn’t prominent enough either.

In cases where the responsibility text is quite long (President, and possibly also Cabinet Secretaries), we should probably show only the first 4 or 5 list items, with a "Show more" link that unfolds the remaining items on demand.

@JessMusila – what do you think of this, now you can see it in place? Do you think it solves the problem?

**Comment by JessMusila** [comment]
@zarino Makes sense. Let's go with your proposal. @JenMysoc
