### ISSUE TITLE
[ZA] - Notes to person attendance page to clarify definitions

### ISSUE THREAD

**Issue by xybrnet** [mysociety/pombola#2306]
Change some wording under the person page attendance tab,
and add some clarification as requested by People's Assembly.

**Comment by JenMysoc** [comment]
hey @xybrnet can you give us the wording that needs to be changed? If you've done it via a pull request can you let me know the number so I can get someone to review and merge it? Thanks!

**Comment by xybrnet** [comment]
Hey @JenMysoc Sorry, I forgot to close the issue.
The pull request has been merged - [(https://github.com/mysociety/pombola/pull/2307)]

Thank you.
