### ISSUE TITLE
[KE] Ensure that all memberships for current politicians in Kenya have the same start date

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2318]
Currently some of the re-elected members of parliament in Kenya are showing different start dates for memberships than the newly elected members. Jessica would like all memberships to show the same start date.

Example;
Re-elected member Anthony Kimani Ichung'Wah
![re_elected mp](https://user-images.githubusercontent.com/4170351/31932532-6cb44be4-b89e-11e7-86e9-c71b901a7113.png)

Newly elected member Hon Patrick Kimani Wainaina Junge
![new_mp_snip](https://user-images.githubusercontent.com/4170351/31932603-a2d11ef0-b89e-11e7-9a52-2a09e38e8cdb.png)

**Comment by jacksonj04** [comment]
This appears to be a [single case](http://info.mzalendo.com/search/?q=anthony+kimani), down to a mismatch between ` and ' in the person name.

Proposed fix is `./manage.py core_merge_people --keep-object anthony-kimani-ichungwah --delete-object anthony-kimani-ichungwah-2`, then manually re-upload the new photo.
