### ISSUE TITLE
[KE] swap Bonga-Na-Mzalendo and Dokeza buttons on Mzalendo homepage

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2319]
Jessica would like the Bonga-Na-Mzalendo and the Dokeza buttons swapped on the Mzalendo homepage

![screen shot 2017-10-24 at 09 36 52](https://user-images.githubusercontent.com/4170351/31932852-6c0bcc66-b89f-11e7-8c3a-a52f74451dbb.png)

In addition the text on the Dokeza button should read: _Click to review bills and give your input_

**Comment by 4bic** [comment]
Hi @JenMysoc, 
I've made [this fix](https://github.com/4bic/pombola/commit/e7cae28ce4415fa922961648dc1a18130fe568d1) I've as per this request. 
![screen shot 2017-10-25 at 17 35 58](https://user-images.githubusercontent.com/5486449/32005063-fe880e8a-b9ab-11e7-9b75-7eed0f49c1d9.png)

**Comment by JenMysoc** [comment]
@4bic That's great, do you have a pull request you could submit to us for approval so we can make the change live on the site?

**Comment by 4bic** [comment]
Hi, kindly review [PR#2323](https://github.com/mysociety/pombola/pull/2323)
