### ISSUE TITLE
[ZA] Homepage redesign for PA to incorporate WiP links

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2321]
We're going to implement WiP for People's Assembly over the next couple of months and PMG would like to have a homepage redesign to go along with this. We'll discuss the specifics on a call on Thursday 26th Oct but here are some points they've made for this placeholder ticket.

- There needs to be a space for the survey and the survey results on the homepage
- There needs to be a space to link to write to MPs and also write to a committee <del>(can the MP one be linked to the rep locator? as they would need to locate MP first)</del>
- Infographics still need to be prominent
- Nav menu bar needs to change again; 

- [ ] Remove the Democracy Resources link and remove bills link. Keep questions and campaigns under the HotTopics dropdown (though at bottom of list) but move campaigns to the blog
- [ ] Add MP attendance to nav menu and remove from Hot Topics

Further details will be added once we've had the call

**Comment by JenMysoc** [comment]
PMG are quite set on their homepage mockup and would like us to move forward with something similar to that. 

The key thing for the site is connecting users to their representatives, so we need to consider the MP profiles link, the Rep Locator and the new Write to your MP tool. 

Surveys will be done on a blog as a blog category, we need them to be almost *pinned* to the homepage when they are running and then off when the survey is over to be replaced by another blog or the results. 

Here is the mockup image they sent through
![mock homepage 1](https://user-images.githubusercontent.com/4170351/32051424-704f3f70-ba4c-11e7-9185-c703ac9636ea.jpg)

**Comment by wrightmartin** [comment]
Here's my notes from the cal

### Priorities order (TBC)

- Write to a representative
- Write to committee
- Embedded survey
- Rep locator 

**Embedded survey** - either a call to action to take the survey or to see the results. If there’s not one there, replace it with a blog post.
Survey will just be a specialised blog post - can have a slightly different icon or visual treatment.

**Write to rep** - People write to a representative not based on their location, but on their preference, eg what they have seen in the media, what they know they’re specialists of - eg energy, women’s issues. People don’t identify with their assigned representative. It’s artificially assigned process they don’t relate to and no-one is enforcing.

Surveys are a new way of doing submissions to parliament

MP Profiles button must stay prominent on mobile

**Comment by wrightmartin** [comment]
Looking at Analytics for the past year this is where people go from the homepage

1. MP profiles (the button that is very prominent on mobile)
2. Rep locator
3. National Assembly (I assume via the 'People' dropdown menu item in the nav)
4. MP Attendance
5. Search
6. MP Assets (a bit surprised to see this here. The new design removes this from the homepage)
7. People
8. Search for person by name
9. MP Corner
10. About

**Comment by wrightmartin** [comment]
Some observations that I think are important

- MP Corner is popular, the featured MP will regularly result in being the most viewed MP on the site
- MP Corner, rep locator and MP profiles are all the same thing, or at least the _same subject_. They're also the main thing that aligns with the aim of the PA website
- News on the homepage is good - it keeps in topical and the content changes. Good for SEO.
- MP assets are popular, I think we should find a way of keeping them on the site

**Comment by wrightmartin** [comment]
Priorities from the PMG team

>  1) MP profiles
>  2) Public engagement* (active) if not, Write to an MP
> 3) Write to an MP
> 4) Write to a Parliament Committee
> 5) MP Corner
> 6) MP Attendance,
> 7) MP Assets
> 8) Rep Locator: Find your rep at local, provincial and national level
> 9) Infographics
> 10) Public engagement results*
> 11) Constituency offices list*
>  
> - As we discussed, if we do not have an active survey (no. 2), the latest survey results will be featured, but way down the priority list at no. 10
> - *11 refers to a list of constituency offices that we created as a blog on demand from mostly organisations who wanted a complete list of PCOs. If it is not possible to create a block for it right now, it can be shelved for another sprint. See link to blog here https://www.pa.org.za/blog/pco
>  - We really want the mobile home screen to open up and show most of the high priority blocks/tabs at a glance, i.e. if it is at all possible to see at least the top 4-6 blocks (I attached a screenshot of the PMG mobile home screen  to give an idea.)

![screenshot_2017-11-08-17-16-51](https://user-images.githubusercontent.com/2292925/32719284-c10cbe6a-c857-11e7-9183-ad12cdb96845.png)

**Comment by JenMysoc** [comment]
It would be good to know from @mhl if being able to change the importance of something on the page is something it would be possible for them to do in the admin - if that's a huge and difficult piece of work we might need to just situate the public engagement stuff somewhere in the middle to balance its changing priority

**Comment by wrightmartin** [comment]
@JenMysoc hopefully we can resolve that in the design process rather than putting together a technical fix

**Comment by wrightmartin** [comment]
Something that puzzles me is there's nothing about the blog or news on the homepage. For me, that's one of the key ways for the PMG team to control priorities of things – writing blog posts and new releases about things that are happening.

**Comment by wrightmartin** [comment]
Working document to figure out priorities between the team and what we know from analytics
 https://docs.google.com/spreadsheets/d/1RlG1XBtglxDNS6hFHoRJ2eDVS1giNHyFdBHU_olV6lY/edit#gid=0

**Comment by wrightmartin** [comment]
### Designs

![desktop hd](https://user-images.githubusercontent.com/2292925/32725217-25831a7e-c86c-11e7-871e-00ef3d81b604.png)

![mobile portrait](https://user-images.githubusercontent.com/2292925/32725215-254bfa58-c86c-11e7-9051-b5084eccd197.png)

### Walkthrough of designs

[People's Assembly homepage changes.pdf](https://github.com/mysociety/pombola/files/1466770/People.s.Assembly.homepage.changes.pdf)

**Comment by wrightmartin** [comment]
Comments from PMG

> Hi Jen/Martin
> Thank you for the work you’ve done so far and so quick! It looks great, just a few queries:
> 1) The Meet your MPs segment works well, but could the wording of the ‘MP Profiles’ link be changed to ‘Show more MPs’
> 2) On the ‘Write’ feature – can you fit in the wording ‘Do you have a problem?’
> 3)On the survey – can you clarify what the “unique layout and silhouette” would be. Initially we thought we could (if programming allows for it) – have a survey specific image, but it looks like there might not be enough space for that.
>  
> Mobile – is it possible to keep the red MP Profiles (red tab) as it is now.
>  
> *Reminder that we decided in our last discussion that MP Attendance will be a standalone feature on the menu bar and that ‘Democracy Resources’ under hot topics, will be scrapped and only ‘Questions’ will remain.  
>  
> Sincere regards
> Megan Lessing

**Comment by wrightmartin** [comment]
> 1) The Meet your MPs segment works well, but could the wording of the ‘MP Profiles’ link be changed to ‘Show more MPs’
> **Yes, good idea** 
> 2) On the ‘Write’ feature – can you fit in the wording ‘Do you have a problem?’
> 
> **Yep** 
> 3) On the survey – can you clarify what the “unique layout and silhouette” would be. Initially we thought we could (if programming allows for it) – have a survey specific image, but it looks like there might not be enough space for that.
> 
> **By 'unique layout and silhouette' I mean the survey feature itself looks different to the other items surrounding it so it will draw the eye and encourage people to interact with it.** 
> 
> **We may be able to fit a small thumbnail type image but as you say, there's not a huge amount of room for it.**
> 
> Mobile – is it possible to keep the red MP Profiles (red tab) as it is now.
> 
> **Yep**
> 
> **If you're happy with the wireframe with these changes the next step would be to work it up into a design with your colour scheme. Are you happy for us to start that asap?**
> 
> **Martin**

**Comment by wrightmartin** [comment]
> Hi Guys
>  
> Yes it’s a go it seems. It would be really good if we could do the thumbnail for the survey insert, but only if we will be able to change the picture ourselves according to the survey topic.
>  
> On the Write option, we get that the placement of the tabs will be reassessed after 6 months, but the height of the tabs (i.e. visibility/prominence on the homepage) is a little bit of a concern. Is it possible to make the tabs bigger?
>  
> Thanks again Martin/Jen

**Comment by wrightmartin** [comment]
> Dear Martin and Jen
>  
> Thank you for your hard work on this and the great wireframes to explain to purpose of the changes - and for your careful examination of what "works" on the site according to user stats.
>  
> Very exciting - we look forward to seeing it actualised.
>  
> I really feel for the first time that the purpose of People's Assembly is reflected in the design presentation of content.
>  
> Many thanks
> Gaile

**Comment by wrightmartin** [comment]
Here's the wireframes worked up into a design

![desktop hd copy 2](https://user-images.githubusercontent.com/2292925/33170602-b2c2f928-d040-11e7-9233-d073a4f6d825.png)

**Comment by wrightmartin** [comment]
Here's the homepage design with the menu bar changes that will also be applied

![desktop hd copy 2](https://user-images.githubusercontent.com/2292925/35733044-b4ad24e2-0813-11e8-8f47-ed4b6996dbc6.png)

**Comment by JenMysoc** [comment]
for @wrightmartin PMG have said the following about the survey and committee WIP buttons:

"We don’t have a current survey, but we will work on putting together a survey on debt relief. We need at least 24 hours to put it together and should be able to finalise it by tomorrow (to either then go live either tomorrow or Monday). The text will be specific to the survey and we want to be able to change that ourselves, as well as be able to change the picture. Can we change the wording on the survey button to ‘HAVE YOUR SAY’?"

For the moment to get it launched let's hard code it and I will make a ticket for the admin side of that now

"For the Write to a committee button can he grey it out and if it’s possible to have the wording ‘COMING SOON’?"

**Comment by wrightmartin** [comment]
> "For the Write to a committee button can he grey it out and if it’s possible to have the wording ‘COMING SOON’?" 

I'll see what I can do...

**Comment by chrismytton** [comment]
Done in #2349
