### ISSUE TITLE
ZA (WriteInPublic): create committee secretaries Popolo JSON file suitable for WIP

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2324]
One of the instances that PMG want is just the secretaries of committees. They've supplied us with the email addresses of these scretaries in a word document, but I've turned that into a spreadsheet here:

https://docs.google.com/spreadsheets/d/1-JNEZcHhO99UuUQNFPjKnuE-lhv6Ddj6yiapfaBC5r0/edit#gid=0

We will need to generate a Popolo JSON file with these details suitable for presenting them as options to write to in WriteInPublic

**Comment by chrismytton** [comment]
I've been investigating https://github.com/mysociety/pombola/issues/1216 which is about cleaning up the committees in Pombola South Africa. From my investigations it seems that the `OrganisationKind` that we'll need to use for getting the list of committees for adding the email addresses and eventually for writing to is name == "National Assembly Committee".

**Comment by chrismytton** [comment]
This is now done. Committee Popolo JSON available here: https://www.pa.org.za/api/committees/popolo.json
