### ISSUE TITLE
[ZA] Design tasks for WriteInPublic/pa.org.za integration

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2334]
I've made some changes to the WiP/PA integration  (PR: https://github.com/mysociety/pombola/pull/2329 branch: `send-messages-via-writeinpublic`) since the initial design bits were done by @zarino, so there's a few bits that need some design ❤️

## What's new?

- The process now lives at `/write`, which you can see [on the staging site](http://za-pombola.staging.mysociety.org/write/).
- We're now using a wizard so we have separate "Recipients", "Draft" and "Preview" steps
- There is now a flash message when the message is sent which appears on the individual message page where the user is redirected.
- The preview step has some text saying "Are you happy for this message to be sent?" etc
- You can now go back a step in the wizard, so Preview->Draft and Draft->Recipients

## What needs doing?

- [x] Recipients step needs styling, this is using [chosen.js](https://harvesthq.github.io/chosen/) just like WriteInPublic, so hopefully won't be too hard to style in a similar way

- [x] "Are you happy for this message to be sent?" text on the preview page might need a bit of styling so it looks similar to the WriteInPublic version
- [x] Flash message that appears once message has been sent needs some styling
- [x] Back buttons _might_ need some styling, I've added some classes that looked vaguely appropriate, but not sure if they're "right" :)
- [ ] Anything else that you notice while going though things.

### Recipients screen

<img width="868" alt="screen shot 2017-12-12 at 14 52 53" src="https://user-images.githubusercontent.com/22996/33891898-402058e8-df4f-11e7-8918-98cfea62c97a.png">

### Flash message

<img width="918" alt="screen shot 2017-12-12 at 14 52 29" src="https://user-images.githubusercontent.com/22996/33891920-50172286-df4f-11e7-9257-ace42de934c7.png">

### "Are you happy for this message to be sent?" text

<img width="956" alt="screen shot 2017-12-12 at 14 52 07" src="https://user-images.githubusercontent.com/22996/33891938-5bd7378c-df4f-11e7-8ca9-2268b2181d7c.png">

**Comment by JenMysoc** [comment]
Only suggestion from PMG: At the end [of sending a message]when it states: Success, your message has now been sent, there should be a: Return to Write to my MP [link] rather than Correct this Page [link] at the bottom of page.

**Comment by zarino** [comment]
> Only suggestion from PMG: At the end [of sending a message]when it states: Success, your message has now been sent, there should be a: Return to Write to my MP [link] rather than Correct this Page [link] at the bottom of page.

@JenMysoc I’ve added this to the design backlog spreadsheet.

**Comment by chrismytton** [comment]
Done as part of #2349
