### ISSUE TITLE
[KE] Remove duplicate profiles from Mzalendo

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2337]
There are people on Mzalendo who have two profiles - it's people who have served in both the national assembly and the senate

Below are MPs with two profiles, kindly merge them. 

1. Johnson Sakaja 
http://info.mzalendo.com/person/johnson-arthur-sakaja/
http://info.mzalendo.com/person/johnson-arthur-sakaja-2/

2. Martha Wangari 
http://info.mzalendo.com/person/martha-wangari/
http://info.mzalendo.com/person/martha-wangari-wanjira/

3. Naisula Lesuuda
http://info.mzalendo.com/person/naisula-lesuuda/
http://info.mzalendo.com/person/josephine-naisula-lesuuda/

4. Irungu Kangata 
http://info.mzalendo.com/person/irungu-kangata/
http://info.mzalendo.com/person/irungu-kangata-2/

5. Fredrick Outa 
http://info.mzalendo.com/person/fredrick-outa/
http://info.mzalendo.com/person/fredrick-otieno-outa/

6. Janet Ongera
http://info.mzalendo.com/person/janet-ongera/
http://info.mzalendo.com/person/janet-ongera-2/

7. Liza Chelule
http://info.mzalendo.com/person/liza-chelule/
http://info.mzalendo.com/person/chelule-chepkorir-liza/

8. Mishi Mboko
http://info.mzalendo.com/person/mishi-juma-khamisi/
http://info.mzalendo.com/person/mishi-juma-khamisi-mboko/

9. Aisha Jumwa 
http://info.mzalendo.com/person/aisha-jumwa-katana/
http://info.mzalendo.com/person/aisha-jumwa-karisa-katana/

10. Dullo Fatuma
http://info.mzalendo.com/person/dullo-fatuma-adan/
http://info.mzalendo.com/person/dullo-fatuma-adan-2/

11. Rose Nyamunga 

http://info.mzalendo.com/person/rose-auma-ogendo/
http://info.mzalendo.com/person/rose-ogendo-nyamunga/

**Comment by JenMysoc** [comment]
Just a list to compare as Jessica has mentioned this again

1. Peter Njeru Ndwiga (Njeru Ndwiga)

2.     Dullo Fatuma Adan (Dullo Fatuma Adan)

3.     Prof. Sam Ongeri ( Prof Samson Kegengo Ongeri)

4.     Fredrick Otieno Outa ( Fredrick Otieno Outa)

5.     Franklin Mithika Linturi (Franklin Mithika Linturi)

6.     Irungu Kang’ata (Irungu Kang’ata)

7.     Ledama Ole Kina ( Ledama OleKina)

8.     Ephraim Mwangi Maina Kirinyaga (Ephraim Mwangi Maina)

9.     Margaret Kamar (Margaret Kamar)

10.  Samuel Poghisio (Prof Samuel Losuron Poghisio)

11.  Sara Paulata Korere (Sara Paulata Korere)

12.  Aisha Jumwa Katana (Aisha Jumwa Karisa Katana)

13.  Beatrice Kones (Beatrice Pauline Cherono Kones)

14.  Jayne Njeri Kihara (Jayne Njeri Wanjiru Kihara)

15.  Sophia Abdi Noor (Sophia Abdi Noor)

16.  Zuleikha Juma Hassan (Zuleikha Ju Ma Hassan )

17.  Roselinda Soipan Tuya (Roselinda Soipan Tuya)

18.  Janet Ongera (Janet Ongera)

19.  Dullo Fatuma Adan (Dullo Fatuma Adan)

20.  Margaret Kamar (Prof Margaret Jepkoech Kamar)

21.  Rose Nyamunga (Rose Ogendo Nyamunga)

**Comment by jacksonj04** [comment]
* [x] Johnson Sakaja
* [ ] Martha Wangari
* [ ] Naisula Lesuuda
* [ ] Irungu Kangata
* [ ] Fredrick Outa
* [ ] Janet Ongera
* [ ] Liza Chelule
* [ ] Mishi Mboko
* [ ] Aisha Jumwa
* [ ] Dullo Fatuma
* [ ] Rose Nyamunga
* [ ] Peter Njeru Ndwiga (Njeru Ndwiga) 
* [ ] Prof. Sam Ongeri ( Prof Samson Kegengo Ongeri)
* [ ] Franklin Mithika Linturi (Franklin Mithika Linturi)
* [ ] Ledama Ole Kina ( Ledama OleKina)
* [ ] Ephraim Mwangi Maina Kirinyaga (Ephraim Mwangi Maina)
* [ ] Margaret Kamar (Margaret Kamar)
* [ ] Samuel Poghisio (Prof Samuel Losuron Poghisio)
* [ ] Sara Paulata Korere (Sara Paulata Korere)
* [ ] Beatrice Kones (Beatrice Pauline Cherono Kones)
* [ ] Jayne Njeri Kihara (Jayne Njeri Wanjiru Kihara)
* [ ] Sophia Abdi Noor (Sophia Abdi Noor)
* [ ] Zuleikha Juma Hassan (Zuleikha Ju Ma Hassan )
* [ ] Roselinda Soipan Tuya (Roselinda Soipan Tuya)
