### ISSUE TITLE
Support multiple WriteInPublic instances being used from Pombola

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#2351]
With the current writeinpublic Django app in Pombola, you can only configure one instance to use, which is done in `general.yml-example`.

It would be nice instead if one could add new WriteInPublic instances in the Django admin, and be able to use different instances depending on which instance slug is used in the URL.

This probably means adding a model in `pombola/writeinpublic/models.py` a model that has fields for:
* The WriteInPublic instance's base URL
* The WriteInPublic owner's username
* The WriteInPublic API Key
* The WriteInPublic instance ID (and / or slug?)

**Comment by chrismytton** [comment]
As of https://github.com/mysociety/pombola/pull/2384 this is now possible.
