### ISSUE TITLE
[ZA] Make featured MP on homepage configurable

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2354]
We added a "featured MP" section to the homepage in #2349, but currently that person is hard-coded in the view.

https://github.com/mysociety/pombola/blob/32c1e6498e62792b00c0571936cdd627ea9f60de/pombola/south_africa/views/home.py#L28

We should make this configurable in the Django Admin so that PMG can update this without us having to do anything.

**Comment by chrismytton** [comment]
PA want the featured MP on the homepage to show the MP from the latest MP Corner blog post. This is tricky because the homepage now shows a Person instance from the DB, rather than an MP Corner blog post.

To make this work again I think we have three options:

1. Add a “feature on the featured profile section of the homepage” button to people in the admin
2. Add some metadata to the info pages to flag up who the blog post is about
3. Change the homepage so the “Meet your MPs” section shows an MP Corner post rather than a Person object from the DB

For reference https://github.com/mysociety/pombola/commit/c288e76d7d02176b505b93a2f26de8e2e758d031 was the commit that changed how this worked.

**Comment by JenMysoc** [comment]
Note from PMG: Yes you are 100% correct – we want the MP that feature on the homepage to show the MP from the latest MP corner blog. The first option sounds great, because we are happy that the  profile is linked rather than blog (which is on the profile after all). 

This is option 1!

**Comment by chrismytton** [comment]
It turns out Pombola already has a mechanism for flagging people to be featured on the homepage. I've changed the homepage view to use that in #2371.

## Flagging a person to be featured

In the admin there is a checkbox just above the biography section labelled "Can be featured". Checking this box and saving the person will make them appear as a featured person on the homepage.

<img width="718" alt="screen shot 2018-02-16 at 14 35 08" src="https://user-images.githubusercontent.com/22996/36312511-a99de992-1326-11e8-853e-6a95884f1203.png">

**NOTE**: If there is more than one person with this box checked then one of the people that can be featured will be chosen at random.

## Seeing all currently featured MPs

To see a list of people that can be featured on the homepage use the filter on the right hand side of the person listing page, "Filter by can be featured" (https://www.pa.org.za/admin/core/person/). Selecting "Yes" will only show the people that have the box checked. Then you can go in and uncheck the box for any people you want to stop featuring.

![image 2018-02-16 14-42-24](https://user-images.githubusercontent.com/22996/36312843-b27951b8-1327-11e8-9c08-abaf2da2c65b.png)
