### ISSUE TITLE
[ZA] Design tweaks for PMG homepage post WIP launch

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2358]
PMG have come back with a three small design change requests for the homepage design post WIP launch, these are:

- [x] 1. Can you change the wording to ‘Write to a MP’ (we just realised that the ‘write to’ function will only be to MPs and not to all three levels of representation).
- [x] 2. Can you make the ‘Write to a MP’ and ‘Write to a committee’ buttons  more prominent (bigger tabs and font). At least as big as the question ‘Do you have  a problem?’
- [x] 3. On the individual MP page, can we change the wording on the button to ‘Write a public message to this MP’

I think these should be relatively quick and uncontentious fixes.

**Comment by JenMysoc** [comment]
At the end of the week we're also hoping the committee write in public will be up and running so we'll need to activate the committees button too.

**Comment by chrismytton** [comment]
Text changed done in #2369

**Comment by chrismytton** [comment]
Bigger buttons added in https://github.com/mysociety/pombola/pull/2370 so I think this is done. Thanks @wrightmartin! 🎉
