### ISSUE TITLE
[ZA] /person/all list does not display content

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/pombola#2362]
eg at https://www.pa.org.za/person/all/

To recreate:

1. Visit any person page (eg https://www.pa.org.za/person/gijimani-jim-skosana/)
2. In the breadcrumb navigation click "politicians"

**Comment by zarino** [comment]
This came up in discussion with Gaile and Rashaad today.

It’s particularly annoying as the page is linked to prominently in the main nav bar (it’s the top level “People” link) – so we either need to fix the page, or stop it being linked to in the main nav.

**Comment by GeorgieBurr** [comment]
1 day

**Comment by chrismytton** [comment]
Looks like this was fixed as part of https://github.com/mysociety/pombola/pull/2580, yay! 🎉
