### ISSUE TITLE
[WriteInPublic] Fix homepage button

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2393]
Since doing #2386 the homepage buttons no longer fit on one line:

<img width="1065" alt="screen shot 2018-03-12 at 09 55 35" src="https://user-images.githubusercontent.com/22996/37277227-0664dd94-25dc-11e8-98e4-a00845db54cb.png">

The code for this is currently in this pull request: https://github.com/mysociety/pombola/pull/2380

**Comment by JenMysoc** [comment]
We've done a quick fix which looks like this:
![screen shot 2018-03-19 at 15 51 22](https://user-images.githubusercontent.com/4170351/37606497-819d456c-2b8d-11e8-9eeb-99613601889a.png)

However PMG would like to have the buttons back in one line with the question. They have suggested taking the "Do you" off the front of the question and moving the buttons and question closer together. One for Martino to think over I think.

**Comment by chrismytton** [comment]
For reference the quick fix was done in https://github.com/mysociety/pombola/commit/7b06fc16aa7197b2034f73246c9016869d02c1dd.

**Comment by zarino** [comment]
There’s a PR fixing this, here: https://github.com/mysociety/pombola/pull/2424
