### ISSUE TITLE
[ZA] Pull start and end dates into a spreadsheet for PMG

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2405]
PMG want to analyse attendance data for MPs; they've asked if we can pull out the start and end dates of MPs into an Excel spreadsheet of that data that is structured in a way that would allow Gaile to do some pivot table reports (or similar) to analyse days in parliament for MPs.

**Comment by jacksonj04** [comment]
@JenMysoc it's a little unclear on exactly what the requirements are here, so I've done a first pass (at https://gist.github.com/jacksonj04/0a56a86bddc399f5e60585e850122494), but there are still some questions such as:

* Does Gaile want _every_ MP, or only _current_ ones?
* Which date format is most useful? The current data doesn't always have an exact date or even month, so I've left it in the 'raw' variant for the time being but that might not be easily understandable by Excel.

If the data is useful as it is then hooray, but if not then let me know and it's a quick change to make it more so.

**Comment by gailefullard** [comment]
Thank you very much, Nick!

1. MP turnover rate in Parliament is perfect - although political party affiliation would be an important field to include i.e. looking at the health of the political party.
Megan will input the missing dates and will liaise with you once done. We are looking specifically at the Fifth Parliament starting 6 May 2014, so there are not many missing dates. 
However, we need to make a decision about the dates for MPs continuing from the Fourth Parliament (2009-2014). We will let you know. YYYY-MM-DD format would be great.

2. The second half of the request was accidentally left out. MP turnover rates per Committee i.e. looking at the health of the Committee. PA has recorded the start and end dates of an MP's committee membership. We would like to see per Committee from May 2014, a list of MPs with their start and end dates. If you can spare the time sometime - this would be wonderful. It is a hobbyhorse of one of the PMG board members, so it is quite important we can try and get this but there is no rush whatsoever.

**Comment by gailefullard** [comment]
Megan has finished inputting missing dates from 21 May 2014 which is the start date of Fifth Parliament.
We will edit the missing dates in the file you give us for earlier MPs continuing from the Fourth Parliament.

**Comment by jacksonj04** [comment]
Hi @gailefullard, @longhotsummer, I've updated the CSV at https://gist.github.com/jacksonj04/0a56a86bddc399f5e60585e850122494 with the new date format, party membership and updated dates from PA.

Anything else you need, give me a shout!

**Comment by gailefullard** [comment]
Thank you very much, Nick
