### ISSUE TITLE
[ZA] Add blurb text and Image to the page where people can select recipients

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2407]
On the new WriteInPublic tools, PMG would like to add a blurb for each of the tools to explain a little more about what they do.

We want to include a blurb  on the homepage/ 1st page of both tools:

 On the write to a committee page: https://www.pa.org.za/write-committees/recipients/

![screen shot 2018-03-19 at 16 03 36](https://user-images.githubusercontent.com/4170351/37607176-39a8cbf8-2b8f-11e8-90d2-4d0441d3b565.png)

The following text:

Write to a committee

 

A large part of the work of Parliament takes place in committees. There is a corresponding parliamentary committee for each government department. Committees pass law, scrutinise the work and expenditure of the government, and is a forum for public participation. Write to a committee if you want to bring attention to poor service delivery of a department or lobby it to introduce legislation that deals with your concerns.

 On the Write to an MP page: https://www.pa.org.za/write/recipients/

![screen shot 2018-03-19 at 16 03 52](https://user-images.githubusercontent.com/4170351/37607207-4bb5472c-2b8f-11e8-9b30-e8108cf44dfe.png)

The following text:

Write to an MP

 

Members of Parliament are the elected representatives of the people, they must be accountable to the people of South Africa and they must act in the public interest. Write to an MP if you want to petition or lobby him/her to assist you with a problem (no private disputes and only issues related to government services), offer suggestions or support a campaign you feel strongly about.

 

*Before you contact an MP, it is important to note that their ability to assist is limited. Often the right person to contact will be a local councillor, the Presidential Hotline, National Anti-Corruption Hotline, or the Public Protector. Also, most government departments have a Complaints Call Centre/Unit that you can approach first.

**Comment by JenMysoc** [comment]
PMG would also like the ability to add an image like a header image to both pages to make them more appealing.

**Comment by zarino** [comment]
https://github.com/mysociety/pombola/pull/2456 includes these changes:

# Write to an MP

![write-to-an-mp](https://user-images.githubusercontent.com/739624/43832250-ba831c40-9afe-11e8-811b-8d4a2cdda2db.png)

# Write to a committee

![write-to-a-committee](https://user-images.githubusercontent.com/739624/43832256-beb614e8-9afe-11e8-8984-88b52f2c4d83.png)

Right now they’re both re-using the same internal photo of the National Assembly [(from here)](https://www.pa.org.za/organisation/national-assembly/) – need to check whether the PMG folks had different images in mind.
