### ISSUE TITLE
[KE] Organise MP speech counts by year and display

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2408]
From Jessica: 

> [we want] Each MPs speech counts organised per year as we have realised most people don't care about the monthly entries. MPs that have served more than one term have no way of figuring out which years were more productive.

Example of current "Appearances" page for an MP: http://info.mzalendo.com/person/aden-duale/appearances/

We need to do some investigation with Jessica to find out:
How they want this to be displayed (eg as a number on the Reps profiles or as something else)
Where on the profile they'd want it to go (in the sidebar, in the box about parliamentary appearances). Finally we'd need to know if they want text by it and if that text might change. 

How do we currently calculate the speech counts - is this the script we run every year? If so we also need to know if it's still done once a year, but instead showing a yearly rather than monthly total?

**Comment by JenMysoc** [comment]
![screen shot 2018-05-09 at 10 44 13](https://user-images.githubusercontent.com/4170351/39808114-03fc4d0e-5376-11e8-870f-5e98bc04c89b.png)

The speech counts link to parliamentary appearances. These need to be overhauled so you can see:

* Number of speeches by year; currently if an MP has multiple terms it's really hard to see when they've said what in a given year - you have to add up per month. Most people are more interested in a yearly count! 

![screen shot 2018-05-09 at 10 47 59](https://user-images.githubusercontent.com/4170351/39808325-7f2e0ecc-5376-11e8-9b99-30dbc19fe2e7.png)

![screen shot 2018-05-09 at 10 47 59](https://user-images.githubusercontent.com/4170351/39808830-eae302ac-5377-11e8-9496-7af5ff1d7d61.png)

![screen shot 2018-05-09 at 10 44 13](https://user-images.githubusercontent.com/4170351/39808841-ef32c630-5377-11e8-9be6-bd8a6d4b4212.png)

And if you actually want to see the speeches made in a year you have to go through the "view all speeches" bit as you can't click on the month and get to them. 

* Jessica wants to be able to rank/order speeches by topic and by importance. This will need to be done by them in the admin I think, but if there's a way of automatically pulling topics out this would make this easier. 

* Jessica also wants to be able to link to replies - wondering if SayIt would be useful here for their hansard to make this easier?

**Comment by emilydrk** [comment]
Estimate: 1-2 days.

**Comment by GeorgieBurr** [comment]
By end of Jan if possible, if not we need to communicate  that we can't do this to Jessica
