### ISSUE TITLE
[ZA] Same person is returned multiple times from Term page

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/pombola#2414]
e.g. on https://www.pa.org.za/position/member/parliament/national-assembly/?page=41&session=na26, Thembi Majola is listed twice:

![screen shot 2018-04-09 at 14 39 14](https://user-images.githubusercontent.com/57483/38500997-ccf1505e-3c03-11e8-84c4-0abcc901d2ff.png)

**Comment by jacksonj04** [comment]
This was actually a fault in the underlying data - Thembi Majola had the same "Member of the National Assembly" position listed twice with identical details.
