### ISSUE TITLE
[ZA] Export dates of committee memberships from May 2014

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/pombola#2418]
From #2405 

> The second half of the request was accidentally left out. MP turnover rates per Committee i.e. looking at the health of the Committee. PA has recorded the start and end dates of an MP's committee membership. We would like to see per Committee from May 2014, a list of MPs with their start and end dates. If you can spare the time sometime - this would be wonderful. It is a hobbyhorse of one of the PMG board members, so it is quite important we can try and get this but there is no rush whatsoever.

**Comment by longhotsummer** [comment]
Hi @jacksonj04 -- we just chatted with @gailefullard from PMG and she mentioned she would still like this data to be able to move forward with the analysis of MP memberships from #2405.

Would it be possible to extract committee membership information, MP names and dates, from PA?

Thanks,
Greg

**Comment by jacksonj04** [comment]
Hi @longhotsummer, @gailefullard, sorry this took so long to get around to!

I've exported all the committee members currently in PA, available at https://gist.github.com/jacksonj04/787dcf9d64474e77e46adfcadbb10a2f. Hopefully this meets your requirements, but if you need anything else please don't hesitate to give me a shout!

**Comment by gailefullard** [comment]
Hi Nick 

 

It is a bit of a disappointment. From the CSV file, it is apparent that the PA programming does not retain the date and name of committee changes by MPs over time.

It merely overwrites the name of the Committee and does not record the date change.

 

We will have to consult the original daily parliamentary papers to obtain this info.

 

Thanks for all you help on these two projects.

 

cheers

Gaile

**Comment by jacksonj04** [comment]
@gailefullard Whoops! That didn't sound right, so I went back in and discovered I'd accidentally missed out a whole load of different _types_ of committee. I've re-run the export and there are now far more entries, which might be more useful: https://gist.github.com/jacksonj04/787dcf9d64474e77e46adfcadbb10a2f
