### ISSUE TITLE
[KE] MP/representative list page redesign

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#2423]
Main thing for the rest of the site is to have MPs/Parliamentarians displayed in a picture grid format with their name and area underneath. 

Current look:

![screen shot 2018-05-09 at 10 44 13](https://user-images.githubusercontent.com/4170351/39812597-30dd8c34-5385-11e8-9c23-ead25194d9e5.png)

but from what she's described it sounds more like the Mac file preview grid format is what she wants:

![screen shot 2018-05-09 at 12 34 45](https://user-images.githubusercontent.com/4170351/39812665-75eb0734-5385-11e8-94f7-c1bd5e335e36.png)

**Comment by zarino** [comment]
Is this any different to the existing "View as grid" option on the MP list page? http://info.mzalendo.com/position/member-national-assembly/?view=grid

(Other than adding job titles, and making the grid the default choice?)

**Comment by JenMysoc** [comment]
@JessMusila Is Zarino on the right track?

**Comment by JessMusila** [comment]
Yap. Looks good.

**Comment by JenMysoc** [comment]
@JessMusila great! Shall we make the grid view the default view for Mzalendo MP list page and then we can add in the job titles and area underneath their picture?

**Comment by JessMusila** [comment]
Sure. I think it looks better.
