### ISSUE TITLE
[KE] Mzalendo online user survey

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2446]
From #2421:

> Jessica would like to run some user research via a survey on the site to get an idea of what people want to see more/less of (maybe @zarino @wrightmartin @ajparsons would have some ideas on what/how to do this?)

More details, from last week’s call with Jessica and Abiud:

* Survey needs to ask for gender, age, profession, place of origin (County, constituency, ward), and place of residence (County, constituency, ward) if not the same.

* Ask what their favourite part of the website is, what information about parliament they’d like to see more of, parts of Mzalendo they feel could be improved, where else they source information about politicians from, and where they heard about Mzalendo (workshop, twitter, facebook, instagram, radio, tv, newspaper, newsletter, academic journal, other).

* Links to survey wherever feels appropriate on Mzalendo – in the footer perhaps? Maybe an additional "Help us understand you!" type banner somewhere on the homepage?

**Comment by ajparsons** [comment]
This was being separately detailed here: https://github.com/mysociety/research/issues/141

Survey is complete: https://www.surveygizmo.com/s3/4482783/Mzalendo-2018-Survey
