### ISSUE TITLE
[KE] Look at Google Index link to Mzalendo

### ISSUE THREAD

**Issue by GeorgieBurr** [mysociety/pombola#2472]
Jessica says that speeches on Mzalendo Hansard aren’t being picked up on Google index and so speeches are not showing up in Google search results.

**Comment by jacksonj04** [comment]
Hansard pages appear to be covered by the Google Index, it just may be that they don't rank particularly highly for the keyword combinations.

Is there an example available of a specific query or page which is showing this problem?

**Comment by GeorgieBurr** [comment]
Hansard definitely _is_ getting indexed by Google - https://www.google.com/search?q=“SENATE+DEBATES+1+PARLIAMENT+OF+KENYA+THE+SENATE+THE+HANSARD”

**Comment by emilydrk** [comment]
Explain SEO to Jessica and how to use Google search.

**Comment by GeorgieBurr** [comment]
@zarino  explained SEO to Jimmy and Jessica.
But Jessica then linked this back to #2420 and #2408
