### ISSUE TITLE
[KE] Update Hansard scraper to handle constituency+party MP references

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2473]
@JessMusila says Kenyan Parliament has changed how they present MPs’ names in Hansard. It sounds like some of the time (all of time?) MPs are simply referred to by their constiuency name and the initials of their party, rather than by full name.

I think Jessica said her team has gone through and manually fixed some of the past Hansard entries, but it sounds like our scraper needs to be updated to recognise the right speakers without manual intervention.

**Comment by dracos** [comment]
Just to note we had a call with Kenyan Hansard who were interested in working with Mzalendo/better display of Hansard, so possibility is there of asking them to change it back? ;) But yes, handling it probably a better solution if possible.

**Comment by JessMusila** [comment]
Hi Matthew,

They still have some fine tuning to do but we actually like the new format.
It resolves the problem of distinguishing MPs with similar names that we
have faced in past years.

Regards,

Jessica

*Jessica *
*Musila, Executive Director, Mzalendo Trust, P. O. Box 21765 00505 Ngong
Road, Nairobi, Tel. 0726464063Email: jessica@mzalendo.com
<jessica@mzalendo.com>, Skype: Jessica.Musila, Twitter: mzalendowatch (w)
Africanvigil (p), www.mzalendo.com <http://www.mzalendo.com>*

**Comment by emilydrk** [comment]
Estimate: 5+ days. Need to research and plan this.

**Comment by chrismytton** [comment]
Still some more to do on this:

- [ ] Handle place names that don't exactly match Hansard, e.g. `Ijara` in Hansard, [`Ijara - 2017`](http://info.mzalendo.com/place/ijara-2017/) on Mzalendo
- [ ] Fix Women's Representatives counties, currently they are members of the counties that belong to the Senate, but they need to be members of county objects that are specific to the National Assembly
- [ ] Add aliases, or handle somehow, the 7 people that are "Nominated" (see below)
- [ ] Make sure entries that can't be matched because of a mistake in Hansard are clearly flagged in the admin somewhere
- [ ] Document how to add a new mapping for party initials in Hansard

### Nominated people

|House|Hansard name|Hansard title|
| ----------------- | ----------------- | ----------------------------- |
| National Assembly | Nominated, ANC    | Hon. Godfrey Osotsi           |
| National Assembly | Nominated, FORD-K | Hon. (Ms.) Nasri Ibrahim      |
| National Assembly | Nominated, ODM    | Hon. (Ms.) Dennitah Ghati     |
| National Assembly | Nominated, ODM    | Hon. (Prof.) Jacqueline Oduol |
| National Assembly | Nominated, ODM    | Hon. (Prof.) Jacquiline Oduol |
| National Assembly | Nominated, ODM    | Hon. Wilson Sossion           |
| National Assembly | Nominated, WDM-K  | Hon. Sammy Seroney            |

**Comment by JessMusila** [comment]
@chrismytton

Following is the list of all the Nominated Members in the National assembly, their parties  and the interests they represent. May be you can distinguish them by their special interest.

1. David ole Sankok - Jubilee Party - Persons With Disabilities (PWDs)
2. Mucheke Halima Yussuf - Jubilee Party - Workers
3. Gideon Keter - Jubilee Party - Youth
4. Jeniffer Shamala - Jubilee Party - Special Interest
5. Maina Kamanda - Jubilee Party - Special Interest
6. Cecily Mbarire - Jubilee Party - Special interest
7. Prof. Jacquiline Oduol - ODM - Marginalised Communities
8. Wilson Sossion - ODM - Workers
9. Dennitah Ghati - ODM - Persons With Disabilities (PWDs)
10. Godfrey Osotsi - Amani National Congress - workers
11. Nasri Sahal Ibrahim - Ford Kenya - Marginalised groups
12. Sammy Seroney - WDM-K - Workers

**Comment by JessMusila** [comment]
Nominated Senators with a special interest:
1. Victor Prengei - Jubilee Party - Youth
2. Mercy Chebeni - ODM - Youth
3. Isaack Mwaura - Jubilee Party - PWDs
4. Getrude Musuruve Inimah - ODM - PWD

**Comment by JessMusila** [comment]
@chrismytton 

Nominated Women Senators & their parties (Affirmative Action seats) - 16

1. Beth Mugo - Jubilee Party 
2. Alice Chepkorir Milgo - Jubilee Party
3. Millicent Omanga - Jubilee Party
4. Christine Zawadi Gona - Jubilee Party
5. Mary Yiane Senata - Jubilee Party
6. Falhada Dekow Iman - Jubilee Party
7. Naomi Jilo Wago - Jubilee Party
8. Farhiya Ali Haji - Jubilee Party
9. Agnes Zani - ODM
10. Judith Ramaita Pareno - ODM
11. Beatrice Kwamboka Makori - ODM
12. Naomi Shiyonga Masitsa - ODM
13. Rose Ogendo Nyamunga - ODM
14. Petronila Were Lokorio - ANC
15. Abshiro Soka Halake - KANU
16. Sylvia Mueni Kasanga - WDM-K

**Comment by JessMusila** [comment]
I am investigating constituencies that changed names in 2017. I will advise tomorrow.

**Comment by chrismytton** [comment]
Great, thanks for that info @JessMusila, very useful.

**Comment by JessMusila** [comment]
@chrismytton Please send us the list of constituency names that are problematic. We have called our electoral boundaries commission and they learnt they don't have a list of constituencies that changed names  so we have cross-check each problematic name for you. 

I believe all constituencies names for the 2017 election have the said year at the end eg. Ijara_2017 so that should not be a problem. 

Our research so far shows, in the last election the following constituencies changed names:
i) Mbita became Suba North
ii) Gwasi became Suba South.

**Comment by chrismytton** [comment]
> Please send us the list of constituency names that are problematic.

@JessMusila These were just the constituencies in Mzalendo that had " - 2017" at the end of their name. I've manually removed that from the end of the name and those entries are matching fine now.

I've done a few other fixes, which has matched lots more people this week, but there's still a few outstanding bits that I was hoping to get to but haven't quite had the time for this week. I will send you a more complete update next week.

**Comment by chrismytton** [comment]
@JessMusila I'm pleased to report that all of the "simple" matches are now done.

There are still a few dozen speeches that haven't been matched up, but they are due to either errors in Hansard or errors in Mzalendo. I'm going through them one by one to see what the problems are.

One of the problems I've noticed is that on the official site [Hon. Oyoo, James Onyango](http://www.parliament.go.ke/the-national-assembly/hon-oyoo-james-onyango) is listed as being in the ODM party, but on Mzalendo [James Onyango Oyoo](http://info.mzalendo.com/person/james-onyango-oyoo/) is listed as being in the PDP party. Do you know which of these is correct?

**Comment by chrismytton** [comment]
@JessMusila Similarly Enoch Kibunguchy is listed as ANC on Mzalendo, but FORD-K on the official site:

- http://info.mzalendo.com/person/enoch-kibunguchy/
- http://www.parliament.go.ke/node/3277

Do you know which of these is correct?

**Comment by JessMusila** [comment]
@chrismytton I see what you mean. Our information was from the Gazette notice of all elected and nominated MPs from the 2017 election. 

However, since the profiles of the MPs are synched as per the entries used by Parliament's hansard team, we can update the MPs profiles with the information the National Assembly and Senate is using. 

Kindly send the entire list of MP profiles with errors so we can update accordingly. I have corrected Enoch Kibunguchy's profile. 

I was not able to update Jame Onyango Oyoo's profile as the system threw me out. I got a message that my connection isn't private.

**Comment by chrismytton** [comment]
@JessMusila Here's a list of the remaining errors with Mzalendo data that need to be resolved. Once these have been fixed let me know and I will re-run the Hansard name matching script. Then I will be able to generate the speech counts for you (#2550).

## Place issues

- [ ] Couldn't find place for "Kitutu Chache South, FORD-K"
  - Mzalendo doesn't seem to have a "Kitutu Chache South" for 2017 onwards? Is this an error in Hansard or Mzalendo?

## Position issues

- [ ] Couldn't find position for "Sabatia, ANC"
  - Alfred Agoi Masadia's position object has an end date of "2017", despite speaking in a sitting on 2018-07-05 - http://info.mzalendo.com/admin/core/position/45057/ does the end date need to be removed from this position?

## Party issues

For each of the items below the name according to Hansard is shown, "Baringo CWR, JP" for the first item, then I've also written what's currently in Mzalendo, e.g. KANU for the first item.

I need you to go through each of these and confirm if the party in Hansard is correct, and if it is update Mzalendo to reflect that.

- [ ] Couldn't find matching party for Baringo CWR, JP, initials: [u'CWR', u'JP'], URL: http://info.mzalendo.com/person/gladwell-jesire-cheruiyot/
  - Shown as KANU on Mzalendo
- [ ] Couldn't find matching party for Embakasi South, ODM, initials: [u'ODM'], URL: http://info.mzalendo.com/person/julius-musili-mawathe-2/
  - Shown as WDM-K on Mzalendo
- [ ] Couldn't find matching party for Emuhaya, ODM, initials: [u'ODM'], URL: http://info.mzalendo.com/person/jeremiah-omboko-milemba/
  - Shown as ANC on Mzalendo
- [ ] Couldn't find matching party for Endebess, ODM, initials: [u'ODM'], URL: http://info.mzalendo.com/person/robert-pukose/
  - Shown as JP on Mzalendo
- [ ] Couldn't find matching party for Funyula, ANC, initials: [u'ANC'], URL: http://info.mzalendo.com/person/wilberforce-ojiambo-oundo-2/
  - Shown as ODM on Mzalendo
- [ ] Couldn't find matching party for Homa Bay CWR, JP, initials: [u'CWR', u'JP'], URL: http://info.mzalendo.com/person/gladys-atieno-nyasuna/
  - Shown as ODM on Mzalendo
- [ ] Couldn't find matching party for Ikolomani, ANC, initials: [u'ANC'], URL: http://info.mzalendo.com/person/benard-masaka-shinali/
  - Shown as JP on Mzalendo
- [ ] Couldn't find matching party for Kajiado CWR, JP, initials: [u'CWR', u'JP'], URL: http://info.mzalendo.com/person/janet-marania-teiyaa/
  - Shown as TNA on Mzalendo
- [ ] Couldn't find matching party for Kimilili, FORD-K, initials: [u'FORD-K'], URL: http://info.mzalendo.com/person/didmus-wekesa-barasa-mutua/
  - Shown as JP on Mzalendo
- [ ] Couldn't find matching party for Kisii CWR, JP, initials: [u'CWR', u'JP'], URL: http://info.mzalendo.com/person/janet-ongera/
  - Shown as ODM on Mzalendo
- [ ] Couldn't find matching party for Meru CWR, Independent, initials: [u'CWR', u'Independent'], URL: http://info.mzalendo.com/person/kawira-mwangaza-mwenda/
  - Shown as JP/MP on Mzalendo
- [ ] Couldn't find matching party for Narok South, ODM, initials: [u'ODM'], URL: http://info.mzalendo.com/person/korei-ole-lemein/
  - Shown as JP on Mzalendo
- [ ] Couldn't find matching party for Samburu North, KANU, initials: [u'KANU'], URL: http://info.mzalendo.com/person/alois-musa-lentoimaga/
  - Shown as JP on Mzalendo
- [ ] Couldn't find matching party for Suba North, FORD-K, initials: [u'FORD-K'], URL: http://info.mzalendo.com/person/millie-odhiambo-mabona/
  - Shown as ODM on Mzalendo

**Comment by JessMusila** [comment]
@chrismytton on it this afternoon.

**Comment by JessMusila** [comment]
@chrismytton Response to Query 1 follow:
I have created the Kitutu chache south constituency. See: http://info.mzalendo.com/admin/core/place/2588/?_changelist_filters=q%3DKitutu%2BChache%2BSouth

The MP is Richard Onyonka
See: http://info.mzalendo.com/admin/core/person/128/?_changelist_filters=q%3DRichard%2BOnyonka

This constituency did not have an election in August 2017 as one of the candidates died. Their by-election happened in November 2017. I didn't realise their profile was not properly updated.

**Comment by JessMusila** [comment]
@chrismytton Response to query 2 follows:

Alfred Agoi Masadia is the MP for Sabatia under the Amani National Congress (ANC) party.
The 2017 end date was an error

**Comment by JessMusila** [comment]
@chrismytton 
Following is the list of MPs whose profiles needed some changes:
1. Funyula MP - He has two profiles. Kindly merge: http://info.mzalendo.com/admin/core/person/1474/?_changelist_filters=q%3DWilberforce%2BOjiambo%2BOundo
and http://info.mzalendo.com/person/wilberforce-ojiambo-oundo-2/
His current party is ODM as listed on both sites.

2. Kajiado CWR, JP http://info.mzalendo.com/admin/core/person/?q=Janet+Marania+Teiyaa 
Mzalendo lacked an entry listing her as member of the Jubilee Party. We closed the TNA entry and created the JP one. 

Please merge her two profiles: http://info.mzalendo.com/person/janet-marania-teiyaa/ and http://info.mzalendo.com/person/janet-marania-teyiaa/ The main difference is in how her last name is spelt. Please use **Teyiaa** not Teiyaa. 

3. Meru CWR - Kawira Mwangaza - was incorrectly listed under JP on Mzalendo. We have changed that to Independent. See http://info.mzalendo.com/admin/core/person/1325/?_changelist_filters=q%3DKawira%2BMwangaza

The following list of MPs are correctly listed on both Mzalendo and Parliament website. The entries also match the gazette. Hansard entries are the ones with errors. We choose to ignore for now and bring it to the attention of the hansard team. 

a) The Baringo, CWR is listed as KANU member on both Parliament and our website. Hansard team has JP as the party which is an error. We will ignore the entry as her profile has actually been replicating ok.
b) The Embakasi South, MP - Julius Mawathe - is listed Wiper Democratic Party - Kenya (WDM-K) on both our sites. 
c) The Emuhaya, MP - Jeremiah Omboko - is listed under ANC on both sites too.
d) The Endebess, MP - Robert Pukose - is listed under Jubilee party on both websites.
e) The Homabay CWR - Gladys Nyasuna - is correctly listed as a member of ODM.
f) Ikolomani, - Benard Shinali is correctly listed under Jubilee Party (JP)
g) Kimilili - Didmus Barasa Mutua is correctly listed under JP. 
h) Kisii CWR - Janet Ongera - is correctly listed under ODM. 
i) Narok South - Korei Ole Lemein - is correctly listed under Jubilee Party (JP)
j) Samburu North - Alois Musa Lentoimaga - is correctly listed under Jubilee Party (JP)
k) Millie Odhiambo's profile has ODM as party on both Mzalendo and Parliament -http://info.mzalendo.com/admin/core/person/376/ changelist_filters=q%3DMillie%2BOdhiambo%2BMabona

**Comment by JessMusila** [comment]
@chrismytton Please note I added the MP of - Baringo South - who was elected through a by election in August 2018 after the death of the previous MP last year 
http://info.mzalendo.com/admin/core/person/1202/?_changelist_filters=q%3DCharles%2BKamuren

His profile does not seem to sync properly with his hansard mentions. I matched his profile with some entries among the aliases.

**Comment by JessMusila** [comment]
@chrismytton 

As you compile Mzalendo data remember National Assembly should have 349 members and in the Senate 67.

**Comment by chrismytton** [comment]
> Following is the list of MPs whose profiles needed some changes:
> 
> 1. Funyula MP - He has two profiles. Kindly merge: http://info.mzalendo.com/admin/core/person/1474/?_changelist_filters=q%3DWilberforce%2BOjiambo%2BOundo
>    and http://info.mzalendo.com/person/wilberforce-ojiambo-oundo-2/
>    His current party is ODM as listed on both sites.
> 2. Kajiado CWR, JP http://info.mzalendo.com/admin/core/person/?q=Janet+Marania+Teiyaa
>    Mzalendo lacked an entry listing her as member of the Jubilee Party. We closed the TNA entry and created the JP one.
> 
> Please merge her two profiles: http://info.mzalendo.com/person/janet-marania-teiyaa/ and http://info.mzalendo.com/person/janet-marania-teyiaa/ The main difference is in how her last name is spelt. Please use **Teyiaa** not Teiyaa.
> 
> 1. Meru CWR - Kawira Mwangaza - was incorrectly listed under JP on Mzalendo. We have changed that to Independent. See http://info.mzalendo.com/admin/core/person/1325/?_changelist_filters=q%3DKawira%2BMwangaza

👍 done

> @chrismytton Please note I added the MP of - Baringo South - who was elected through a by election in August 2018 after the death of the previous MP last year
> http://info.mzalendo.com/admin/core/person/1202/?_changelist_filters=q%3DCharles%2BKamuren
> 
> His profile does not seem to sync properly with his hansard mentions. I matched his profile with some entries among the aliases.

Can you give me a link to an example of a Hansard speech not matching? The only unmatched speeches I can see in the database are for `The Member for Baringo South`, which we're not handling currently because they don't mention the party name, so you'll need to add an alias for that.

**Comment by JessMusila** [comment]
@chrismytton Kindly link the 'The member for Baringo South' with Charles Kamuren's profile.

**Comment by chrismytton** [comment]
> @chrismytton Kindly link the 'The member for Baringo South' with Charles Kamuren's profile.

Done.

@JessMusila I've also created aliases for a few other places that have incorrect place names in Hansard. You can see them [in the admin](http://info.mzalendo.com/admin/hansard/alias/?o=-4.1), that link is sorted by date created, so it shows the most recent aliases first. The aliases created today (13 Mar 2019) are the new ones, some of them are false-positives, but there are quite a few which are genuine and need to be manually matched to a person, e.g. "South Suba, ODM", which is a Hansard error, should be "Suba South, ODM".

Let me know once you've gone through those new aliases then I think we will be able to finally close this ticket!

**Comment by JessMusila** [comment]
@Chrismytton Done.

**Comment by chrismytton** [comment]
@JessMusila Perfect, thanks! I _think_ this issue can now be closed. If you spot any obvious issues then let us know and we'll look into it. Thanks again for your help getting the data issues resolved!
