### ISSUE TITLE
[ZA] Enable places to have a .primary_image method

### ISSUE THREAD

**Issue by zarino** [mysociety/pombola#2496]
Currently, places cannot have an image associated with them, which is why we get the grey push pins on pages like eg: https://www.pa.org.za/place/is/province/.

PMG have supplied some images for these 9 provinces, so it’d be good to display them.

The quick, hacky solution is to hard-code the images into the source code. But it seems more logical that the images should be added via the Django admin, just like the images for organisations and people.

This will require a developer to modify the model for places, to add a `primary_image` field.

Required for #2476.

**Comment by GeorgieBurr** [comment]
2 days
