### ISSUE TITLE
[KE] Add twitter and opengraph meta tags to pombola pages and wordpress blog posts

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2497]
Add the necessary markup for [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) and [Facebook Open Graph ](https://developers.facebook.com/docs/sharing/webmasters/#markup) so that when links to Mzalendo are shared on Twitter it comes up with a preview.

This request came in from Abiud today.

**Comment by zarino** [comment]
Remember this change will need to be made in the Mzalendo wordpress theme (orgsites), _as well_ as in Pombola.

**Comment by zarino** [comment]
I’ve started a branch for these changes: #2499.

@chrismytton it’d be good to have a quick chat, when you’re next available, over the simplest way to automatically generate sensible titles and descriptions for pages via the views (or something?) so that we don’t have to add new blocks to the top of every template.

**Comment by emilydrk** [comment]
Title of each page is difficult to reuse. Will take some effort to sort that out. Estimate: 1-2 days.

**Comment by chrismytton** [comment]
Had another request for this from Abiud today. They are now asking specifically about the blog (i.e. the Wordpress install), not the Django site. So I think we can get a quick-ish win by getting the appropriate plugin working for the Mzalendo blog.

**Comment by chrismytton** [comment]
Looks like [this plugin](https://en-gb.wordpress.org/plugins/wonderm00ns-simple-facebook-open-graph-tags/) is already installed on the main Wordpress install, but it's not currently working for Mzalendo. I _think_ this is because we're not calling `wp_head();` in `header.php`, but my Wordpress is a bit rusty, so not totally sure.

@zarino Do you think you might have a moment to look at this at some point?

**Comment by zarino** [comment]
@chrismytton yep, that will fix it for the blog. Here’s a PR: https://github.com/mysociety/orgsites/pull/1065

**Comment by chrismytton** [comment]
@zarino Thanks! Those changes have been deployed now. So blog posts shared on Twitter and Facebook should now have previews:

### Twitter

<img width="531" alt="screen shot 2018-11-22 at 16 20 01" src="https://user-images.githubusercontent.com/22996/48914177-90556c80-ee72-11e8-956c-54493c73b93f.png">


### Facebook

![image](https://user-images.githubusercontent.com/22996/48914121-73209e00-ee72-11e8-9167-8b0e62077da7.png)
