### ISSUE TITLE
Send Jessica data on Surveys

### ISSUE THREAD

**Issue by GeorgieBurr** [mysociety/pombola#2538]
On Catch up call Jessica mentioned the need for data from the surveys... Zarino if you could add more info, that would be great!

**Comment by chrismytton** [comment]
More info: Jessica would like the data from the survey that ran on the homepage until the end of November 2018, and was removed in 3f56c502b6ff6dcff970990a0327205adae7afa9. This data is in Survey Gizmo. Hopefully we can export it from Survey Gizmo and send it over.

**Comment by chrismytton** [comment]
Exported the latest data from SurveyGizmo and sent it to Jessica.
