### ISSUE TITLE
[KE] Send 2017 - 2018 speech counts to Mzalendo

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2550]
Mzalendo have requested we send them speech counts for the following date range:

Start: 31 August 2017
End: 31 December 2018

The command needed to do this can be found in the previous issue about this: https://github.com/mysociety/pombola/issues/2282#issuecomment-312352442

**Comment by chrismytton** [comment]
Getting an error when running the command against the production database:

```
$ ./manage.py kenya_hansard_speech_statistics --date-from=2017-08-31 --date-to=2018-12-31
Generating all-speakers.csv
speaker: John Olago Aluoch speeches: 49
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    execute_from_command_line(sys.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/vhost/mzalendo.mysociety.org/pombola-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/kenya/management/commands/kenya_hansard_speech_statistics.py", line 170, in handle
    position_results = self.position_data(speaker, date_midpoint, position_data_cache)
  File "/data/vhost/mzalendo.mysociety.org/pombola/pombola/kenya/management/commands/kenya_hansard_speech_statistics.py", line 87, in position_data
    raise MultipleMembershipsException, message
pombola.kenya.management.commands.kenya_hansard_speech_statistics.MultipleMembershipsException: Multiple party_membership memberships found for John Olago Aluoch: [u'Ford Kenya', u'Forum For The Restoration Of Democracy']
```

So will need to resolve that first.

**Comment by chrismytton** [comment]
Looks like [Forum For The Restoration Of Democracy](http://info.mzalendo.com/organisation/ford/) (9 related people) is actually a duplicate of [Ford Kenya](http://info.mzalendo.com/organisation/ford-kenya/) (609 related people), so I've fixed the problem with John Olago Aluoch by removing their u'Forum For The Restoration Of Democracy membership.

But we're not quite finished yet! I'm now getting another similar error for a different person.

> Multiple party_membership memberships found for **Cecily Mutitu Mbarire: [u'Jubilee Party', u'The National Alliance (TNA)']**

**Comment by chrismytton** [comment]
It seems the previous error has been fixed during the work we've done in https://github.com/mysociety/pombola/issues/2473.

However I'm now getting a new error:

> Multiple party_membership memberships found for Maina Kamanda: ['The National Alliance (TNA)', 'Jubilee Party']

@JessMusila Should [Maina Kamanda](http://info.mzalendo.com/person/maina-kamanda/) be a member of both of those parties, or should the membership at TNA have an end date on it? He's only listed as being in JP on [parliament's site](http://www.parliament.go.ke/index.php/node/3259).

**Comment by JessMusila** [comment]
@chrismytton TNA was his former party. I have closed his term there. See: http://info.mzalendo.com/person/maina-kamanda/experience/

**Comment by chrismytton** [comment]
@JessMusila I'm afraid there are actually quite a few other people who have multiple party positions listed in Mzalendo. I've listed them below. These need to be fixed, otherwise the party counts will be incorrect.

A couple of pointers:

- There shouldn't be any overlapping party positions, so if there's a position that ends "August 9th 2017" and another that starts "August 2017" you you might need to make the "August 2017" date more specific.
- Party positions should *not* have places associated with them, only governmental positions should have places associated.

Here's the full list, with links to the admin page for each person. Please can you check through the below problems, thanks!

- [ ] [Aaron Kipkirui Cheruiyot](http://info.mzalendo.com/admin/core/person/13165/) (Jubilee Party, Jubilee Party)
- [ ] [Adan Wehliye Keynan](http://info.mzalendo.com/admin/core/person/41/) (Jubilee Party, Orange Democratic Movement)
- [ ] [Anthony Kimani Ichung'Wah](http://info.mzalendo.com/admin/core/person/1835/) (The National Alliance (TNA), Jubilee Party)
- [ ] [Athanas Misiko Wafula Wamunyinyi](http://info.mzalendo.com/admin/core/person/291/) (Ford Kenya, Forum For The Restoration Of Democracy)
- [ ] [Caleb Amisi Luyai](http://info.mzalendo.com/admin/core/person/2740/) (Orange Democratic Movement, Kenya National Congress)
- [ ] [Catherine Nanjala Wambilianga](http://info.mzalendo.com/admin/core/person/523/) (Ford Kenya, Ford Kenya)
- [ ] [Cecily Mutitu Mbarire](http://info.mzalendo.com/admin/core/person/78/) (Jubilee Party, The National Alliance (TNA))
- [ ] [Chrisantus Wamalwa Wakhungu](http://info.mzalendo.com/admin/core/person/1889/) (Ford Kenya, Forum For The Restoration Of Democracy)
- [ ] [Elsie Busihile Muhanda](http://info.mzalendo.com/admin/core/person/628/) (Orange Democratic Movement, Federal Party of Kenya)
- [ ] [Enoch Wamalwa Kibunguchy](http://info.mzalendo.com/admin/core/person/294/) (Ford Kenya, Ford Kenya)
- [ ] [Faith Wairimu Gitau](http://info.mzalendo.com/admin/core/person/974/) (Farmers Party, Jubilee Party)
- [ ] [Ferdinard Kevin Wanyonyi](http://info.mzalendo.com/admin/core/person/2065/) (Ford Kenya, Forum For The Restoration Of Democracy)
- [ ] [Godana Hargura](http://info.mzalendo.com/admin/core/person/827/) (Jubilee Party, Orange Democratic Movement)
- [ ] [Halima Yussuf Mucheke](http://info.mzalendo.com/admin/core/person/845/) (Jubilee Party, Grand National Union)
- [ ] [James Lusweti Mukwe](http://info.mzalendo.com/admin/core/person/1641/) (Ford Kenya, Forum For The Restoration Of Democracy)
- [ ] [Janet Nangabo Wanyama](http://info.mzalendo.com/admin/core/person/1076/) (Jubilee Party, New Ford Kenya)
- [ ] [Johana Ngeno Kipyegon](http://info.mzalendo.com/admin/core/person/1453/) (Kenya African National Union, Kenya National Congress)
- [ ] [John Oroo Oyioka ](http://info.mzalendo.com/admin/core/person/1257/) (Kenya African National Union, Peoples Democratic Party  Traditional)
- [ ] [Joyce Kamene](http://info.mzalendo.com/admin/core/person/795/) (Chama Cha Uzalendo, Wiper democratic Movement Kenya)
- [ ] [Liza Chelule](http://info.mzalendo.com/admin/core/person/13126/) (Jubilee Party, United Republican Party (URP))
- [ ] [Martha Wangari](http://info.mzalendo.com/admin/core/person/13123/) (United Democratic Forum Party (UDF), Jubilee Party)
- [ ] [Mary Yiane Senata](http://info.mzalendo.com/admin/core/person/611/) (Jubilee Party, The National Alliance (TNA))
- [ ] [Mishi Juma Khamisi](http://info.mzalendo.com/admin/core/person/874/) (Orange Democratic Movement, Orange Democratic Movement)
- [ ] [Rahab Mukami Wachira](http://info.mzalendo.com/admin/core/person/983/) (Grand National Union, Jubilee Party)
- [ ] [Rehema Dida Jaldesa](http://info.mzalendo.com/admin/core/person/601/) (United Republican Party (URP), Jubilee Party)
- [ ] [Rozaah Akinyi Buyu](http://info.mzalendo.com/admin/core/person/1950/) (Orange Democratic Movement, Orange Democratic Movement)
- [ ] [Ruweida Mohamed Obo](http://info.mzalendo.com/admin/core/person/786/) (The National Alliance (TNA), Jubilee Party)
- [ ] [Shariff Athman Ali](http://info.mzalendo.com/admin/core/person/2100/) (Jubilee Party, United Democratic Forum Party (UDF))
- [ ] [Silvanus Osoro Onyiego](http://info.mzalendo.com/admin/core/person/1417/) (Kenya National Congress, Progressive Party of Kenya)
- [ ] [Sylvia Mueni Kasanga](http://info.mzalendo.com/admin/core/person/13185/) (Wiper democratic Movement Kenya, Wiper democratic Movement Kenya)
- [ ] [Thaddeus Kithua Nzambia](http://info.mzalendo.com/admin/core/person/13375/) (Wiper democratic Movement Kenya, Muungano Development Movement Party (MDM))
- [ ] [Tum Tecla Chebet](http://info.mzalendo.com/admin/core/person/913/) (Kenya African National Union, Jubilee Party)
- [ ] [Vincent Musyoka Musau](http://info.mzalendo.com/admin/core/person/2440/) (Maendeleo Chap Chap Party, Chama Cha Uzalendo)

**Comment by JessMusila** [comment]
@Chrismytton 

The data you are compiling should start from 31st August 2017 to 31st December 2018. I have updated  the profiles.

**Comment by chrismytton** [comment]
@JessMusila Thanks! There still seems to be one person with multiple party memberships. [Hon. Capt. Ruweida Mohamed Obo](http://info.mzalendo.com/person/ruweida-mohamed-obo/) is listed as JP and TNA. Does the TNA membership need an end date?

**Comment by JessMusila** [comment]
@chrismytton I have fixed the problem in Hon. Capt. Ruweida Mohamed Obo's profile. See http://info.mzalendo.com/person/ruweida-mohamed-obo/

**Comment by chrismytton** [comment]
Speech counts generated and emailed to @JessMusila.

The speech counts were generated with:

```
./manage.py kenya_hansard_speech_statistics --date-from=2017-08-31 --date-to=2018-12-31
```
