### ISSUE TITLE
[ZA] Updated export of National Assembly committee memberships

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2562]
PMG have requested an up-to-date CSV of committee memberships, similar to the one we generated for them last year (see https://github.com/mysociety/pombola/issues/2418).

However they _only_ want details of National Assembly Committees this time. They haven't said explicitly, but I assume they still want the data from May 2014 onwards.

Here's the email Gaile sent requesting this information:

> The State Capture Commission asked PMG today for Committee Membership information.
>
> This information was sent to us  by mySociety in July last year — https://gist.github.com/jacksonj04/787dcf9d64474e77e46adfcadbb10a2f
>
> Would it be possible to provide an update that includes TO DATE?
>
> We are looking for only NATIONAL ASSEMBLY COMMITTEES - is it possible to exclude the NCOP / JOINT / AD HOC COMMITTEES

**Comment by jacksonj04** [comment]
Updated version including only NA Committees at https://gist.github.com/jacksonj04/6fa65722950bd83f311516b7bb4429d7

**Comment by chrismytton** [comment]
@jacksonj04 Would you mind commenting on this issue with the SQL you used to get this data? In case we need to generate this report again in the future 🙂

**Comment by jacksonj04** [comment]
I ended up modifying the [`south_africa_export_committee_members`](https://github.com/mysociety/pombola/blob/a6678e5aba43bbc285c20e3c714b0dd3cad05a70/pombola/south_africa/management/commands/south_africa_export_committee_members.py) command which we used previously to do this, once I remembered that was how I solved it last time.

Usage is `python manage.py south_africa_export_committee_members output.csv`.

**Comment by chrismytton** [comment]
👌 Perfect, thanks @jacksonj04!
