### ISSUE TITLE
[KE] Remove survey banner from the blog

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2564]
From Jessica:

> Please remove the user survey banner from our blog. We had requested for it to come down before the People's Shujaaz Awards in late November & December 2018.

Looks like it was removed from the pombola site as part of https://github.com/mysociety/pombola/pull/2535, but we forgot to remove it from the [Wordpress blog](http://www.mzalendo.com/blog/).

**Comment by chrismytton** [comment]
@zarino Is this something you might be able to do? I'm guessing this change needs to be made in the orgsites repo, which I am totally unfamiliar with!

**Comment by zarino** [comment]
@chrismytton I will look at it today 👍

**Comment by zarino** [comment]
@chrismytton The banner has now been removed from blog pages: http://www.mzalendo.com/blog/

**Comment by chrismytton** [comment]
Great, thanks @zarino! I'll let Jessica know.
