### ISSUE TITLE
[KE] User account management March 2019

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2568]
Following on from #2551 Mzalendo has had some more staffing changes. We need to disable an old user account and create a new one for the admin section.

- [x] De-activate Derrick's account
- [x] Create a new user account with the same permissions as Derrick's

@JessMusila to provide details on the new user account.

**Comment by JessMusila** [comment]
@chrismytton 
Rachael Gichuki has replaced Derrick Makhandia as our program officer. Please create a mzalendo admin account for her and deactivate Derrick's admin rights. Her rights should be similar as Derrick used to have. Rachael's email is rachael@mzalendo.com

**Comment by chrismytton** [comment]
Done, login details sent securely to @JessMusila.
