### ISSUE TITLE
[KE] Remove people’s Shujazz banner on homepage

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2569]
People’s Shujazz banner: request to remove the banner and put back the links that used to be there.

I think this is referring to this part of the homepage:

![image](https://user-images.githubusercontent.com/22996/53958507-25eed200-40d9-11e9-98ec-f03ee196be24.png)

**Comment by chrismytton** [comment]
@zarino you seemed to know what needed to be done here, can I leave this in your capable hands? 🙂

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/pombola/pull/2570

**Comment by chrismytton** [comment]
Thanks @zarino!

@JessMusila This has now been done and is live at http://info.mzalendo.com.

![image](https://user-images.githubusercontent.com/22996/54114059-7ae45e00-43e1-11e9-9555-f65dee027745.png)

**Comment by JessMusila** [comment]
Awesome!! @chrismytton and @zarino
