### ISSUE TITLE
[ZA] WriteInPublic will need updating after 2019 elections

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2593]
We will need to update EveryPolitician after the May 2019 elections so that it gets through to WriteInPublic.

Alternatively we could eliminate the EveryPolitician bit of this process and get WriteInPublic reading data directly from People's Assembly via an API which produces appropriately formatted Popolo JSON. That would be abandoning our vision for getting all data from the commons, but it would make future maintenance simpler for people not familiar with EveryPolitician.

**Comment by chrismytton** [comment]
Have discussed this with the rest of the team and decided that decoupling the South Africa WriteInPublic from EveryPolitician is the way to go. I think the simplest thing to do is create a WriteInPublic-compatible Popolo JSON API in pombola and point WriteInPublic at that.

**Comment by chrismytton** [comment]
Have created https://github.com/mysociety/pombola/issues/2651 to track removing EP and adding a WiP-friendly Popolo JSON API to pombola.

**Comment by chrismytton** [comment]
PMG have sent us files containing the email addresses that need to be added. Since we're going to be getting the information from a new pombola API we can simply add these email addresses as contact details in pombola.

- [National Assembly](https://github.com/mysociety/pombola/files/3361659/NA.emails.csv.txt)
- [Committees](https://github.com/mysociety/pombola/files/3361658/WRITE.TO.A.COMMITTEE.list.-.June.2019.xlsx)

**Comment by chrismytton** [comment]
Seems that the National Assembly CSV that I added in my previous comment has some extra cruft on the end of the surnames which makes it tricky to match them up to the correct person in the database. I've emailed PMG to ask for a fixed version of the CSV.

**Comment by chrismytton** [comment]
Pull request to import the National Assembly emails here: https://github.com/mysociety/pombola/pull/2655

I'll do a separate one for the committees.

**Comment by chrismytton** [comment]
Pull request to add the committee emails here: https://github.com/mysociety/pombola/pull/2658

**Comment by chrismytton** [comment]
Emails from those CSV/XLS files for the National Assembly members and the committees are now loaded into the live People's Assembly database.

Next steps:

- [ ] Check that the new committee emails are being imported into WriteInPublic
- [ ] Add a WriteInPublic-compatible Popolo API endpoint for NA members, similar to existing one for committees. @jacksonj04 Is there a branch or PR for this yet? No worries if not!
- [ ] Switch the WriteInPublic source for NA members to pull from new Popolo API and check that new emails are correctly pulled in.

**Comment by jacksonj04** [comment]
@chrismytton Popolo branch is at #2659, which matches Committees except for the ID (since I'm not sure what WiP would like to see, although it's an easy change to use a different ID than the URL)

**Comment by chrismytton** [comment]
Done. See https://github.com/mysociety/pombola/issues/2651 and linked issues/pull requests for more details.
