### ISSUE TITLE
Update to run on latest version of Debian (stretch)

### ISSUE THREAD

**Issue by chrismytton** [mysociety/pombola#2596]
The servers that pombola are running on are going to be updated to the latest version of Debian soon, so we need to check pombola works on the newer version of Debian.

I think one of the main challenges will be getting it working on the newer version of Elasticsearch. The latest version at time of writing is 7.0.1, but django-haystack, which is the Elasticsearch interface we use, hasn't done a release recently, so even the support for Elasticsearch 5 is unreleased currently.

**Comment by chrismytton** [comment]
Related to https://github.com/mysociety/sysadmin/issues/682.

**Comment by chrismytton** [comment]
Looks like we'll also need to update elasticsearch in django-sayit and za-hansard.

**Comment by chrismytton** [comment]
Discussed with @sagepe and he's going to look at updating and modernising the vagrant setup. That should allow us to test pombola on stretch and try out newer versions of Elasticsearch.

**Comment by chrismytton** [comment]
Elasticsearch version 5 appears to be supported by django-haystack, though that support hasn't been released to PyPi, so we'd have to use it directly from git.

**Comment by sagepe** [comment]
I've got a working Vagrant environment with a Stretch-based box working. This also makes the location of the virtualenv, gems, media files, caches, etc configurable.

It's still a WIP, but see the vagrant-stretch branch for the current status; a PR will follow soon once we've had the chance to test a bit more.

**Comment by chrismytton** [comment]
@sagepe Awesome! I'll give it a spin tomorrow and report back.

@jacksonj04 Would be good if you could kick the tyres on this as well, if that's OK. Thanks!

**Comment by sagepe** [comment]
Some notes:

* Before you start, delete or move any local `conf/general.yml` present in your local working copy. If you want to experiment with varying the `COUNTRY_APP` or `DATADIR` variables you'll also need to do this. (It's probably worth adding a small script to optionally do this like the `script/setup` script from the [scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) pattern.)

* `vagrant up` by default will start a Kenya-themed VM with ES 0.90. The virtualenv etc will be at `/home/vagrant/` and your local working copy mapped to `/vagrant`.

* If you want to use a different version of ES, start with `ES_VERSION=foo vagrant up`. `foo` can be any one of 0.90, 1, 2 or 5 and the actual version installed will be the final release for each major version.

* If you want to start up a PA version, start with `COUNTRY_APP=south_africa vagrant up`.

* If you want to put the virtualenv, etc, somewhere else (for example `data/` in the repo), start with `DATADIR=data vagrant up` (although this will be very slow).

* You can, of course, specify multiple environment variables when starting.

**Comment by chrismytton** [comment]
@sagepe This is great! ✨ The pages seems to load a fair bit faster now, which is an unexpected (to me) bonus!

I've experimented with setting `COUNTRY_APP` to both `kenya` and `south_africa` and they work as expected.

> If you want to experiment with varying the `COUNTRY_APP` or `DATADIR` variables you'll also need to do this. (It's probably worth adding a small script to optionally do this like the `script/setup` script from the [scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) pattern.)

I wouldn't worry about adding an extra script, this repo is going to be split into two separate repos really soon and at that point we can just make the appropriate country the default for each repo, and people won't need to switch countries. Also you'd have to destroy and recreate the box anyway, as the database would have data for the other country in it etc.

One other _very_ minor thing, at the end of provisioning it says `Log in and run /vagrant/manage.py runserver 0.0.0.0:8000 to view the site.`, which works, but then I instinctively went to http://0.0.0.0:8000/ in the browser, which doesn't work because it needs to be http://localhost:8000 for Django security reasons, so perhaps worth making that explicit?

**Comment by chrismytton** [comment]
@sagepe and I just migrated www.pa.org.za to a new server, so that is now running on stretch.

**Comment by chrismytton** [comment]
Pombola has now been updated to run on Debian Stretch.
