### ISSUE TITLE
Define which parts of Pombola are core/country-specific/obsolete

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/pombola#2603]
* [x] Create a new branch in the existing repository (#2604)
* [x] Scrub away anything which isn't involved in making either Kenya or South Africa work (with some extra judgement calls made for Nigeria)
* [x] Make notes on where country-specific code appears in unexpected places (ie anywhere which is not in a country-specific directory)
* [x] Fix where possible anything where non-country-specific code is summoned from a country-specific directory. In theory this shouldn't happen, but you never know.

**Comment by chrismytton** [comment]
This is now done. Tracking the actual repo split in https://github.com/mysociety/pombola/issues/2630.
