### ISSUE TITLE
Add 'Recent Tweets' tab to people who have twitter accounts

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#306]
Can reuse the code that we use for the homepage tweets. Although this might lead to us hitting the twitter rate limit...

**Comment by paullenz** [comment]
Would we feasibly able to do this with the Twitter API?

**Comment by tmtmtmtm** [comment]
You could just add an [Embedded User Timeline](https://dev.twitter.com/web/embedded-timelines/user), without needing any API or server-side stuff at all.
