### ISSUE TITLE
Don't rely on external repos for deploy

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#319]
GitHub just had a hiccup that prevented a deploy to stage. We don't need to check the external repos all the time and shouldn't rely on them for a deploy. Not sure what the solution is.

Arguably this is a pip issue, but that's not helpful :)

**Comment by paullenz** [comment]
I am assuming that this is either resolved through the sys ad changes that have taken place since raised, or else not material as no-one has detailed this as a problem in the last 3.5 years
