### ISSUE TITLE
using simplify tolerance on some kml outputs leads to polygons being dropped

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#443]
Effect of this is that some maps don't appear correctly: eg on http://info.mzalendo.com/place/malava/#related-places

One fix is to remove the simplify_tolerance parameter on all maps, but this might lead to a big increase in the size of the KML sent from the server.

For the 211 constituencies this affects about six of them:  Kisumu Town East, Malava, Muhoroni, Sabatia, Sotik & Ugenya

**Comment by paullenz** [comment]
Give the low level of constituencies affected and the lack of user demand, closing
