### ISSUE TITLE
improve "Related Places" information on places pages

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#450]
Relationships between places in Pombola are currently represented by the `parent_place_id` column of the `core_places` table.  This would be sufficient with an exactly nested hierarchy of places, but in Nigeria, for example, there is no straightforward inclusion relationship between States, Senatorial Districts and Federal Constituencies.  For examples of Federal Constituencies that are split across multiple States, and Senatorial Districts are split across multiple States, see the output of the `core_set_area_parents` management script:

https://gist.github.com/4149839

For the moment, I have added a parent relationships where there is a 98% overlap between a child area and a unique parent, considering SEN->STA and FED->STA.  It would be good to include information about all overlapping areas as well as just strict inclusion between those pairs.

We could do this by querying MapIt on demand (either server-side or in javascript in the browser) to find the overlapping regions, but those queries can be very slow - it would be better to have a join table with an additional column to express the type of relationship between the two areas.

**Comment by paullenz** [comment]
Is this still an issue /  has the solution implemented resolved to a sufficiently good level?

**Comment by tmtmtmtm** [comment]
Moved to https://github.com/theyworkforyou/shineyoureye/issues/5 for the NG case. We can re-open separately if we need something similar anywhere else.
