### ISSUE TITLE
area type codes in MapIt for Kenya should be 3 uppercase letters

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#495]
At the moment the codes for area types in MapIt for Kenya are 3 lower-case letters:

    [<Type: Country (ctr)>,
     <Type: Province (pro)>,
     <Type: District (dis)>,
     <Type: Division (div)>,
     <Type: Location (loc)>,
     <Type: Sub-location (sub)>,
     <Type: Constituency (con)>]

Unfortunately, this means that you can't do lookups like:

    /mapit/areas/dis.html

... since MapIt interprets that as looking for areas whose names begin "dis" rather than all areas of type "dis".  These should be uppercase.

**Comment by tmtmtmtm** [comment]
@mhl is this still an issue?

**Comment by mhl** [comment]
@tmtmtmtm Yes.
