### ISSUE TITLE
Kenya: fix the Central ward confusion

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#645]
I can't find CENTRAL WARD (from the gazette) in the database or the API names.

In the gazette, have two wards called something like "central":

    One in county Embu, constituency Runyenjes, called "Central Ward" (winner: Steve Munene Mugendi)

    One in county Kitui, constituency Mwingi Central, called "Central" (winner: Benard Mwangangi Munyasya)

In the database, we have "Central" in Runyenjes, but one of the aspirants was Benard Mwangangi Munyasya - so, the database is almost certainly wrong. We should:

- [ ] Create the ward "Central" in Mwingi Central
- [ ] Rename the ward "Central" in Runyenjes to "Central Ward"
- [ ] Set Steve Munene Mugendi as the elected ward representative in "Central Ward" (Runyenjes)
- [ ] Set Benard Mwangangi Munyasya as the elected ward representative in "Central" (Mwingi Central)
- [ ] Find all the aspirant ward representatives for Central Ward in Runyenjes, and change their place to Central in Mwingi Central

**Comment by paullenz** [comment]
This appears to be no longer an issue based upon searching today
