### ISSUE TITLE
feature request: promise tracking

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#678]
Many people have mentioned a couple of features they would like Mzalendo to be able to provide:

- <del>Budget tracking/monitoring for the parliament or similar</del> (moved to #681)
- Promise tracking (https://docs.google.com/spreadsheet/ccc?key=0Ar1LyYAE_Sn3dFlVRmN6QTc4YTcwUktTemJ6YVZvMmc#gid=0 different ones available here with various merits)

What else have people said they might want?

**Comment by paullenz** [comment]
Closing for now as part of Pombola as, if required, possibly part of YNR or EP
