### ISSUE TITLE
assess the work involved for i18n and l10n of Pombola

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#684]
via @JenMysoc we have had a request to be able to translate Pombola into another language: Shona in this case.  The first step towards this, I think, should be figuring out how large a bit of work this would be, so that's what this ticket is for.  Some considerations, for example:
* The Django documentation for internationalization has changed significantly since 1.3, so it may be that #676 could help
* To what extent does it make sense to do this incrementally - picking out some set of strings that the customers are particuarly keen to have translated in the first instance?
* What would be a reasonable time estimate for enabling localization in Pombola?
* Presumably we would want to use Transifex again for this, but is it worth considering other options?
There's probably a couple of days work in just investigating the points above, I'd have thought.

**Comment by johnfelipe** [comment]
Its possible transifex?

**Comment by mhl** [comment]
@johnfelipe: Not yet, I'm afraid

**Comment by tmtmtmtm** [comment]
This isn't a current priority, so closing for now. Can re-open new tickets when this changes.
