### ISSUE TITLE
South Africa: fix Metropolitan Municipalities in MapIt

### ISSUE THREAD

**Issue by mhl** [mysociety/pombola#695]
The hierarchy of places in South Africa, from Province down is a bit like this:

     -------------------------------------------------------------------
    | Province                                                          |
    --------------------------------------------------------------------
    | Metropolitan M.         | District M.               | District M. |
    -                         ------------------------------------------
    |                         | Local M.    | Local M.    | Local M.    |
    --------------------------------------------------------------------
    | Ward | Ward | Ward      | Ward | Ward | Ward | Ward | Ward | Ward |
    --------------------------------------------------------------------

However, both the `LocalMunicipalities2011.shp` and `DistrictMunicipalities2011.shp` files contained boundaries for the Metropolitan Municipality boundaries, so we've ended up with two copies of each Metropolitan Municipality, one of type `LMN` and one of type `DMN`, e.g.

http://za.mzalendo.dev.mysociety.org/mapit/area/8131.html
http://za.mzalendo.dev.mysociety.org/mapit/area/8365.html

There should only be one of those, of type `MMN`.

(This isn't urgent compared to the other things we have to do on this site at the moment, since we don't have any people associated with MMNs, but it would be good to fix.)

**Comment by tmtmtmtm** [comment]
Does this actually cause any issues, or is it just duplication that we'd like to remove?

**Comment by tmtmtmtm** [comment]
Accidentally hit the 'close' button there — but actually I'm going to leave this closed unless it's something we think we're ever actually going to fix.

**Comment by mhl** [comment]
Yeah, I think it's fine to close - if anything, we should consider moving to using the Code4SA MapIt instead, in which case this would no longer be our problem.
