### ISSUE TITLE
Correct typo on politician profile page

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#712]
'Legislative' is misspelled in the summary area in the politician profile page. This is likely a data issue.

*Legistlative Interest(s): NA*

http://www.shineyoureye.org/person/ojudu-babafemi/

**Comment by tmtmtmtm** [comment]
Still an issue:

![screen shot 2015-11-13 at 15 34 48](https://cloud.githubusercontent.com/assets/57483/11149705/17dcf47a-8a1c-11e5-850d-70ebf5c55d55.png)

**Comment by JenMysoc** [comment]
I think I need to do this through the administration of the site: can someone give me access?

**Comment by tmtmtmtm** [comment]
@JenMysoc you can presumably fix this now…

**Comment by JenMysoc** [comment]
Done!

**Comment by tmtmtmtm** [comment]
Yay!

![screen shot 2016-02-22 at 10 36 46](https://cloud.githubusercontent.com/assets/57483/13215843/3c9ab832-d950-11e5-8901-7d7e1c535497.png)
