### ISSUE TITLE
Make static strings in the template translatable

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#713]
In the templates there are several generic strings such as "Subscribe to receive updates" that should be translatable.

- [x] decide which approach to take ([Django's default](https://docs.djangoproject.com/en/1.4/topics/i18n/translation/) seems best)
- [x] decide if the translation keys should be the english text (default) or some string identifier (the Rails way)
- [x] set up the translation framework
- [ ] identify and mark up strings requiring translation
- [ ] generate `.po` files
- [ ] place onto transifex (or equivalent) for others to start translating

**Comment by tmtmtmtm** [comment]
unlikely to do i18n any time soon — can re-open when that changes.
