### ISSUE TITLE
Translate content stored in the database 

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#717]
**NOTE: THIS IS HIGHLY SPECULATIVE AND SHOULD ONLY BE IMPLEMENTED AFTER EXTENSIVE DISCUSSION**

Some content, like the `summary` field for a person, will contain free text that should perhaps be translated into the various languages that the users of the Pombola site may be expected to prefer.

This could be achieved by using apps such as [django-hvad](http://django-hvad.readthedocs.org/en/latest/)

My (@evdb) concern is that this will complicate the code base for relatively little gain as my suspicion is that the burden of maintaining records in several languages will be so great that it will not actually be done. The very few cases that it will be done in will not justify the extra burden this would place on all sites (even ones that only use a single language)

This ticket here to store the conversation on this topic.

**Comment by tmtmtmtm** [comment]
unlikely to do i18n any time soon — can re-open when that changes.
