### ISSUE TITLE
Move most settings into database so they can be set in admin

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#722]
This would allow admins of the site to change them making management of the site easier. Missing settings would not be caught during deploy, so sensible defaults would need to be provided.

Looking at all the settings in `general.yml-example` the following three types exist:

## Need to be set from config on server:

These are values that are needed to connect to database, expected (or used to set other keys that are expected) by django to be available via `django.conf.settings` or are used to configure the app at start up (so would need a reboot to take effect).

```
POMBOLA_DB_HOST
POMBOLA_DB_PORT
POMBOLA_DB_USER
POMBOLA_DB_NAME
POMBOLA_DB_PASS

STAGING
TIME_ZONE

DJANGO_SECRET_KEY

MANAGERS_NAME
MANAGERS_EMAIL

ERRORS_NAME
ERRORS_EMAIL

FROM_EMAIL

SELENIUM_PATH

COUNTRY_APP
OPTIONAL_APPS
```

## Could be stored in database:

These are used rarely, are used in templates, and can all have sensible defaults.

```
GOOGLE_ANALYTICS_ACCOUNT

IEBC_API_ID
IEBC_API_SECRET

KENYA_PARSER_PDF_TO_HTML_HOST

DISQUS_SHORTNAME
DISQUS_USE_IDENTIFIERS

POLLDADDY_WIDGET_ID

TWITTER_USERNAME

TWITTER_WIDGET_ID

BLOG_RSS_FEED

MAP_BOUNDING_BOX_NORTH
MAP_BOUNDING_BOX_EAST
MAP_BOUNDING_BOX_SOUTH
MAP_BOUNDING_BOX_WEST
```

There may well be a settings app that will do most of this for us.

**Comment by paullenz** [comment]
Our partner admin users only currently work on site data - they don't need this level of control - given this and the lack of likely future sites (and those that may come are most likely to be technically managed by mySociety) I am closing
