### ISSUE TITLE
Change code so that after a map selection redirect is to correct place

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#723]
Extracted from #693:

> [On the map page] for ZA at least [the post selection redirect] needs to link through to the output of #691 rather than a mapit place page.

This will require changing the `place_mapit_area` view in the [core views](https://github.com/mysociety/pombola/blob/master/pombola/core/views.py).

**Comment by tmtmtmtm** [comment]
I'm closing this, as it doesn't actually seem to be a problem on a live site. If it's actually causing issues, please open a new ticket for the specific case.
