### ISSUE TITLE
Replace Pombola Hansard app with SayIt

### ISSUE THREAD

**Issue by dracos** [mysociety/pombola#764]
- [ ] Migrate any existing data from hansard app to sayit models
- [ ] Move Kenya hansard scraping/parsing to its own separate app

**Comment by tmtmtmtm** [comment]
Much as this might be nice, it's unlikely to happen unless there's a clear benefit, to justify the amount of work required, particularly as SayIt doesn't provide some of the functionality that Mzalendo needs.  Can revisit later if wider strategy pushes us in this direction.
