### ISSUE TITLE
Organisation > People list - loading times, page size

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/pombola#789]
Noticed while browsing Mzalendo that when the number of people in an organisation is large the page load times are glacial

37 seconds to load this one http://info.mzalendo.com/organisation/odm/people/ with a 4.1mb payload

I couldn't get this one to load fully without Chrome thinking the page had become unresponsive, it was well over 90s and 10mb in size - http://info.mzalendo.com/organisation/cord/people/.

**Comment by paullenz** [comment]
This has materially improve since the ticket was opened - closing
