### ISSUE TITLE
Feature idea: Allow CSV import of MP data

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/pombola#824]
It could be good for international reusers to have the option to import their gathered MP (such as email addresses, education, history etc) data via csv file rather than manually entering in the data to the website. 

We would need to document exactly how they should present the data and give clear notice that if it is not presented in this way, the data will not upload correctly, so a helpful error message should present itself.

**Comment by paullenz** [comment]
Given the infrequency of setting up a new site, rather than develop this as separate functionality, suggest that we continue as we have done with SYE where CSV is mailed in and a developer imports it

**Comment by tmtmtmtm** [comment]
Or, indeed, that the import happens through EveryPolitician…
