### ISSUE TITLE
Move country specific config into country apps.

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#829]
At the moment there are several bits of config that could come directly from the country app - for example the [country bounding box](https://github.com/mysociety/pombola/blob/d43a3c17432db5ec063501dad54c0b06ca47d98b/conf/general.yml-example#L84-L89). It would make sense to move this to the country app so that simply [changing that](https://github.com/mysociety/pombola/blob/d43a3c17432db5ec063501dad54c0b06ca47d98b/conf/general.yml-example#L78-L82) would set other values correctly.

**Comment by tmtmtmtm** [comment]
Looks like this was done in #722
