### ISSUE TITLE
Correct za-hansard parsing of section titles ("Members Statement" etc)

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#842]
On pages like http://za.mzalendo.dev.mysociety.org/speeches/sections/108 the section headers contain apostrophe errors: "Members Statement" should be "Member's Statement". This may well be an error in the source data.

![view_section__proceedings_of_national_assembly__tuesday__10_august_2010_____pombola_south_africa](https://f.cloud.github.com/assets/187630/1287455/2b2ffd06-2ff6-11e3-8a95-ca2a6337f568.png)

**Comment by paullenz** [comment]
No longer significant - closing
