### ISSUE TITLE
prepare_environmeth virtualenv version check does not work on Mac OSX

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#869]
The `sort` provided does not support the `-V` flag used on [line 18](https://github.com/mysociety/pombola/blob/master/bin/prepare_environment.bash#L18)

```
evdb@macosx-10.8.5 ~ $ echo -e '1.7\n1.2.3' | sort -V | head -1
sort: invalid option -- V
Try `sort --help' for more information.
```

**Comment by tmtmtmtm** [comment]
Is this still an issue? I'm guessing this is something that isn't currently hurting us because no-one working on the code is using OSX?

**Comment by chrismytton** [comment]
The GDAL requirement was removed in https://github.com/mysociety/pombola/commit/ad6364e4dd93ec29aa3d068e6f3b4ccba486af10 as part of https://github.com/mysociety/pombola/pull/2078, so I think we can simply [remove this part of `prepare_environment.bash`](https://github.com/mysociety/pombola/blob/5d1a67ba21e84d8713e1851545ccd91102e45153/bin/prepare_environment.bash#L15-L21) and close this ticket now.

**Comment by chrismytton** [comment]
Looks like even without GDAL this still needs `--system-site-packages` in order to install bcrypt. I think it will be simpler to switch to using @dracos' version of the `sort(1)` command.

**Comment by chrismytton** [comment]
@dracos has pointed out that bcrypt *should* install cleanly, indeed when I actually activate the virtualenv that I've created it does install cleanly.
