### ISSUE TITLE
Tidying committee membership information

### ISSUE THREAD

**Issue by dracos** [mysociety/pombola#878]
The current people JSON file contains committee information from both the Parliament site and CSV files (in the `data` directory). There are a number of issues with the data that need sorting e.g. if you're listed on Parliament site as having a "Position" of committee chairperson, that'll be in the JSON file as e.g. "Chairperson of Select Committee on Land and Environmental Affairs at National Council of Provinces (House)", when it's not really a house membership at all. There are probably also overlapping identical memberships.

For example, Yolanda Rachel Botha is listed currently as "Chairperson of Portfolio Committee on Social Development at National Assembly (House)", "Chairperson at Social Development (National Assembly Committees)", "Member at Ad Hoc Committee on Coordinated Oversight on Service Delivery (Ad Hoc Committees)" and "Member at Portfolio Committee On Social Development (Committee)". There are also currently multiple organisation kinds for Committees too, we can see from this.

It might be easiest just to drop the Parl information, import only from the CSV, then start making manual database changes.

**Comment by paullenz** [comment]
Closing as should be resolved by obtaining committee data from the Code4SA API rather than scraping
