### ISSUE TITLE
ZA: person page tab selection should change url

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#930]
On eg http://za-pombola.staging.mysociety.org/person/bomo-edna-edith-molewa/ if you select the profile tab and then share the url the person opening it will not see the profile tab.

Perhaps use a fragment, and then detect the fragment on page load. The old tab code used to do this, could dig that out if helpful.

**Comment by mhl** [comment]
Fixed by https://github.com/mysociety/pombola/pull/1820, I think
