### ISSUE TITLE
Tidy up old unmerged branches

### ISSUE THREAD

**Issue by evdb** [mysociety/pombola#967]
There are several branches listed on https://github.com/mysociety/pombola/branches that are now no longer useful and should be deleted.

**Comment by paullenz** [comment]
Is this still needed / a priority?

**Comment by tmtmtmtm** [comment]
There are definitely still a lot of old branches that are almost certainly obsolete, and should really be cleaned out at some point. I don't think it's particularly high priority, though it would be good to come with a plan to gradually clean it up.

**Comment by tmtmtmtm** [comment]
This is something we should probably be doing regularly, but doesn't need a ticket.
